/* v1.6.66.9.9 — Caravan Master, Defeat & Mount Recovery */
const CARAVAN_MASTER_CANDIDATES=[
 {id:'toma_reed',name:'Toma Reed',competence:4,salary:88,capacity:5,trait:'Careful Drover',desc:'A patient pack-train handler who favors safe roads and orderly baggage lines.'},
 {id:'vesa_morn',name:'Vesa Morn',competence:6,salary:124,capacity:8,trait:'Road Captain',desc:'A veteran caravan hand comfortable moving valuable animals through unsettled country.'},
 {id:'halren_voss',name:'Halren Voss',competence:8,salary:166,capacity:12,trait:'Remount Keeper',desc:'A skilled remount and baggage officer known for recovering scattered animals after raids and routs.'}
];
function ensureCaravanMasterState(){ensureWorldState();if(!state.world.caravanMaster||typeof state.world.caravanMaster!=='object')state.world.caravanMaster={active:false,master:null,lastSalaryDay:state.world.day,recoveries:[],history:[]};const C=state.world.caravanMaster;if(!Array.isArray(C.recoveries))C.recoveries=[];if(!Array.isArray(C.history))C.history=[];return C}
function caravanMaster(){return ensureCaravanMasterState().master}
function caravanMasterActive(){const C=ensureCaravanMasterState();return !!(C.active&&C.master)}
function caravanMasterHire(id){const C=ensureCaravanMasterState(),c=CARAVAN_MASTER_CANDIDATES.find(x=>x.id===id);if(!c||C.master)return showCaravanMaster();C.master={...c,hiredDay:state.world.day};C.active=true;C.lastSalaryDay=state.world.day;C.history.push({day:state.world.day,text:`${c.name} hired as Caravan Master.`});save();showCaravanMaster()}
function caravanMasterSetTravel(active){const C=ensureCaravanMasterState();if(!C.master)return showCaravanMaster();C.active=!!active;save();showCaravanMaster()}
function caravanMasterConversation(){
 const M=caravanMaster();if(!M)return showCaravanMaster();const packs=mountPackAnimals().length,missing=ensureMountState().owned.filter(m=>m.status==='missing').length;
 overlay(`<h2>Speak with ${esc(M.name)}</h2><p>${packs?`“I have ${packs} pack animal${packs===1?'':'s'} accounted for. ${packs>M.capacity?'We are stretched too thin; the line will move badly until we reduce it.':'The train is within what I can manage cleanly.'}”`:'“Give me animals and a road, and I will keep the baggage together.”'}</p>${missing?`<p>“We still have ${missing} animal${missing===1?'':'s'} unaccounted for. They are not gone for good. Give me the time and protection and I will bring them home.”</p>`:''}<div class="dialog-footer"><button id="cmTalkBack">Back</button></div>`,true);$('#cmTalkBack').onclick=showCaravanMaster
}
function showCaravanMasterCandidates(){guardianHallRouteEnter('showCaravanMasterCandidates',[]);overlay(`<h2>Hire a Caravan Master</h2><p>This is a dedicated traveling specialist position. The Caravan Master does not consume a companion slot and normally withdraws the animals from battle rather than fighting.</p>${CARAVAN_MASTER_CANDIDATES.map(c=>`<div class="card"><h3>${esc(c.name)}</h3><p>${esc(c.desc)}</p><small>${esc(c.trait)} • Competence ${c.competence}/10 • manages ${c.capacity} pack animals • ${c.salary}g / 14 days</small><button data-cmhire="${c.id}">Hire</button></div>`).join('')}<div class="dialog-footer"><button id="cmHireBack">Back</button></div>`,true);document.querySelectorAll('[data-cmhire]').forEach(b=>b.onclick=()=>caravanMasterHire(b.dataset.cmhire));$('#cmHireBack').onclick=showCaravanMaster}
function caravanRecoveryDays(m,master,escort='none'){const quality=(m.stats.speed+m.stats.stamina+m.stats.courage)/3,skill=master?.competence||1,escortBonus=escort==='guards'?2:escort==='soldiers'?3:0;return Math.max(1,Math.min(8,Math.ceil(6+quality/5-skill*.55-escortBonus)))}
function caravanRecoveryCost(m,escort='none'){const value=m.purchasePrice||500,base=Math.max(40,Math.round(value*.04/10)*10);return base+(escort==='guards'?180:escort==='soldiers'?350:0)}
function caravanStartRecovery(id,escort='none'){const C=ensureCaravanMasterState(),M=C.master,m=ensureMountState().owned.find(x=>x.id===id&&x.status==='missing');if(!M||!m)return showCaravanMaster();const cost=caravanRecoveryCost(m,escort);if(state.gold<cost)return actionResult('Recovery Cannot Depart',`Preparing the search requires ${cost}g.`,'bad',showCaravanMaster);state.gold-=cost;const days=caravanRecoveryDays(m,M,escort);m.status='recovery_search';m.recoveryDueDay=state.world.day+days;m.recoveryEscort=escort;C.recoveries.push({mountId:m.id,name:m.name,startDay:state.world.day,dueDay:m.recoveryDueDay,escort,cost});C.history.push({day:state.world.day,text:`${M.name} departed to recover ${m.name}; expected ${days} day${days===1?'':'s'}.`});save();showCaravanMaster()}
function caravanMasterDailyTick(){if(!isOpenWorld())return;const C=ensureCaravanMasterState(),M=C.master;if(M&&state.world.day-(C.lastSalaryDay||state.world.day)>=14){if(state.world.homeBase?.logistics?.budget>=M.salary){homeFinanceDebit(M.salary,'Caravan staff',`${M.name}, Caravan Master`);C.lastSalaryDay=state.world.day}}for(const m of ensureMountState().owned){if(m.status==='recovery_search'&&m.recoveryDueDay<=state.world.day){m.status='owned';m.assignment='hall_stable';m.fatigue=Math.max(15,m.fatigue||0);delete m.recoveryDueDay;delete m.recoveryEscort;C.history.push({day:state.world.day,text:`${M?.name||'The recovery party'} returned ${m.name} safely to Guardian Hall.`})}}C.recoveries=C.recoveries.filter(r=>ensureMountState().owned.some(m=>m.id===r.mountId&&m.status==='recovery_search'));C.history=C.history.slice(-80)}
function caravanMasterBattleDefeat(){
 if(!isOpenWorld())return null;const C=ensureCaravanMasterState(),M=caravanMasterActive()?C.master:null,animals=ensureMountState().owned.filter(m=>m.status==='owned'&&['riding','pack'].includes(m.assignment));if(!animals.length)return null;
 let secured=0,missing=0;for(const m of animals){const difficulty=5+(m.stats.speed||5)*.45+(m.stats.courage||5)*.2,roll=(M?.competence||0)+Math.random()*8;if(M&&roll>=difficulty){m.assignment='hall_stable';m.fatigue=Math.max(m.fatigue||0,25);secured++}else{m.status='missing';m.assignment='missing';m.missingSinceDay=state.world.day;m.missingNear=state.world.location;missing++}}
 if(M){C.history.push({day:state.world.day,text:`After the defeat, ${M.name} secured ${secured} mount${secured===1?'':'s'} and ${missing} became scattered.`})}
 save();return {secured,missing,master:M?.name||null}
}
function showCaravanMaster(){
 guardianHallRouteEnter('showCaravanMaster',[]);const C=ensureCaravanMasterState(),M=C.master,missing=ensureMountState().owned.filter(m=>m.status==='missing'),searching=ensureMountState().owned.filter(m=>m.status==='recovery_search'),packs=mountPackAnimals().length;
 const recover=missing.map(m=>`<div class="card"><b>${esc(m.name)}</b> — ${esc(m.breedName)}<br><small>Missing since Day ${m.missingSinceDay}${m.missingNear?` near ${esc(worldLocation(m.missingNear)?.name||m.missingNear)}`:''}. Owned mounts are never permanently lost.</small>${M?`<div class="button-row"><button data-cmrecover="${m.id}:none">Search — ${caravanRecoveryCost(m,'none')}g</button><button data-cmrecover="${m.id}:guards">With Hall Guards — ${caravanRecoveryCost(m,'guards')}g</button></div>`:''}</div>`).join('');
 overlay(`<h2>Guardian Caravan Master</h2>${M?`<div class="card"><h3>${esc(M.name)}</h3><p>${esc(M.trait)} • Competence ${M.competence}/10 • ${M.salary}g / 14 days</p><p>Efficient pack-animal limit: <b>${M.capacity}</b> • current traveling pack animals: <b>${packs}</b></p><button id="cmTalk">Speak with ${esc(M.name)}</button><button id="cmToggle">${C.active?'Remain at Hall':'Travel with Guardian'}</button></div>`:`<p>No Caravan Master is employed. Without one, more than two pack animals become increasingly cumbersome on the road.</p><button id="cmHire">Hire Caravan Master</button>`}<details class="card compact caravan-missing-mounts" ${missing.length?'open':''}><summary><b>Missing Mounts</b> — ${missing.length?`${missing.length} unresolved`:'None'}</summary><div class="details-body">${missing.length?recover:'<p class="muted">All owned mounts are accounted for.</p>'}</div></details>${searching.length?`<h3>Recovery Parties</h3>${searching.map(m=>`<div class="notice compact"><b>${esc(m.name)}</b> • expected by Day ${m.recoveryDueDay}</div>`).join('')}`:''}<div class="dialog-footer"><button id="cmBack">Back to Guardian Hall</button></div>`,true);
 if($('#cmHire'))$('#cmHire').onclick=showCaravanMasterCandidates;if($('#cmTalk'))$('#cmTalk').onclick=caravanMasterConversation;if($('#cmToggle'))$('#cmToggle').onclick=()=>caravanMasterSetTravel(!C.active);document.querySelectorAll('[data-cmrecover]').forEach(b=>b.onclick=()=>{const [id,e]=b.dataset.cmrecover.split(':');caravanStartRecovery(id,e)});$('#cmBack').onclick=()=>guardianHallRouteBack(showHomeBase)
}

/* v1.6.66.9.20 — Caravan Masters own their working mounts. */
const CARAVAN_MASTER_MOUNT_CHOICES={
 toma_reed:{breedId:'shantium_sable',name:'Waybell',stats:{speed:7,stamina:8,carry:6,surefoot:8,courage:6,recovery:8}},
 vesa_morn:{breedId:'spawn_roadster',name:'Longstep',stats:{speed:8,stamina:8,carry:5,surefoot:7,courage:7,recovery:8}},
 halren_voss:{breedId:'lockwood_ranger',name:'Greywind',stats:{speed:8,stamina:9,carry:6,surefoot:9,courage:8,recovery:9}}
};
function caravanMasterEnsurePersonalMount(){const C=ensureCaravanMasterState(),M=C.master;if(!M)return null;if(!M.personalMount){const x=CARAVAN_MASTER_MOUNT_CHOICES[M.id]||CARAVAN_MASTER_MOUNT_CHOICES.toma_reed,B=MOUNT_BREEDS[x.breedId];M.personalMount={id:`cm_mount_${M.id}`,owner:M.name,name:x.name,species:'horse',breedId:x.breedId,breedName:B?.name||'Riding Horse',stats:{...x.stats},condition:'fresh',fatigue:0,recoverUntilDay:0,personal:true};C.history.push({day:state.world.day,text:`${M.name}'s personal mount, ${x.name}, is recorded with the caravan train.`})}return M.personalMount}
const _caravanMasterBase=caravanMaster;
caravanMaster=function(){const M=_caravanMasterBase();if(M)caravanMasterEnsurePersonalMount();return M};
const _caravanMasterHireBase=caravanMasterHire;
caravanMasterHire=function(id){_caravanMasterHireBase(id);caravanMasterEnsurePersonalMount();save()};
const _showCaravanMasterBase=showCaravanMaster;
showCaravanMaster=function(){caravanMasterEnsurePersonalMount();_showCaravanMasterBase();const M=ensureCaravanMasterState().master,card=document.querySelector('#cmTalk')?.closest('.card');if(M?.personalMount&&card){const p=document.createElement('p');p.innerHTML=`Personal mount: <b>${esc(M.personalMount.name)}</b> — ${esc(M.personalMount.breedName)} • sustainable pace ${mountSustainablePace(M.personalMount).toFixed(1)}`;card.insertBefore(p,document.querySelector('#cmTalk'))}};
