/* UCL GameDay v0.5.03 — build fragment: 15_ctespn_audio.js
   CTESPN Audio Simplification + GameView outcome-timed playback */
const CTESPN_AUDIO_KEY='ucl-gameday-audio-v1';
const CTESPN_AUDIO_DEFAULTS=Object.freeze({enabled:false,muted:false,master:.80,announcer:1,stadium:.85,stingers:.90});
const CTESPN_AUDIO_LONG_RUSH_YARDS=25;
const CTESPN_AUDIO_LONG_RECEPTION_YARDS=30;
const CTESPN_AUDIO_FOLLOWUP_GAP_MS=700;
const CTESPN_AUDIO_HANDLED_LIMIT=500;
const CTESPN_AUDIO_PREPARED_LIMIT=80;
function ctespnAudioSpec(priority,announcerVariants=[],layers=[],timing={milestone:'outcome',ratio:.82}){return Object.freeze({priority,announcerVariants:Object.freeze(announcerVariants),layers:Object.freeze(layers),timing:Object.freeze({...timing})})}
const CTESPN_AUDIO_CATALOG=Object.freeze({
  touchdown:ctespnAudioSpec(100,['assets/audio/announcer/touchdown-01.mp3','assets/audio/announcer/touchdown-02.mp3','assets/audio/announcer/touchdown-03.mp3'],[{channel:'stadium',src:'assets/audio/stadium/touchdown-roar-01.mp3'},{channel:'stingers',src:'assets/audio/stingers/touchdown-01.mp3'}]),
  pick_six:ctespnAudioSpec(110,['assets/audio/announcer/pick-six-01.mp3','assets/audio/announcer/pick-six-02.mp3','assets/audio/announcer/pick-six-03.mp3'],[{channel:'stadium',src:'assets/audio/stadium/turnover-roar-01.mp3'},{channel:'stingers',src:'assets/audio/stingers/turnover-01.mp3'}]),
  kick_six:ctespnAudioSpec(110,['assets/audio/announcer/kick-six-01.mp3'],[{channel:'stadium',src:'assets/audio/stadium/touchdown-roar-01.mp3'},{channel:'stingers',src:'assets/audio/stingers/touchdown-01.mp3'}]),
  scoop_score:ctespnAudioSpec(110,['assets/audio/announcer/scoop-and-score-01.mp3'],[{channel:'stadium',src:'assets/audio/stadium/turnover-roar-01.mp3'},{channel:'stingers',src:'assets/audio/stingers/turnover-01.mp3'}]),
  sack:ctespnAudioSpec(70,['assets/audio/announcer/sack-01.mp3','assets/audio/announcer/sack-02.mp3','assets/audio/announcer/sack-03.mp3'],[{channel:'stadium',src:'assets/audio/stadium/hit-01.mp3'}]),
  qb_intercepted:ctespnAudioSpec(86,['assets/audio/announcer/qb-intercepted-01.mp3','assets/audio/announcer/qb-intercepted-02.mp3','assets/audio/announcer/qb-intercepted-03.mp3'],[{channel:'stingers',src:'assets/audio/stingers/turnover-01.mp3'}]),
  your_player_fumbled:ctespnAudioSpec(84,['assets/audio/announcer/your-player-fumbled-01.mp3','assets/audio/announcer/your-player-fumbled-02.mp3','assets/audio/announcer/your-player-fumbled-03.mp3'],[{channel:'stingers',src:'assets/audio/stingers/turnover-01.mp3'}]),
  defensive_interception:ctespnAudioSpec(88,['assets/audio/announcer/defensive-interception-01.mp3','assets/audio/announcer/defensive-interception-02.mp3','assets/audio/announcer/defensive-interception-03.mp3'],[{channel:'stingers',src:'assets/audio/stingers/turnover-01.mp3'}]),
  fumble_recovery:ctespnAudioSpec(87,['assets/audio/announcer/fumble-recovery-01.mp3','assets/audio/announcer/fumble-recovery-02.mp3','assets/audio/announcer/fumble-recovery-03.mp3'],[{channel:'stingers',src:'assets/audio/stingers/turnover-01.mp3'}]),
  long_rush:ctespnAudioSpec(62,['assets/audio/announcer/long-rush-01.mp3','assets/audio/announcer/long-rush-02.mp3','assets/audio/announcer/long-rush-03.mp3'],[{channel:'stadium',src:'assets/audio/stadium/cheer-01.mp3'}]),
  long_reception:ctespnAudioSpec(64,['assets/audio/announcer/long-reception-01.mp3','assets/audio/announcer/long-reception-02.mp3','assets/audio/announcer/long-reception-03.mp3'],[{channel:'stadium',src:'assets/audio/stadium/cheer-01.mp3'}]),
  late_lead_change:ctespnAudioSpec(96,['assets/audio/announcer/late-lead-change-01.mp3','assets/audio/announcer/late-lead-change-02.mp3'],[{channel:'stingers',src:'assets/audio/stingers/lead-change-01.mp3'}],{milestone:'post_outcome',ratio:1})
});
let ctespnAudioState={...CTESPN_AUDIO_DEFAULTS},ctespnAudioUnlocked=false,ctespnAudioQueue=[],ctespnAudioCurrentPriority=-Infinity;
let ctespnAudioActive=new Set(),ctespnAudioMissing=new Set(),ctespnAudioLastVariant=new Map(),ctespnAudioHandledEvents=new Map(),ctespnAudioPrepared=new Map();
function ctespnAudioLoadState(){try{const raw=storage.get(CTESPN_AUDIO_KEY,'');if(raw)ctespnAudioState={...CTESPN_AUDIO_DEFAULTS,...JSON.parse(raw)}}catch(e){ctespnAudioState={...CTESPN_AUDIO_DEFAULTS}}return ctespnAudioState}
function ctespnAudioSaveState(){try{storage.set(CTESPN_AUDIO_KEY,JSON.stringify(ctespnAudioState))}catch(e){}}
function ctespnAudioSetStatus(text,kind=''){for(const id of ['ctespnAudioStatus','ctespnAudioTestStatus']){const el=document.getElementById(id);if(!el)continue;el.textContent=text;el.classList.remove('ready','warn');if(kind)el.classList.add(kind)}}
function ctespnAudioSetResolverStatus(r){const el=document.getElementById('ctespnAudioResolverStatus');if(!el)return;if(!r){el.textContent='Resolver idle.';return}const calls=[r.primaryKey,r.secondaryKey].filter(Boolean),cue=r.timingPlan?.[0]?.milestone||'outcome';el.textContent=`${r.leadChange?.qualifying?'QUALIFYING LEAD CHANGE':'NO QUALIFYING LEAD CHANGE'} • ${calls.length?calls.join(' → '):'NO ANNOUNCER CALL'} • cue: ${cue} • ${calls.length} automatic call${calls.length===1?'':'s'}`}
function ctespnAudioChannelVolume(channel){if(ctespnAudioState.muted||!ctespnAudioState.enabled)return 0;const key=channel==='announcer'?'announcer':channel==='stingers'?'stingers':'stadium';return Math.max(0,Math.min(1,Number(ctespnAudioState.master||0)*Number(ctespnAudioState[key]||0)))}
function ctespnAudioUnlock(){if(ctespnAudioUnlocked)return;ctespnAudioUnlocked=true;if(ctespnAudioState.enabled)ctespnAudioSetStatus('Audio ready for installed clips.','ready');ctespnAudioDrainQueue()}
function ctespnAudioStopBelow(priority=Infinity){for(const entry of [...ctespnAudioActive]){if(Number(entry.priority||0)>=priority)continue;try{entry.audio.pause();entry.audio.currentTime=0}catch(e){}ctespnAudioActive.delete(entry)}}
function ctespnAudioChooseVariant(key,spec,requestedIndex=null){const variants=spec?.announcerVariants||[];if(!variants.length)return null;if(Number.isInteger(requestedIndex)){const idx=Math.max(0,Math.min(variants.length-1,requestedIndex));ctespnAudioLastVariant.set(key,idx);return variants[idx]}if(variants.length===1){ctespnAudioLastVariant.set(key,0);return variants[0]}const last=ctespnAudioLastVariant.get(key),choices=variants.map((_,i)=>i).filter(i=>i!==last),idx=choices[Math.floor(Math.random()*choices.length)];ctespnAudioLastVariant.set(key,idx);return variants[idx]}
function ctespnAudioResolvedLayers(key,spec,opts={}){const layers=[],announcer=ctespnAudioChooseVariant(key,spec,opts.variantIndex);if(announcer)layers.push({channel:'announcer',src:announcer});layers.push(...(spec?.layers||[]));return layers}
function ctespnAudioPlayLayer(layer,priority){return new Promise(resolve=>{if(!layer?.src||ctespnAudioMissing.has(layer.src)){resolve(false);return}const volume=ctespnAudioChannelVolume(layer.channel);if(volume<=0){resolve(false);return}const audio=new Audio(layer.src),entry={audio,priority,src:layer.src};ctespnAudioActive.add(entry);audio.preload='auto';audio.volume=volume;let settled=false;const finish=ok=>{if(settled)return;settled=true;ctespnAudioActive.delete(entry);resolve(ok)};audio.addEventListener('ended',()=>finish(true),{once:true});audio.addEventListener('error',()=>{ctespnAudioMissing.add(layer.src);ctespnAudioSetStatus(`Missing audio clip: ${layer.src.split('/').pop()}`,'warn');finish(false)},{once:true});const p=audio.play();if(p&&typeof p.catch==='function')p.catch(()=>finish(false));setTimeout(()=>finish(false),12000)})}
async function ctespnAudioRunKey(key,opts={}){const spec=CTESPN_AUDIO_CATALOG[key];if(!spec)return false;const priority=Number(opts.priority??spec.priority??0);if(priority>ctespnAudioCurrentPriority)ctespnAudioStopBelow(priority);ctespnAudioCurrentPriority=priority;await Promise.all(ctespnAudioResolvedLayers(key,spec,opts).map(layer=>ctespnAudioPlayLayer(layer,priority)));ctespnAudioCurrentPriority=-Infinity;return true}
async function ctespnAudioRun(item){if(Array.isArray(item?.sequence)){for(let i=0;i<item.sequence.length;i++){const step=item.sequence[i];if(!step?.key)continue;if(i>0)await new Promise(resolve=>setTimeout(resolve,Number(step.gapMs??CTESPN_AUDIO_FOLLOWUP_GAP_MS)));await ctespnAudioRunKey(step.key,step)}return}await ctespnAudioRunKey(item.key,item)}
async function ctespnAudioDrainQueue(){if(!ctespnAudioUnlocked||!ctespnAudioState.enabled||ctespnAudioState.muted||ctespnAudioDrainQueue.busy)return;ctespnAudioDrainQueue.busy=true;try{while(ctespnAudioQueue.length&&ctespnAudioState.enabled&&!ctespnAudioState.muted){ctespnAudioQueue.sort((a,b)=>Number(b.priority||0)-Number(a.priority||0)||a.time-b.time);await ctespnAudioRun(ctespnAudioQueue.shift())}}finally{ctespnAudioDrainQueue.busy=false}}
function ctespnAudioQueueItem(item){if(!ctespnAudioState.enabled||ctespnAudioState.muted)return false;if(!ctespnAudioUnlocked){ctespnAudioQueue=[item];ctespnAudioSetStatus('Audio armed — interact with the page to unlock playback.','warn');return true}ctespnAudioQueue.push(item);ctespnAudioDrainQueue();return true}
function ctespnAudioPlayEvent(key,opts={}){const spec=CTESPN_AUDIO_CATALOG[key];if(!spec)return false;return ctespnAudioQueueItem({key,priority:Number(opts.priority??spec.priority??0),variantIndex:opts.variantIndex,time:Date.now()})}
function ctespnAudioEventId(evt){return String(evt?.canonicalEventId||evt?.canonicalId||evt?.id||[evt?.time||evt?.timestamp||'',evt?.rosterId||evt?.roster_id||'',evt?.playerId||evt?.player_id||'',Number(evt?.pointDelta??evt?.delta??0).toFixed(3),evt?.detail||''].join('|'))}
function ctespnAudioPruneHandled(){if(ctespnAudioHandledEvents.size<=CTESPN_AUDIO_HANDLED_LIMIT)return;const ordered=[...ctespnAudioHandledEvents.entries()].sort((a,b)=>Number(a[1]||0)-Number(b[1]||0));for(const [key] of ordered.slice(0,ordered.length-CTESPN_AUDIO_HANDLED_LIMIT))ctespnAudioHandledEvents.delete(key)}
function ctespnAudioPrunePrepared(){if(ctespnAudioPrepared.size<=CTESPN_AUDIO_PREPARED_LIMIT)return;const ordered=[...ctespnAudioPrepared.entries()].sort((a,b)=>Number(a[1]?.preparedAt||0)-Number(b[1]?.preparedAt||0));for(const [key] of ordered.slice(0,ordered.length-CTESPN_AUDIO_PREPARED_LIMIT))ctespnAudioPrepared.delete(key)}
function ctespnAudioStats(evt){return evt?.intervalAnalysis?.stats||{}}
function ctespnAudioVisualYards(evt){const st=ctespnAudioStats(evt),direct=Number(evt?.visualYards);if(Number.isFinite(direct)&&Math.abs(direct)>0)return Math.abs(direct);for(const key of ['rush_yd','rec_yd','pass_yd']){const v=Number(st?.[key]);if(Number.isFinite(v)&&Math.abs(v)>0)return Math.abs(v)}const m=String(evt?.detail||'').match(/(-?\d+(?:\.\d+)?)\s*(?:yard|yd)/i);return m?Math.abs(Number(m[1])):0}
function ctespnAudioIsDefense(evt,type=''){const pos=String(evt?.pos||playerInfo?.(evt?.playerId||evt?.player_id)?.pos||'').toUpperCase();return pos==='DEF'||pos==='DST'||String(type).startsWith('def_')}
function ctespnAudioBaseEventKey(evt){const type=String(evt?.playType||gvPlayType(evt)||'').toLowerCase(),detail=String(evt?.detail||'').toLowerCase(),banner=String(evt?.resultBanner||evt?.banner||'').toUpperCase(),st=ctespnAudioStats(evt),isDefense=ctespnAudioIsDefense(evt,type);if(banner.includes('PICK SIX')||type==='pick_six'||type==='def_int_td')return 'pick_six';if(banner.includes('SCOOP')||type==='fumble_return_td'||type==='def_fum_td')return 'scoop_score';if(banner.includes('KICK SIX')||['kick_return_td','punt_return_td','def_kick_ret_td','def_punt_ret_td'].includes(type))return 'kick_six';if(type==='touchdown'||detail.includes('touchdown')||Number(st.pass_td||0)>0||Number(st.rush_td||0)>0||Number(st.rec_td||0)>0)return 'touchdown';const interception=['interception','def_int','def_interception'].includes(type)||detail.includes('interception')||Number(st.pass_int||0)>0||Number(st.int||0)>0;if(interception)return isDefense||Number(st.int||0)>0?'defensive_interception':'qb_intercepted';const fumble=['fumble','def_fumble'].includes(type)||detail.includes('fumble')||Number(st.fum_lost||0)>0||Number(st.fum_rec||0)>0;if(fumble)return isDefense||Number(st.fum_rec||0)>0?'fumble_recovery':'your_player_fumbled';if(type==='def_sack'||detail.includes('sack')||Number(st.sack||0)>0)return 'sack';const yards=ctespnAudioVisualYards(evt);if(['rb_run','qb_run'].includes(type)&&yards>=CTESPN_AUDIO_LONG_RUSH_YARDS)return 'long_rush';if(['reception','qb_pass'].includes(type)&&yards>=CTESPN_AUDIO_LONG_RECEPTION_YARDS)return 'long_reception';return null}
function ctespnAudioLeadChangeContext(evt){if(evt?.audioTestLeadChange&&typeof evt.audioTestLeadChange==='object')return {qualifying:!!evt.audioTestLeadChange.qualifying,direction:evt.audioTestLeadChange.direction||'took_lead',source:'testing',maturity:{eligible:!!evt.audioTestLeadChange.qualifying}};try{const pair=chosenPair?.(),line=ctespnAlertScoreline?.(pair);if(!pair||!line)return {qualifying:false,reason:'no-selected-matchup'};const rid=String(evt?.rosterId??evt?.roster_id??''),aId=String(line.a?.roster_id??''),bId=String(line.b?.roster_id??'');if(!rid||(rid!==aId&&rid!==bId))return {qualifying:false,reason:'event-not-in-selected-matchup'};const delta=Number(evt?.pointDelta??evt?.delta??0);if(!Number.isFinite(delta)||Math.abs(delta)<.001)return {qualifying:false,reason:'no-fantasy-delta'};const beforeA=Number(line.aScore||0)-(rid===aId?delta:0),beforeB=Number(line.bScore||0)-(rid===bId?delta:0),beforeDiff=beforeA-beforeB,afterDiff=Number(line.aScore||0)-Number(line.bScore||0),raw=Math.sign(afterDiff)!==0&&Math.sign(beforeDiff)!==Math.sign(afterDiff),maturity=ctespnLeadChangeMaturity?.(line,beforeDiff,gameNow?.()||Date.now())||{eligible:false};return {qualifying:!!(raw&&maturity.eligible),raw,delta,beforeDiff,afterDiff,maturity,direction:delta<0?'lost_lead':'took_lead',source:'matchup-score'}}catch(e){return {qualifying:false,reason:'lead-change-context-error'}}}
function ctespnAudioTimingPlan(primaryKey,secondaryKey,totalDuration=0){const duration=Math.max(0,Number(totalDuration)||0),plan=[];if(primaryKey){const timing=CTESPN_AUDIO_CATALOG[primaryKey]?.timing||{milestone:'outcome',ratio:.82};plan.push({key:primaryKey,milestone:timing.milestone||'outcome',estimatedOffsetMs:duration?Math.round(duration*Math.max(0,Math.min(1,Number(timing.ratio??.82)))):0})}if(secondaryKey)plan.push({key:secondaryKey,milestone:'post_outcome',afterPrimary:true,gapMs:CTESPN_AUDIO_FOLLOWUP_GAP_MS,estimatedOffsetMs:duration+CTESPN_AUDIO_FOLLOWUP_GAP_MS});return plan}
function ctespnAudioResolveEvent(evt,totalDuration=0){const baseKey=ctespnAudioBaseEventKey(evt),leadChange=ctespnAudioLeadChangeContext(evt);let primaryKey=baseKey||null,secondaryKey=null;if(leadChange.qualifying)secondaryKey='late_lead_change';if(!primaryKey&&secondaryKey){primaryKey=secondaryKey;secondaryKey=null}const callCount=[primaryKey,secondaryKey].filter(Boolean).length,timingPlan=ctespnAudioTimingPlan(primaryKey,secondaryKey,totalDuration),r={eventId:ctespnAudioEventId(evt),baseKey,combinationKey:null,primaryKey,secondaryKey,leadChange,leadChangeConsumedByPrimary:false,automaticCallCount:callCount,candidates:[baseKey,leadChange.qualifying?'late_lead_change':null].filter(Boolean),timingPlan,totalDuration:Number(totalDuration)||0};evt.audioResolutionAudit={baseKey,combinationKey:null,primaryCall:primaryKey,secondaryCall:secondaryKey,leadChangeConsumedByPrimary:false,automaticCallCount:callCount,qualifyingLeadChange:!!leadChange.qualifying,timingPlan};return r}
function ctespnAudioPlayResolution(r){if(!r?.automaticCallCount)return false;const sequence=[];if(r.primaryKey)sequence.push({key:r.primaryKey});if(r.secondaryKey)sequence.push({key:r.secondaryKey,gapMs:CTESPN_AUDIO_FOLLOWUP_GAP_MS});const priority=Math.max(...sequence.map(x=>Number(CTESPN_AUDIO_CATALOG[x.key]?.priority||0)));return ctespnAudioQueueItem({sequence,priority,time:Date.now(),eventId:r.eventId})}
function ctespnAudioPrepareForGameViewEvent(evt,totalDuration=0){if(!evt)return null;const eventId=ctespnAudioEventId(evt);if(ctespnAudioHandledEvents.has(eventId)){evt.audioResolutionAudit={...(evt.audioResolutionAudit||{}),duplicateSuppressed:true,eventId};return null}const r=ctespnAudioResolveEvent(evt,totalDuration);ctespnAudioSetResolverStatus(r);if(!r.automaticCallCount)return r;ctespnAudioHandledEvents.set(eventId,Date.now());ctespnAudioPruneHandled();ctespnAudioPrepared.set(eventId,{resolution:r,preparedAt:Date.now(),fired:false});ctespnAudioPrunePrepared();return r}
function ctespnAudioGameViewMilestone(evt,milestone='outcome'){const eventId=ctespnAudioEventId(evt),prepared=ctespnAudioPrepared.get(eventId);if(!prepared||prepared.fired)return false;const required=prepared.resolution?.timingPlan?.[0]?.milestone||'outcome';if(milestone!==required&&!(required==='outcome'&&milestone==='result'))return false;prepared.fired=true;ctespnAudioPrepared.delete(eventId);return ctespnAudioPlayResolution(prepared.resolution)}
function ctespnAudioForGameViewEvent(evt){const r=ctespnAudioPrepareForGameViewEvent(evt,0);if(r?.automaticCallCount)ctespnAudioGameViewMilestone(evt,'outcome');return r}
function ctespnAudioEventKey(evt){return ctespnAudioResolveEvent(evt).primaryKey}
function ctespnAudioTestingScenario(name){const scenarios={touchdown_lead_change:{id:'audio-test-td-lc',playType:'touchdown',pos:'RB',detail:'Touchdown',pointDelta:6,audioTestLeadChange:{qualifying:true,direction:'took_lead'}},pick_six_lead_change:{id:'audio-test-ps-lc',playType:'def_int_td',pos:'DEF',detail:'Interception return touchdown',pointDelta:8,resultBanner:'PICK SIX',audioTestLeadChange:{qualifying:true,direction:'took_lead'}},sack_lead_change:{id:'audio-test-sack-lc',playType:'def_sack',pos:'DEF',detail:'Sack',pointDelta:1,audioTestLeadChange:{qualifying:true,direction:'took_lead'}},long_rush_lead_change:{id:'audio-test-rush-lc',playType:'rb_run',pos:'RB',detail:'31 yard rush',visualYards:31,pointDelta:3.1,audioTestLeadChange:{qualifying:true,direction:'took_lead'}},defensive_int_lead_change:{id:'audio-test-def-int-lc',playType:'def_int',pos:'DEF',detail:'Interception',pointDelta:2,intervalAnalysis:{stats:{int:1}},audioTestLeadChange:{qualifying:true,direction:'took_lead'}},offensive_int_lost_lead:{id:'audio-test-off-int-lc',playType:'qb_pass',pos:'QB',detail:'Interception thrown',pointDelta:-2,intervalAnalysis:{stats:{pass_int:1}},audioTestLeadChange:{qualifying:true,direction:'lost_lead'}},offensive_fumble:{id:'audio-test-off-fum',playType:'rb_rush_fumble',pos:'RB',detail:'Fumble lost',pointDelta:-2,intervalAnalysis:{stats:{fum_lost:1}}},defensive_fumble:{id:'audio-test-def-fum',playType:'def_fumble',pos:'DEF',detail:'Fumble recovery',pointDelta:2,intervalAnalysis:{stats:{fum_rec:1}}}};const evt=scenarios[name];if(!evt)return null;const r=ctespnAudioResolveEvent({...evt},5000);ctespnAudioSetResolverStatus(r);if(ctespnAudioState.enabled)ctespnAudioPlayResolution(r);return r}
function ctespnAudioSyncUi(){const s=ctespnAudioState,pairs=[['ctespnAudioEnabled','checked',!!s.enabled],['ctespnAudioMaster','value',Math.round(s.master*100)],['ctespnAudioAnnouncer','value',Math.round(s.announcer*100)],['ctespnAudioStadium','value',Math.round(s.stadium*100)],['ctespnAudioStingers','value',Math.round(s.stingers*100)]];for(const [id,prop,val] of pairs){const el=document.getElementById(id);if(el)el[prop]=val}const mute=document.getElementById('ctespnAudioMute');if(mute)mute.textContent=s.muted?'Unmute':'Mute';ctespnAudioSetStatus(!s.enabled?'Audio disabled.':ctespnAudioUnlocked?'Audio ready for installed clips.':'Audio enabled — interact with the page to unlock.','')}
function ctespnAudioBindUi(){ctespnAudioLoadState();ctespnAudioSyncUi();const enabled=document.getElementById('ctespnAudioEnabled');if(enabled)enabled.onchange=e=>{ctespnAudioState.enabled=!!e.target.checked;ctespnAudioSaveState();ctespnAudioSyncUi();if(ctespnAudioState.enabled)ctespnAudioUnlock()};const volumeMap={ctespnAudioMaster:'master',ctespnAudioAnnouncer:'announcer',ctespnAudioStadium:'stadium',ctespnAudioStingers:'stingers'};for(const [id,key] of Object.entries(volumeMap)){const el=document.getElementById(id);if(el)el.oninput=e=>{ctespnAudioState[key]=Math.max(0,Math.min(1,Number(e.target.value)/100));ctespnAudioSaveState()}}const mute=document.getElementById('ctespnAudioMute');if(mute)mute.onclick=()=>{ctespnAudioState.muted=!ctespnAudioState.muted;if(ctespnAudioState.muted)ctespnAudioStopBelow(Infinity);ctespnAudioSaveState();ctespnAudioSyncUi()};document.querySelectorAll('[data-audio-test]').forEach(btn=>btn.addEventListener('click',()=>{ctespnAudioUnlock();const idx=Number(btn.dataset.audioVariant);ctespnAudioPlayEvent(btn.dataset.audioTest,{priority:999,variantIndex:Number.isFinite(idx)?idx:null});ctespnAudioSetResolverStatus({primaryKey:btn.dataset.audioTest,secondaryKey:null,leadChange:{qualifying:false},automaticCallCount:1,timingPlan:[{milestone:'manual'}]})}));document.querySelectorAll('[data-audio-resolve-test]').forEach(btn=>btn.addEventListener('click',()=>{ctespnAudioUnlock();ctespnAudioTestingScenario(btn.dataset.audioResolveTest)}))}
window.addEventListener('pointerdown',ctespnAudioUnlock,{once:true,capture:true});
window.addEventListener('keydown',ctespnAudioUnlock,{once:true,capture:true});
window.addEventListener('DOMContentLoaded',ctespnAudioBindUi,{once:true});

