export const APP_VERSION = "1.0.2";
export const RELEASE_NAME = "Stable Release";

export const DIFFICULTY_CONFIG = {
  novice: {
    label: "Novice",
    wordMin: 3,
    wordMax: 5,
    spawnInterval: 2600,
    movementSpeed: 0.72,
    errorTolerance: 5,
    rhythmTolerance: 0.52,
    numericLength: 4,
    timerFactor: 1.35,
    opponentPace: 0.55
  },
  easy: {
    label: "Easy",
    wordMin: 3,
    wordMax: 6,
    spawnInterval: 2250,
    movementSpeed: 0.86,
    errorTolerance: 4,
    rhythmTolerance: 0.43,
    numericLength: 4,
    timerFactor: 1.18,
    opponentPace: 0.68
  },
  normal: {
    label: "Normal",
    wordMin: 4,
    wordMax: 7,
    spawnInterval: 1950,
    movementSpeed: 1,
    errorTolerance: 3,
    rhythmTolerance: 0.34,
    numericLength: 5,
    timerFactor: 1,
    opponentPace: 0.78
  },
  challenging: {
    label: "Challenging",
    wordMin: 5,
    wordMax: 9,
    spawnInterval: 1650,
    movementSpeed: 1.17,
    errorTolerance: 2,
    rhythmTolerance: 0.27,
    numericLength: 5,
    timerFactor: 0.88,
    opponentPace: 0.9
  },
  hard: {
    label: "Hard",
    wordMin: 6,
    wordMax: 11,
    spawnInterval: 1380,
    movementSpeed: 1.36,
    errorTolerance: 1,
    rhythmTolerance: 0.21,
    numericLength: 6,
    timerFactor: 0.78,
    opponentPace: 1.02
  },
  expert: {
    label: "Expert",
    wordMin: 7,
    wordMax: 13,
    spawnInterval: 1100,
    movementSpeed: 1.58,
    errorTolerance: 0,
    rhythmTolerance: 0.16,
    numericLength: 6,
    timerFactor: 0.68,
    opponentPace: 1.18
  }
};

export const WORD_LISTS = {
  general: [
    "apple", "bridge", "camera", "distant", "engine", "forest", "garden", "harbor",
    "island", "jacket", "kettle", "lantern", "market", "notebook", "orange", "planet",
    "quiet", "river", "silver", "travel", "umbrella", "valley", "window", "yellow",
    "anchor", "breeze", "circle", "dragon", "energy", "fabric", "glimmer", "hammer",
    "inside", "journey", "kitten", "legend", "meadow", "number", "ocean", "puzzle",
    "rocket", "station", "timber", "violet", "wander", "zephyr", "balance", "cabinet",
    "delight", "emerald", "frequent", "gravity", "horizon", "imagine", "jovial", "kingdom",
    "machine", "natural", "observe", "picture", "quality", "rapid", "shelter", "texture",
    "utility", "venture", "weather", "absent", "active", "admire", "adventure", "airport",
    "almond", "answer", "apron", "artist", "autumn", "basket", "beacon", "beauty",
    "bicycle", "blanket", "blossom", "bottle", "branch", "bright", "brother", "bubble",
    "candle", "carpet", "castle", "cheerful", "cherry", "citizen", "cloudy", "coffee",
    "color", "compass", "corner", "cotton", "country", "crystal", "curious", "desert",
    "dinner", "discover", "dolphin", "doorway", "drawing", "dream", "early", "evening",
    "feather", "festival", "field", "flower", "friendly", "frozen", "gentle", "giant",
    "golden", "highway", "holiday", "honey", "hotel", "humble", "idea", "invite",
    "kitchen", "ladder", "language", "laughter", "library", "little", "lucky", "marble",
    "memory", "morning", "mountain", "music", "narrow", "nearby", "orchard", "paper",
    "parade", "pebble", "people", "pepper", "picnic", "pillow", "pocket", "pretty",
    "rabbit", "rainbow", "ready", "rescue", "ribbon", "saddle", "shadow", "simple",
    "sister", "smooth", "sparkle", "spring", "square", "summer", "sunset", "table",
    "thunder", "ticket", "tomorrow", "tower", "treasure", "tunnel", "village", "winter",
    "wonder", "wooden", "animal", "around", "basic", "beach", "button", "canyon",
    "clever", "coast", "cookie", "copper", "dance", "eager", "family", "farmer",
    "guitar", "happy", "honest", "horse", "lemon", "magic", "mirror", "moment",
    "museum", "noodle", "open", "paint", "parent", "pencil", "radio", "sailor",
    "school", "secret", "shape", "smile", "snow", "story", "street", "sunny",
    "train", "velvet", "water", "weekend", "whisper", "world", "zebra", "amazing",
    "balcony", "battery", "chimney", "diamond", "freedom", "hallway", "nature", "package",
    "sunrise", "teacher",
    "acorn", "afternoon", "airplane", "ancient", "bakery", "center", "cloud", "eagle",
    "graceful", "grape", "green", "house", "ivory", "jelly", "joyful", "jungle",
    "maple", "nest", "olive", "peach", "robin", "round", "sail", "season",
    "star", "sweet", "tiny", "tulip", "turtle", "warm", "waterfall", "young",
    "zipper", "comet", "creek", "dawn", "echo", "ember", "fern", "frost",
    "galaxy", "grove", "hill", "lagoon", "lake", "moon", "moss", "pine",
    "pond", "rain", "reef", "ridge", "rock", "sand", "shore", "sky",
    "stone", "storm", "sun", "trail", "wave", "woods", "amber", "coral",
    "pearl", "ruby", "sapphire", "bronze", "prairie", "cabin", "cottage", "sidewalk",
    "pathway", "triangle", "wagon", "purple",
    "abundant", "achieve", "across", "actual", "adore", "almost", "already", "always",
    "among", "arrive", "awake", "become", "before", "beside", "better", "beyond",
    "bird", "blue", "board", "brave", "breakfast", "broad", "brown", "build",
    "busy", "calm", "carry", "catch", "choose", "clean", "climb", "close",
    "comfortable", "complete", "cool", "create", "deep", "different", "easy", "enjoy",
    "enough", "every", "famous", "far", "fast", "favorite", "fine", "fire",
    "fresh", "fun", "game", "gift", "good", "grand", "grow", "help",
    "hope", "important", "kind", "light", "live", "lovely", "move", "new",
    "nice", "perfect", "place", "play", "quick", "rest", "safe", "soft",
    "special", "strong", "surprise", "together", "true", "useful", "visit", "welcome",
    "wide",
  ],
  office: [
    "agenda", "budget", "calendar", "deadline", "email", "folder", "invoice", "meeting",
    "memo", "printer", "project", "receipt", "report", "schedule", "spreadsheet", "vendor",
    "archive", "contract", "document", "manager", "monitor", "policy", "purchase", "review",
    "signature", "timesheet", "workflow", "analysis", "briefing", "approval", "conference", "department",
    "forecast", "inventory", "keyboard", "minutes", "proposal", "quarterly", "reconcile", "supervisor",
    "template", "training", "workstation", "attachment", "coordination", "deliverable", "documentation", "procurement",
    "administrative", "account", "accounting", "action", "amendment", "appointment", "audit", "authorization",
    "billing", "binder", "board", "cabinet", "calculation", "call", "center", "case",
    "checklist", "client", "collaboration", "communication", "compliance", "confirmation", "consultant", "contact",
    "correspondence", "decision", "delivery", "desk", "directory", "discussion", "division", "draft",
    "duties", "employee", "enrollment", "equipment", "estimate", "evaluation", "executive", "extension",
    "facilities", "filing", "finance", "fiscal", "form", "framework", "funding", "hardware",
    "implementation", "inbox", "information", "intake", "itemization", "laptop", "letter", "management",
    "memorandum", "milestone", "office", "operations", "order", "organization", "payment", "payroll",
    "performance", "planning", "presentation", "procedure", "process", "profile", "program", "purchasing",
    "record", "request", "resolution", "routing", "scanner", "secretary", "service", "software",
    "staff", "statement", "status", "submission", "summary", "support", "task", "team",
    "telephone", "timeline", "tracking", "transaction", "update", "validation", "verification", "workload",
    "workspace", "attendance", "backlog", "benefit", "category", "certification", "change", "charge",
    "classification", "coding", "committee", "comparison", "completion", "condition", "configuration", "consent",
    "coordinator", "copy", "credential", "customer", "database", "delegation", "development", "distribution",
    "expenditure", "function", "guideline", "handoff", "header", "helpdesk", "incident", "issue",
    "liaison", "logistics", "maintenance", "manual", "measure", "migration", "monitoring", "notice",
    "objective", "onboarding", "packet", "personnel", "queue", "referral", "register", "requirement",
    "resource", "response", "scope", "security", "system", "worksheet", "accommodation", "administration",
    "allocation", "announcement", "assessment", "assignment", "dashboard", "operation", "reporting",
    "analyst", "business", "candidate", "closure", "director", "exhibit", "expense", "handbook",
    "hiring", "instruction", "interview", "recruitment", "reference", "supply", "voucher", "reimbursement",
    "reconciliation", "consultation", "negotiation", "notification", "processing", "recommendation", "registration", "renewal",
    "specification", "standardization", "orientation", "participation", "priority", "production", "research", "retention",
    "claim", "encumbrance", "appropriation", "requisition", "fiscal-year", "workpaper", "remittance", "receivable",
    "payable", "ledger", "journal", "capitalization", "accrual", "depreciation", "budgetary", "solicitation",
    "bidder", "procurement-card", "purchase-order", "deliverables", "acceptance", "termination", "indemnification", "insurance",
    "appendix", "schedule-b", "transmittal", "routing-slip", "signature-block", "records-retention", "public-records", "confidentiality",
    "governance", "stakeholder", "meeting-notes", "action-item", "due-date", "follow-up", "metrics",
    "agenda-item", "agenda-packet", "annual-report", "applicant", "benefits", "board-item", "budget-line", "budget-cycle",
    "business-process", "case-file", "charge-code", "client-file", "closeout", "cost-center", "crosswalk", "data-entry",
    "decision-memo", "department-head", "desk-phone", "document-control", "effective-date", "electronic-signature", "employee-file", "end-user",
    "escalation", "executive-summary", "expenditure-code", "fiscal-report", "funding-source", "internal-control", "job-aid", "legal-review",
    "mailroom", "monthly-report", "network-drive", "office-supply", "operating-procedure", "payment-authorization", "performance-measure", "personnel-file",
    "position-control", "program-manager", "project-plan", "purchasing-agent", "quality-assurance", "request-form", "risk-assessment", "service-desk",
    "shared-drive", "sign-off", "source-document", "staff-report", "status-report", "subject-line", "supporting-document", "system-access",
    "technical-review", "tracking-log", "user-account", "vendor-file", "work-order", "year-end", "carryforward", "cost-allocation",
    "fund-center", "general-ledger", "journal-entry", "purchase-requisition", "service-request", "contract-term", "contract-manager", "invoice-date",
    "invoice-number", "payment-date", "payment-status", "approval-date", "approval-route", "routing-number", "reference-number", "tracking-number",
    "records-request", "retention-period",
  ],
  technical: [
    "binary", "buffer", "cache", "client", "compile", "console", "database", "debug",
    "deploy", "domain", "endpoint", "ethernet", "firewall", "gateway", "hardware", "interface",
    "latency", "module", "network", "packet", "protocol", "runtime", "script", "server",
    "socket", "storage", "syntax", "terminal", "thread", "variable", "algorithm", "bandwidth",
    "container", "dependency", "encryption", "framework", "javascript", "middleware", "repository", "responsive",
    "stylesheet", "virtualization", "adapter", "address", "api", "archive", "array", "async",
    "authentication", "backend", "backup", "batch", "browser", "byte", "callback", "certificate",
    "checksum", "class", "cloud", "cluster", "command", "compiler", "component", "compute",
    "configuration", "connection", "connector", "constant", "cookie", "core", "cpu", "credential",
    "daemon", "data", "datatype", "deployment", "device", "directory", "dns", "driver",
    "encoding", "environment", "error", "event", "exception", "expression", "extension", "firmware",
    "function", "git", "handler", "hashing", "host", "hostname", "http", "https",
    "index", "input", "instance", "integration", "interpreter", "ip", "kernel", "library",
    "listener", "load", "localhost", "logging", "loop", "memory", "method", "node",
    "object", "package", "parameter", "parser", "patch", "payload", "permission", "plugin",
    "port", "process", "processor", "promise", "property", "proxy", "query", "queue",
    "recursion", "registry", "release", "render", "request", "response", "route", "router",
    "schema", "security", "session", "shell", "signal", "source", "stack", "stream",
    "string", "subnet", "sync", "system", "tcp", "token", "tool", "transaction",
    "udp", "ui", "version", "virtual", "websocket", "workflow", "xml", "automation",
    "branch", "build", "cli", "code", "engine",
    "analytics", "architecture", "chipset", "codec", "compression", "cybersecurity", "dashboard", "decoder",
    "disk", "hash", "internet", "linux", "load-balancer", "log", "machine", "platform",
    "ram", "software", "ssh", "traffic", "url", "usb", "vpn", "web",
    "wifi", "json", "yaml", "hypervisor", "orchestration", "telemetry", "observability", "microservice",
    "pipeline", "artifact", "commit", "merge", "pull-request", "containerization", "kubernetes", "docker",
    "service", "worker", "cache-control", "certificate-authority", "cryptography", "cipher", "database-index", "rollback",
    "replication", "sharding", "failover", "redundancy", "throughput", "benchmark", "performance", "profiling",
    "iteration", "argument", "return-value", "exception-handler", "asynchronous", "event-loop", "garbage-collection", "memory-leak",
    "race-condition", "deadlock", "mutex", "semaphore", "filesystem", "permission-group", "access-control", "identity-provider",
    "single-sign-on", "multi-factor", "key-exchange", "public-key", "private-key", "session-token", "header", "request-body",
    "response-code", "load-testing", "unit-test", "integration-test", "regression-test", "deployment-pipeline", "version-control", "code-review",
    "source-map", "minification", "transpilation", "breakpoint", "viewport", "accessibility", "semantic", "markup",
    "rendering", "browser-engine", "network-stack", "routing-table", "dns-record", "ip-address", "subnet-mask", "gateway-address",
    "packet-loss", "jitter", "uptime", "downtime", "monitoring", "alerting", "diagnostics", "troubleshooting",
    "recovery", "snapshot", "restore", "firmware-update", "device-driver", "operating-system", "command-line", "scriptable",
    "api-gateway", "application-server", "batch-process", "cache-hit", "cache-miss", "codebase", "data-model", "database-schema",
    "endpoint-route", "error-code", "feature-flag", "file-format", "handshake", "health-check", "host-machine", "http-request",
    "http-response", "input-validation", "load-time", "network-interface", "object-model", "packet-capture", "process-id", "query-string",
    "request-header", "response-header", "root-directory", "runtime-error", "service-account", "source-code", "system-call", "test-suite",
    "thread-pool", "time-out", "user-interface", "virtual-machine", "web-server", "web-service", "wireless-network", "zero-downtime",
    "rollback-plan", "recovery-point", "recovery-time", "access-token", "bearer-token", "configuration-file", "environment-variable", "secret-key",
    "log-file", "stack-trace",
  ]
};


// Additional vocabulary pass: deliberately broad to reduce repetition during long sessions.
const WORD_LIST_EXPANSION_2 = {
  "general": [
    "acorn",
    "adventure",
    "airplane",
    "alley",
    "amber",
    "antique",
    "arrow",
    "autumn",
    "avenue",
    "badge",
    "bakery",
    "bamboo",
    "banner",
    "barrel",
    "basin",
    "bayberry",
    "bedtime",
    "berry",
    "biscuit",
    "breeze",
    "brook",
    "canyon",
    "carnival",
    "cedar",
    "cellar",
    "cereal",
    "chapel",
    "cheerful",
    "circle",
    "circus",
    "clover",
    "comet",
    "cottage",
    "creek",
    "cushion",
    "daisy",
    "daylight",
    "deck",
    "dolphin",
    "doorway",
    "downtown",
    "drift",
    "dune",
    "eagle",
    "earth",
    "echo",
    "elm",
    "feather",
    "ferry",
    "fireplace",
    "fountain",
    "foxglove",
    "garage",
    "ginger",
    "glacier",
    "hammock",
    "hillside",
    "iceberg",
    "jewel",
    "kayak",
    "lagoon",
    "lighthouse",
    "lilac",
    "maple",
    "marsh",
    "melody",
    "midnight",
    "moonlight",
    "mosaic",
    "napkin",
    "orchard",
    "paddle",
    "palace",
    "pasture",
    "pebble",
    "pinecone",
    "playground",
    "pond",
    "porch",
    "prairie",
    "pumpkin",
    "raccoon",
    "rainfall",
    "roadside",
    "rooftop",
    "rowboat",
    "sandbox",
    "seashell",
    "shoreline",
    "skillet",
    "snowfall",
    "sparrow",
    "staircase",
    "starlight",
    "strawberry",
    "suitcase",
    "sunflower",
    "teacup",
    "thunderstorm",
    "toolbox",
    "trail",
    "treetop",
    "tulip",
    "waterfall",
    "wheelbarrow",
    "wilderness",
    "windmill",
    "woodland",
    "workshop"
  ],
  "office": [
    "accrual",
    "adjustment",
    "analyst",
    "appendix",
    "applicant",
    "appointment",
    "authorization",
    "benchmark",
    "calendarization",
    "capitalization",
    "caseload",
    "clarification",
    "collaboration",
    "collection",
    "commissioner",
    "correspondence",
    "costcenter",
    "dashboard",
    "delegation",
    "designation",
    "discrepancy",
    "disposition",
    "distribution",
    "docket",
    "escalation",
    "evaluation",
    "exception",
    "executive",
    "expenditure",
    "facilitator",
    "filing",
    "forecast",
    "governance",
    "implementation",
    "indicator",
    "intake",
    "ledger",
    "mailbox",
    "methodology",
    "onboarding",
    "ordinance",
    "orientation",
    "outreach",
    "portfolio",
    "prioritization",
    "requisition",
    "retention",
    "routing",
    "stakeholder",
    "submission",
    "submittal",
    "tabulation",
    "teleconference",
    "tracking",
    "variance",
    "allocation",
    "appropriation",
    "attestation",
    "beneficiary",
    "certification",
    "chronology",
    "circulation",
    "concurrence",
    "deliverables",
    "designation",
    "encumbrance",
    "engagement",
    "facilitator",
    "governance",
    "hierarchy",
    "implementation",
    "indicator",
    "justification",
    "liability",
    "memorandum",
    "notification",
    "obligation",
    "procurement",
    "reconciliation",
    "reimbursement",
    "solicitation",
    "specification",
    "stewardship",
    "utilization",
    "validation",
    "voucher",
    "workload",
    "amendment",
    "authorization",
    "clearance",
    "consultation",
    "continuation",
    "correction",
    "coverage",
    "custodian",
    "determination",
    "directive",
    "disclosure",
    "eligibility",
    "escalation",
    "exhibit",
    "expenditure",
    "fiscalyear",
    "grantor",
    "handbook",
    "implementation",
    "inventory",
    "justification",
    "limitation",
    "methodology",
    "obligation",
    "ordinance",
    "participation",
    "performance",
    "procurement",
    "reconciliation",
    "reimbursement",
    "renewal",
    "representation",
    "requirement",
    "retention",
    "revision",
    "solicitation",
    "statement",
    "stipulation",
    "subrecipient",
    "verification"
  ],
  "technical": [
    "accessibility",
    "actuator",
    "analytics",
    "architecture",
    "artifact",
    "assembly",
    "breakpoint",
    "broker",
    "caching",
    "cipher",
    "chipset",
    "codec",
    "concurrency",
    "controller",
    "cryptography",
    "daemon",
    "datastore",
    "decryption",
    "emulator",
    "filesystem",
    "gateway",
    "hashing",
    "heap",
    "hypervisor",
    "identifier",
    "indexing",
    "inheritance",
    "instruction",
    "iterator",
    "json",
    "lifecycle",
    "microservice",
    "namespace",
    "observability",
    "orchestration",
    "pipeline",
    "pointer",
    "polling",
    "polymorphism",
    "provisioning",
    "serialization",
    "telemetry",
    "throughput",
    "topology",
    "validation",
    "webhook",
    "abstraction",
    "allocator",
    "bootstrap",
    "compression",
    "coroutine",
    "decoder",
    "dispatcher",
    "encapsulation",
    "executor",
    "frontend",
    "garbagecollector",
    "handshake",
    "immutable",
    "injection",
    "instrumentation",
    "invocation",
    "iterator",
    "manifest",
    "marshalling",
    "mutation",
    "normalization",
    "opcode",
    "pagination",
    "partition",
    "persistence",
    "pipeline",
    "prerequisite",
    "queueing",
    "replication",
    "resolver",
    "sandbox",
    "scheduler",
    "semaphore",
    "serialization",
    "snapshot",
    "telemetry",
    "timeout",
    "tracing",
    "transpiler",
    "tunneling",
    "upstream",
    "websocket",
    "abstraction",
    "assertion",
    "atomicity",
    "benchmark",
    "binarytree",
    "bitmask",
    "bootloader",
    "breakpoint",
    "circuitbreaker",
    "concurrency",
    "deadlock",
    "deserialization",
    "distributed",
    "emulator",
    "encapsulation",
    "federation",
    "garbagecollection",
    "handshake",
    "idempotency",
    "inheritance",
    "instrumentation",
    "interoperability",
    "loadbalancer",
    "memoization",
    "multithreading",
    "normalization",
    "observability",
    "orchestration",
    "parallelism",
    "partitioning",
    "persistence",
    "polymorphism",
    "provisioning",
    "recursion",
    "redundancy",
    "scalability",
    "serialization",
    "throttling",
    "transactionality",
    "validation"
  ]
};

Object.entries(WORD_LIST_EXPANSION_2).forEach(([listName, additions]) => {
  const existing = new Set(WORD_LISTS[listName]);
  additions.forEach(word => {
    const normalized = word.toLowerCase();
    if (!existing.has(normalized)) {
      WORD_LISTS[listName].push(normalized);
      existing.add(normalized);
    }
  });
});


// v0.17.8.1 word-bank expansion: extra long-session variety across all vocabulary families.
const WORD_LIST_EXPANSION_3 = {
  "general": [
    "acacia",
    "alder",
    "alpine",
    "anemone",
    "apricot",
    "aquarium",
    "archipelago",
    "armchair",
    "asparagus",
    "asteroid",
    "backpack",
    "badger",
    "barnyard",
    "beehive",
    "blackberry",
    "boardwalk",
    "bonfire",
    "brookside",
    "butterfly",
    "cactus",
    "campsite",
    "cardinal",
    "carousel",
    "cattail",
    "cinnamon",
    "coastline",
    "constellation",
    "courtyard",
    "daffodil",
    "dandelion",
    "evergreen",
    "firefly",
    "footbridge",
    "gazebo",
    "gemstone",
    "goldfish",
    "grapefruit",
    "grassland",
    "greenhouse",
    "hazelnut",
    "hedgehog",
    "hummingbird",
    "jasmine",
    "lavender",
    "lemonade",
    "magnolia",
    "marshmallow",
    "meadowlark",
    "meteor",
    "morningstar",
    "mushroom",
    "nectarine",
    "nightfall",
    "oakwood",
    "oatmeal",
    "oceanfront",
    "opal",
    "otter",
    "pancake",
    "panorama",
    "papaya",
    "parrot",
    "peppermint",
    "pinewood",
    "popcorn",
    "postcard",
    "raindrop",
    "redwood",
    "riverbank",
    "rosemary",
    "sailboat",
    "sandstone",
    "seagull",
    "seaspray",
    "seedling",
    "skylight",
    "snowflake",
    "songbird",
    "starfish",
    "sunbeam",
    "sunshine",
    "tangerine",
    "terrapin",
    "thundercloud",
    "treehouse",
    "twilight",
    "vineyard",
    "walnut",
    "waterside",
    "wildflower",
    "willow",
    "windchime",
    "wishbone",
    "blueberry",
    "butterscotch",
    "cantaloupe",
    "chestnut",
    "cranberry",
    "dragonfly",
    "elderberry",
    "flamingo",
    "gardenia",
    "honeybee",
    "ladybug",
    "milkshake",
    "moonbeam",
    "nightingale",
    "raspberry",
    "seasick",
    "terrace"
  ],
  "office": [
    "adjudication",
    "administrator",
    "agenda-log",
    "annualization",
    "apportionment",
    "authorization-log",
    "balance-sheet",
    "briefing-note",
    "budget-book",
    "business-unit",
    "calendar-entry",
    "cancellation",
    "certificate-holder",
    "clarification-log",
    "closing-date",
    "compliance-review",
    "confirmation-number",
    "contract-file",
    "cost-analysis",
    "cost-estimate",
    "cost-proposal",
    "cost-report",
    "coverage-period",
    "customer-record",
    "data-request",
    "decision-record",
    "delegation-log",
    "department-code",
    "disposition-log",
    "document-index",
    "document-register",
    "due-diligence",
    "email-thread",
    "engagement-letter",
    "exception-log",
    "expense-report",
    "file-index",
    "filing-date",
    "followup-log",
    "funding-agreement",
    "funding-cycle",
    "grant-agreement",
    "grant-application",
    "invoice-register",
    "issue-log",
    "line-item",
    "mailing-list",
    "meeting-agenda",
    "meeting-record",
    "office-hours",
    "operating-budget",
    "payment-register",
    "payment-request",
    "personnel-action",
    "policy-review",
    "position-number",
    "program-budget",
    "program-review",
    "project-status",
    "proposal-review",
    "purchasing-file",
    "quarterly-report",
    "receipt-log",
    "reconciliation-log",
    "reference-file",
    "renewal-date",
    "reporting-cycle",
    "request-log",
    "response-date",
    "review-cycle",
    "routing-sheet",
    "service-level",
    "signature-date",
    "staff-assignment",
    "staff-directory",
    "standard-operating",
    "status-update",
    "submission-date",
    "supporting-record",
    "task-list",
    "team-lead",
    "telework-agreement",
    "timekeeping",
    "transaction-log",
    "travel-claim",
    "vendor-account",
    "vendor-contract",
    "vendor-invoice",
    "work-queue",
    "work-schedule",
    "audit-trail",
    "budget-amendment",
    "budget-transfer",
    "contract-amendment",
    "contract-review",
    "fiscal-close",
    "funding-request",
    "invoice-review",
    "payment-processing",
    "procurement-file",
    "project-closeout",
    "records-management",
    "risk-register",
    "service-level-agreement",
    "staffing-plan",
    "vendor-management",
    "workflow-step",
    "allocation-plan",
    "approval-log",
    "compliance-log",
    "contract-log",
    "correspondence-log",
    "expenditure-report",
    "management-review",
    "performance-report",
    "procurement-log",
    "project-tracker",
    "record-index",
    "reimbursement-request",
    "retention-schedule"
  ],
  "technical": [
    "accessibility-tree",
    "api-client",
    "api-endpoint",
    "application-layer",
    "audit-log",
    "auth-token",
    "autoscaling",
    "availability-zone",
    "backend-service",
    "binary-search",
    "build-artifact",
    "build-cache",
    "build-system",
    "cache-layer",
    "code-coverage",
    "code-path",
    "command-shell",
    "compile-time",
    "compute-node",
    "connection-pool",
    "data-pipeline",
    "data-store",
    "debug-symbol",
    "dependency-graph",
    "deployment-target",
    "device-state",
    "directory-service",
    "disk-cache",
    "distributed-cache",
    "dns-cache",
    "edge-node",
    "encryption-key",
    "event-handler",
    "exception-log",
    "execution-context",
    "feature-branch",
    "frontend-build",
    "function-call",
    "garbage-collector",
    "gateway-route",
    "health-monitor",
    "heap-memory",
    "host-process",
    "input-buffer",
    "interface-layer",
    "ip-packet",
    "job-queue",
    "kernel-module",
    "latency-budget",
    "log-level",
    "memory-cache",
    "message-broker",
    "network-latency",
    "network-route",
    "object-store",
    "output-buffer",
    "package-manager",
    "packet-filter",
    "parse-tree",
    "process-memory",
    "protocol-stack",
    "proxy-server",
    "query-plan",
    "request-queue",
    "resource-pool",
    "response-time",
    "runtime-library",
    "security-policy",
    "serialization-format",
    "service-mesh",
    "session-cache",
    "shell-script",
    "source-tree",
    "storage-volume",
    "system-service",
    "task-runner",
    "tcp-connection",
    "thread-safe",
    "token-store",
    "traffic-shaping",
    "transport-layer",
    "ui-component",
    "unit-testing",
    "user-session",
    "version-tag",
    "virtual-network",
    "web-client",
    "web-endpoint",
    "web-runtime",
    "worker-thread",
    "zero-trust",
    "api-version",
    "application-log",
    "cache-entry",
    "certificate-chain",
    "configuration-value",
    "data-structure",
    "database-connection",
    "deployment-job",
    "error-handler",
    "event-stream",
    "file-system",
    "host-address",
    "identity-service",
    "load-generator",
    "memory-allocation",
    "network-adapter",
    "process-table",
    "request-context",
    "response-body",
    "routing-policy",
    "runtime-process",
    "service-worker",
    "source-control",
    "system-log",
    "test-runner",
    "web-application",
    "branch-protection",
    "continuous-integration",
    "continuous-delivery",
    "container-runtime",
    "dependency-lock",
    "environment-config",
    "infrastructure-code",
    "merge-request",
    "network-policy",
    "package-lock",
    "release-branch",
    "repository-cache",
    "secret-store",
    "static-analysis",
    "type-checker",
    "vulnerability-scan"
  ]
};

Object.entries(WORD_LIST_EXPANSION_3).forEach(([listName, additions]) => {
  const existing = new Set(WORD_LISTS[listName]);
  additions.forEach(word => {
    const normalized = word.toLowerCase();
    if (!existing.has(normalized)) {
      WORD_LISTS[listName].push(normalized);
      existing.add(normalized);
    }
  });
});


// v0.17.6 supplemental short/plain-token pass to keep every difficulty and drill family well supplied.
const WORD_LIST_EXPANSION_4 = {
  "office": [
    "aid",
    "aide",
    "bid",
    "bids",
    "book",
    "books",
    "brief",
    "briefs",
    "clerk",
    "code",
    "codes",
    "copies",
    "cost",
    "costs",
    "date",
    "dates",
    "desks",
    "fax",
    "file",
    "files",
    "forms",
    "grant",
    "grants",
    "hire",
    "hires",
    "item",
    "items",
    "mail",
    "note",
    "notes",
    "paid",
    "pay",
    "plan",
    "plans",
    "rate",
    "rates",
    "rule",
    "rules",
    "tax",
    "taxes",
    "time",
    "times",
    "total",
    "totals",
    "audits",
    "claims",
    "clients",
    "drafts",
    "emails",
    "funds",
    "memos",
    "orders",
    "records",
    "route",
    "routes",
    "tasks",
    "vendors",
    "budgets"
  ],
  "technical": [
    "app",
    "apps",
    "bit",
    "bits",
    "bus",
    "buses",
    "bytes",
    "caches",
    "chip",
    "chips",
    "clouds",
    "codes",
    "cores",
    "disks",
    "drivers",
    "file",
    "files",
    "hashes",
    "hosts",
    "inputs",
    "kernels",
    "link",
    "links",
    "loads",
    "logs",
    "nodes",
    "ports",
    "routes",
    "scripts",
    "servers",
    "shells",
    "stacks",
    "tokens",
    "tools"
  ]
};
Object.entries(WORD_LIST_EXPANSION_4).forEach(([listName, additions]) => {
  const existing = new Set(WORD_LISTS[listName]);
  additions.forEach(word => {
    const normalized = word.toLowerCase();
    if (!existing.has(normalized)) { WORD_LISTS[listName].push(normalized); existing.add(normalized); }
  });
});


// v0.17.6 technical plain-token balance pass.
const WORD_LIST_EXPANSION_5 = { technical: [
  "accelerator",
  "antenna",
  "appliance",
  "assembler",
  "battery",
  "bios",
  "bridge",
  "busbar",
  "capacitor",
  "circuit",
  "clock",
  "datapath",
  "desktop",
  "diagnostic",
  "diode",
  "display",
  "fiber",
  "graphics",
  "interrupt",
  "keyboard",
  "laptop",
  "modem",
  "motherboard",
  "peripheral",
  "pixel",
  "printer",
  "radio",
  "receiver",
  "register",
  "resistor",
  "sensor",
  "serial",
  "silicon",
  "switch",
  "transistor",
  "wireless",
  "workstation",
  "accesscontrol",
  "identityprovider",
  "multifactor",
  "keyexchange",
  "sourcecode",
  "appserver",
  "datamodel",
  "errorcode",
  "healthcheck",
  "networkinterface",
  "objectmodel",
  "processid",
  "serviceaccount",
  "systemcall",
  "testsuite",
  "threadpool",
  "userinterface",
  "virtualmachine",
  "webserver",
  "webservice"
] };
{{ const existing = new Set(WORD_LISTS.technical); WORD_LIST_EXPANSION_5.technical.forEach(word => { const normalized=word.toLowerCase(); if (!existing.has(normalized)) { WORD_LISTS.technical.push(normalized); existing.add(normalized); } }); }}



// v0.17.6 final practical vocabulary expansion.
// This pass favors common typing, office, and computing terms over obscure filler.
const WORD_LIST_EXPANSION_6 = {
  general: [
    "above", "accept", "account", "adapt", "adult", "after", "again", "against",
    "ahead", "alarm", "alive", "allow", "alone", "along", "angle", "appear",
    "area", "arrange", "aside", "avoid", "awake", "award", "basic", "begin",
    "behind", "below", "bench", "between", "beyond", "border", "bowl", "bread",
    "brush", "bucket", "camera", "camp", "careful", "cause", "change", "choice",
    "clear", "clock", "clothes", "coach", "common", "connect", "consider", "correct",
    "count", "course", "cover", "daily", "danger", "decide", "detail", "direct",
    "during", "earth", "effort", "empty", "enter", "equal", "event", "example",
    "exercise", "expect", "explain", "fair", "finish", "floor", "focus", "follow",
    "future", "glass", "ground", "guide", "handle", "health", "heavy", "history",
    "inside", "keep", "learn", "leave", "level", "listen", "local", "middle",
    "minute", "modern", "notice", "object", "offer", "often", "order", "outside",
    "pattern", "pause", "phone", "please", "point", "possible", "practice", "prepare",
    "present", "problem", "public", "reason", "remember", "repeat", "result", "return",
    "right", "screen", "select", "share", "short", "skill", "slow", "sound",
    "speed", "start", "step", "straight", "study", "system", "thing", "think",
    "through", "today", "under", "usual", "value", "voice", "wait", "watch",
    "whole", "write", "wrong"
  ],
  office: [
    "absence", "access", "adjustment", "administrator", "advisory", "agency", "appraisal", "approver",
    "assistant", "balance", "beneficiary", "business-day", "calendar-invite", "caseload", "cashflow", "certificate",
    "chairperson", "check", "clearance", "close", "comment", "commitment", "compensation", "contact-list",
    "costing", "counterpart", "coverage", "credit", "data-file", "data-point", "deduction", "deliver",
    "deposit", "designation", "disbursement", "disclosure", "distribution-list", "eligibility", "employer", "enclosure",
    "escalate", "exception", "fileroom", "finalize", "followup", "forecasting", "generalist", "grantor",
    "guidance", "inquiry", "insurer", "interoffice", "invoiceable", "leadership", "mailbox", "mailing",
    "managerial", "meeting-room", "monthly", "narrative", "office-wide", "outreach", "payee", "payer",
    "payment-request", "pending", "period", "pointperson", "portfolio", "postage", "pre-approval", "preparer",
    "processing-date", "programmatic", "proofread", "provider", "purchaser", "receipts", "recipient", "reconcilement",
    "refund", "renewal-date", "requestor", "reschedule", "reviewer", "routing", "salary", "section",
    "selection", "signatory", "staffing", "stakeholders", "submission-date", "submitter", "supplier", "telephone-call",
    "timecard", "timekeeping", "training-record", "transfer", "travelclaim", "unit", "vacancy", "variance",
    "verifier", "workday", "workgroup", "work-queue", "worksite", "workweek", "writeup", "yearly",
    "authorization-code", "billing-cycle", "budget-review", "caseworker", "checkin", "checkout", "contractor", "correction",
    "departmental", "deskwork", "documentation-log", "employee-id", "enrollmentform", "expenseclaim", "fiscalperiod", "formletter",
    "fundingrequest", "intakedate", "interviewpanel", "meetingdate", "officehours", "projectstatus", "recordkeeping", "reviewdate",
    "staffmeeting", "tasklist", "timesheetentry", "vendorcontact", "workplan", "telework", "workplace", "workshop", "roster", "overtime", "notary", "paystub", "screening", "settlement", "stipend"
  ],
  technical: [
    "admin", "alias", "allocate", "android", "antivirus", "archive-file", "argument-list", "arraybuffer",
    "audio", "autofill", "boot", "bootloader", "bottleneck", "bug", "button", "cable",
    "capture", "charset", "clipboard", "client-side", "cloud-service", "command-prompt", "compatibility", "cookie-jar",
    "crash", "cursor", "datacenter", "debugger", "desktop-app", "devtools", "displayport", "download",
    "driver-update", "emulator", "ethernet-port", "executable", "extension-file", "failback", "file-handle", "filename",
    "folder", "frontend", "gpu", "graphics-card", "harddrive", "headset", "hotkey", "icon",
    "installer", "internet-access", "keyboard-layout", "laptop-dock", "localstorage", "login", "logout", "malware",
    "metadata", "microphone", "monitor", "mouse", "networking", "notification", "operating-system", "output",
    "password", "pathname", "peripheral-device", "pixelratio", "plugandplay", "power-cycle", "powershell", "processlist",
    "reboot", "redirect", "resolution", "restart", "safemode", "screenshot", "scrollbar", "searchindex",
    "security-patch", "serial-number", "shortcut", "sidebar", "signin", "signout", "softwareupdate", "solidstate",
    "startup", "stylesheet", "taskbar", "touchscreen", "traceroute", "upload", "username", "utility",
    "videocard", "webapp", "webpage", "webview", "windowmanager", "wirelessadapter", "workstation", "accessibilitytree",
    "browsercache", "browserstorage", "buildtool", "cacheentry", "clientapp", "codeeditor", "configfile", "connectionpool",
    "datastore", "dependencytree", "devserver", "diskspace", "errorlog", "eventhandler", "filetransfer", "gatewayroute",
    "inputdevice", "logentry", "memoryusage", "networkdrive", "packetfilter", "proxyserver", "remoteaccess", "remotedesktop",
    "requestqueue", "runtimecheck", "serverlog", "sessiondata", "systemlog", "testdata", "testcase", "updatecheck",
    "userprofile", "webclient", "webhost", "websocketclient", "webhook", "widget", "bitmap", "boolean", "bytecode", "captcha", "coroutine", "datagram", "devops", "favicon", "hotfix", "iframe", "intranet", "namespace", "opcode", "overflow", "plaintext", "regex", "sandbox", "sitemap", "spyware", "tooltip", "webcam"
  ]
};
Object.entries(WORD_LIST_EXPANSION_6).forEach(([listName, additions]) => {
  const existing = new Set(WORD_LISTS[listName]);
  additions.forEach(word => {
    const normalized = word.toLowerCase();
    if (!existing.has(normalized)) { WORD_LISTS[listName].push(normalized); existing.add(normalized); }
  });
});

export const PREFIX_SUFFIX_CHUNKS = [
  "anti", "auto", "bio", "co", "de", "dis", "extra", "hyper", "inter", "micro",
  "mis", "non", "over", "post", "pre", "pro", "re", "semi", "sub", "trans",
  "able", "al", "er", "ful", "hood", "ing", "ion", "ish", "ism", "ist",
  "ity", "less", "ly", "ment", "ness", "ous", "ship", "tion", "ward"
];

export const MODE_METADATA = [
  {
    id: "creatureLab",
    title: "Creature Lab",
    subtitle: "Run a full creature-research program with specimen families, build objectives, rare traits, and bonus DNA.",
    tags: ["Words", "Accuracy", "Research"],
    guide: [
      "Choose a lab program and batch length from Blake's pre-game briefing.",
      "Each specimen belongs to one of several families with a distinct vat silhouette and receives a build objective.",
      "Type eight DNA strands per specimen; incorrect or expired strands still create visible mismatched anatomy.",
      "Rare spontaneous traits can appear during assembly, with Mutation Survey greatly increasing their frequency.",
      "Every specimen is followed by a short bonus DNA sequence for extra score and research objectives.",
      "Archived specimens remain visible in the session gallery until the entire batch is complete."
    ]
  },
  {
    id: "farOffAdventures",
    title: "Far Off Adventures",
    subtitle: "Choose a route and rhythm program, then fly through changing weather, altitude zones, and checkpoints.",
    tags: ["Rhythm", "Weather", "Expedition"],
    guide: [
      "Choose a route, flight length, and rhythm program from Blake's pre-game briefing.",
      "Type the highlighted character in sequence; clean rhythm raises the balloon while mistakes and long pauses cost altitude.",
      "Weather changes during the flight. Crosswinds, gusts, rain, thin air, and turbulence alter the pressure on the balloon.",
      "Pace Shift and Mixed Expedition modes periodically ask for a different target cadence instead of one constant rhythm.",
      "Three checkpoints occur during the flight. Reach them with enough altitude to earn a score and altitude bonus.",
      "Touching the ground ends the expedition; longer routes demand sustained rhythm through more weather changes."
    ]
  },
  {
    id: "checkOutTime",
    title: "Check-Out Time",
    subtitle: "Run different checkout lanes with prices, discounts, tax totals, basket audits, and rush periods.",
    tags: ["10-key", "Calculations", "Rush"],
    guide: [
      "Choose Standard, Express, Discount Desk, or Audit Lane before the shift.",
      "Type the exact displayed amount, including the decimal point. Some cards ask for a discounted price or a price plus the shown tax amount.",
      "Standard, Discount, and Audit lanes periodically send a basket-total card based on successfully scanned items.",
      "Rush periods temporarily accelerate both conveyor speed and item arrival rate.",
      "Numpad Only mode rejects the keyboard number row so the session becomes dedicated 10-key practice.",
      "Too many missed entries closes the lane early; otherwise survive until the register closes."
    ]
  },
  {
    id: "roadRace",
    title: "Road Race",
    subtitle: "Choose a track, rival, race length, and typing style, then out-type the competition through a scrolling text ribbon.",
    tags: ["Continuous Text", "Speed", "Variants"],
    guide: [
      "Choose one of four tracks, four rivals, three race lengths, and four text styles before the race.",
      "Classic Word Salad, Office Stream, and Technical Stream use long continuous word ribbons; Sentence Run adds capitals and punctuation.",
      "Type the highlighted token exactly and press Space after completing it; the ribbon automatically scrolls forward.",
      "Each rival has a different pace pattern: steady, burst-speed, or a late-race charge.",
      "Mistyped characters cost accuracy and a little momentum, but the ribbon waits for the correct key.",
      "Reach the finish line first; Sprint, Standard, and Endurance change how long both racers must sustain their pace."
    ]
  },
  {
    id: "chameleonPicnic",
    title: "Chameleon Picnic",
    subtitle: "Defend three picnic lanes with classic letters, Shift targets, two-key ants, combos, and golden bonus targets.",
    tags: ["Reaction", "Mixed Case", "Combos"],
    guide: [
      "Choose Classic Feeding, Case Crunch, Pair Panic, or Festival Mix before the round; each changes the target mix without removing the existing swarm pressure.",
      "Ants now travel through three named lanes. Scan all three, because a crowded lane can become dangerous while another looks calm.",
      "Case targets are case-sensitive and therefore require Shift; two-character targets use a short visible input buffer.",
      "Consecutive catches build a combo and award small escalating bonuses. A wrong key or regular escape breaks the combo.",
      "Golden ants are optional bonus targets worth extra points. If one escapes it does not consume the normal escape limit.",
      "Rushes and swarm phases remain active on every difficulty, and wrong keys still shove the entire field forward."
    ]
  },
  {
    id: "spaceJunk",
    title: "Space Junk",
    subtitle: "Defend selectable stations through structured orbital waves, armored debris, shields, and emergency pickups.",
    tags: ["Fragments", "Waves", "Defense"],
    guide: [
      "Choose a station, mission profile, and watch length before launch. Stations trade hull, shield capacity, score bonus, and pressure.",
      "Normal debris is destroyed with one fragment. Armored debris exposes a second fragment after the first hit and is pushed slightly away from the station.",
      "Structured waves include Velocity Storms, Armored Convoys, Crossfire, Clusters, and Salvage Windows rather than only random junk storms.",
      "Shield charges absorb incoming collisions before hull damage. Armored impacts cause two hull damage if no shield is available.",
      "Green defense pickups can restore shields or hull; sustained defense can also recharge one defense point periodically.",
      "Mission profiles emphasize standard patrol, armored fields, storm pressure, or salvage opportunities while preserving continuous background traffic."
    ]
  },
  {
    id: "sharkAttack",
    title: "Shark Attack",
    subtitle: "Escape multiple water scenarios while different predators change the shape of the pursuit.",
    tags: ["Paragraph", "Pursuit", "Scenarios"],
    guide: [
      "Choose Open Water, Reef Run, Storm Channel, or Night Swim before the chase.",
      "Reef Shark is steady, Mako uses speed bursts, Hammerhead gains ground on mistakes, and Great White accelerates late.",
      "Type the displayed passage character by character; spaces, capitalization, hyphens, and punctuation count exactly.",
      "Checkpoint buoys push the shark backward and award bonus score, giving accurate sustained typing real breathing room.",
      "Reef and Storm routes add current events; Night Swim deliberately limits how far ahead the passage can be read.",
      "Sprint, Standard, and Endurance alter passage length and checkpoint count without secretly increasing predator speed."
    ]
  },
  {
    id: "penguinCrossing",
    title: "Penguin Crossing",
    subtitle: "Cross alternate ice routes with fragile floes, bonus markers, and optional route forks.",
    tags: ["Words", "Timing", "Routes"],
    guide: [
      "The original 1.8-second opening grace, eight-floe field, and baseline movement pressure remain intact.",
      "Classic Channel preserves the established crossing; Glacier Fork periodically lets you type either of two route words.",
      "Fragile Shelf produces more brittle targets that fracture if you stay on them too long, costing margin but not changing base speed.",
      "Aurora Crossing favors bonus floes; completing one awards extra score and delays the next environmental event briefly.",
      "Floe Program can independently favor standard, fragile, bonus, or mixed ice on any route.",
      "Wind gusts, ordinary cracks, and current surges continue to pressure the field exactly as before."
    ]
  }
];

export const BLAKE_QUOTES = [
  "“I didn't leave the spreadsheet open. I left the computer open. Different thing.”",
  "“The printer tray is basically a filing system if you think about it.”",
  "“I knew where the laptop was. Eventually.”",
  "“I only tried the secure door because I wanted to know if it was secure.”",
  "“Nobody out-types Blake. Compliance has tested that theory repeatedly.”",
  "“My password is extremely secure. I have it written down so I never lose it.”",
  "“The badge reader beeped, which means it definitely noticed me.”",
  "“I don't call them incidents. I call them workflow discoveries.”",
  "“If I can type the corrective action in under thirty seconds, was it really that serious?”",
  "“I read ahead. That's why I finish emails before everyone else finishes explaining what they wanted.”",
  "“Accuracy first, speed second. Unless there's a leaderboard, obviously.”",
  "“You can tell a file is important because everybody gets upset when you misplace it.”",
  "“I have never lost a keyboard. That's the equipment category where my record is spotless.”",
  "“The lock screen and I have a professional disagreement about productivity.”",
  "“A clipboard makes anybody look authorized. That's just office science.”",
  "“Compliance and I both believe in documentation. We disagree about why there is so much of it.”",
  "“The best typing rhythm is the one that makes your supervisor stop asking when the report will be done.”",
  "“I've taken the privacy training enough times that I could probably teach it. They said absolutely not.”",
  "“If the penguin can survive that crossing, you can survive punctuation.”",
  "“Space Junk proves that nearly every emergency can be improved by typing faster.”",
  "“My personnel file is very complete. I assume that's a compliment.”",
  "“I don't tailgate. I perform passive badge-assisted entry.”",
  "“The creature was supposed to have that many legs. The software just didn't know yet.”",
  "“HyperSoft pays me to teach typing and very specifically nothing else.”",
  "“Someday someone will beat my WPM. Management has asked me to stop saying that like a threat.”"
];
