let categoryNames = [
  'Clothing',
  'Produce',
  'Bakery',
  'Other Grocery',
  'Beverages',
  'Dairy',
  'Cleaning Supplies',
  'Pet Supplies',
  'Electronics/Home Office',
  'Crafts/Party Supplies',
  'Home Goods',
  'Home Improvement',
  'Sporting Goods',
  'Toys',
  'Clearance',
  'Garden/Outdoor',
  'Cosmetic/Health',
  'Seasonal',
  'Frozen Food',
  'Checkout Area',
];
