/* v1.6.46 — Spawn Foundations II
   District identity, named urban sub-locations, avenues, and local city navigation.
   The Spawn remains one metropolis: districts are regional locations; places within
   a district are local destinations and do not become fake standalone settlements. */

const SPAWN_AVENUES=[
 {id:'highroad',name:'Highroad Avenue',axis:'north–south',districts:['spawn_northcentral','spawn_civic','spawn_centralres','spawn_stockyards'],desc:'The monumental north–south avenue entering from Shantium and running almost straight through the civic heart toward the southern trade quarters.'},
 {id:'marketway',name:'Market Way',axis:'north–south',districts:['spawn_market','spawn_merchant','spawn_warehouses','spawn_bazaar'],desc:'A broad eastern commercial artery carrying shoppers, freight, merchants, and caravans between the Market District and the southeastern gate.'},
 {id:'northwall',name:'North Wall Road',axis:'east–west',districts:['spawn_northwest','spawn_northgate','spawn_northcentral','spawn_market'],desc:'The long road inside the northern wall, tying the city’s northern quarters and two foreign approaches together.'},
 {id:'civiccross',name:'Civic Crossway',axis:'east–west',districts:['spawn_west','spawn_works','spawn_civic','spawn_merchant'],desc:'A formal east–west boulevard crossing the administrative center and linking workshops to merchant offices.'},
 {id:'oldcross',name:'Old Crossway',axis:'east–west',districts:['spawn_working','spawn_oldcity','spawn_centralres','spawn_warehouses'],desc:'A heavily used middle-city route whose alignment is newer and straighter than some of the streets it cuts through in Old Spawn.'},
 {id:'southway',name:'Southway',axis:'east–west',districts:['spawn_southwest','spawn_spirits','spawn_stockyards','spawn_bazaar'],desc:'The southern freight and labor artery, busy with barrels, livestock, wagons, workers, and desert-bound trade.'}
];

const SPAWN_DISTRICTS={
 spawn_northwest:{character:'Quiet by Spawn standards: long residential blocks, neighborhood courts, schools, gardens, and local shops behind the northwestern wall.',landmarks:[['Wall Gardens','A chain of rectangular public gardens built against the inner wall, giving dense northern households rare open space.'],['Northwest Commons','A large neighborhood square used for food sellers, notices, gatherings, and ordinary local business.'],['Lantern Rows','Orderly residential streets of multistory homes and small corner businesses.']]},
 spawn_northgate:{character:'A monumental arrival quarter built around gate traffic, lodging, transport, and the constant movement of visitors who are not yet deep inside the city.',landmarks:[['Great North Gate','One of the city’s largest gate complexes, opening onto roads serving the northern approaches.'],['Gatehouse Square','A huge paved rectangle where wagons are sorted, travelers regroup, and officials manage incoming traffic.'],['Travelers’ Row','A concentration of inns, stables, eating houses, and services for people passing through the north city.']]},
 spawn_northcentral:{character:'The formal Shantium-facing entrance to the Spawn. Broad paving, severe geometry, monumental facades, and Highroad Avenue provide a deliberately impressive first view of the metropolis.',landmarks:[['Highroad Gate','The city gate reached by the road from Southroad Camp and Shantium.'],['Highroad Promenade','A broad processional section of Highroad Avenue lined with substantial civic and commercial buildings.'],['North-Central Exchange','A busy transport square where arriving wagons and passengers disperse into the city grid.']]},
 spawn_market:{character:'The city’s immense everyday shopping district. Open-air sellers and permanent shops compete block after block, often carrying the same ordinary goods at different prices.',landmarks:[['Upper Market','The northern blocks nearest the Tyrdon gate, crowded with arriving Sengian goods and road merchants.'],['Market Cross','A vast open intersection and plaza where several market streets meet.'],['Equipment Rows','Long runs of competing armorers, tool sellers, outfitters, secondhand dealers, and general merchants.'],['Lower Market','Dense southern market blocks where wholesale and household commerce overlap.']]},
 spawn_west:{character:'A dense, established residential district with broad neighborhood avenues, practical services, and relatively little destination commerce.',landmarks:[['West Commons','A civic square serving several surrounding residential blocks.'],['Longhouse Blocks','Large rectangular housing blocks divided into homes, courtyards, and small workshops.'],['West Avenue Shops','A modest commercial strip serving residents rather than travelers.']]},
 spawn_works:{character:'One of the productive engines of the city: textiles, ceramics, glass, furniture, fine woodwork, metal goods, leatherwork, and luxury components emerge from closely packed workshops.',landmarks:[['Great Workshop Row','Large workshops and guild houses occupying several straight industrial blocks.'],['Kiln Court','A heat-hazed concentration of potters, glassworkers, tile makers, and firing yards.'],['Fineworks Arcade','Skilled craftspeople producing jewelry, decorative metalwork, furnishings, and components for the luxury trade.'],['Cloth Halls','Weavers, dyers, cutters, and factors handling fabric at metropolitan scale.']]},
 spawn_civic:{character:'The administrative heart of the Spawn. Here the city’s geometric planning becomes monumental: enormous plazas, aligned government halls, archives, courts, and offices.',landmarks:[['Great Administrative Plaza','A vast rectangular civic space framed by the principal offices of Spawn government.'],['Hall of the Great Admin','The central seat of metropolitan administration and the highest civic authority in the Spawn.'],['Central Archives','Extensive public and government records housed in a severe stone complex.'],['Courts of Administration','Courts and hearing chambers handling the legal and administrative business of an enormous city.']]},
 spawn_merchant:{character:'Commerce here is measured in cargoes and contracts rather than individual purchases. Merchant houses, brokers, factors, insurers, and trading companies fill the eastern blocks.',landmarks:[['Factors’ Square','A formal commercial square where brokers and agents arrange large transactions.'],['Company Row','Offices and compounds of established trading houses.'],['Exchange Hall','A meeting place for wholesale contracts, cargo sales, financing, and commercial information.'],['Counting Houses','Money changers, lenders, accountants, and private commercial offices.']]},
 spawn_working:{character:'A crowded working neighborhood beside heavy industry. Tenements, cheap meals, repair shops, labor hiring, and small manufactories fill nearly every block.',landmarks:[['Foundry Square','The loud center of the ward, surrounded by metalworking yards and labor traffic.'],['Workers’ Rows','Dense housing for laborers and their families.'],['Hiring Corner','A traditional gathering place where foremen and workers negotiate short-term labor.'],['Hammer Street','Repairers, small smiths, toolmakers, and practical workshops serving the surrounding industry.']]},
 spawn_oldcity:{character:'The surviving old heart of the Spawn. Its streets are still broadly ordered, but blocks are smaller, alignments shift, and ancient buildings interrupt the later city grid.',landmarks:[['Old Square','A smaller, older civic square that predates the monumental modern plan.'],['Founders’ Street','A narrow historic commercial street lined with some of the oldest continuously occupied buildings in the city.'],['Covered Cistern','An old public waterworks fed by the buried and diverted river system beneath the metropolis.'],['Old Arcade','A roofed passage of specialized shops, food sellers, and long-established family businesses.']]},
 spawn_centralres:{character:'An enormous mixed residential district in the center-south city: apartments, townhouses, neighborhood institutions, schools, small parks, and local commerce.',landmarks:[['Central Commons','A major public square and everyday meeting place.'],['Terrace Blocks','Prosperous multistory homes arranged along unusually broad streets.'],['Fountain Court','A public square built around one of the visible outlets of the city’s managed water system.'],['South Central Shops','A busy but ordinary neighborhood shopping avenue.']]},
 spawn_warehouses:{character:'Freight dominates the eastern middle city. Long stone warehouses, loading courts, wagon yards, and wholesale storage connect northern markets with southern caravan trade.',landmarks:[['Long Warehouses','Several enormous parallel warehouse blocks divided among merchants and trading companies.'],['Freight Court','A broad loading square crowded with carts, porters, and cargo.'],['Carters’ Yard','Stabling, repairs, hiring, and dispatch for the city’s freight wagons.'],['Bonded Stores','Guarded storage used for valuable or administratively controlled cargo.']]},
 spawn_southwest:{character:'A sprawling residential quarter populated heavily by working and lower-middle-income households, with its own commons, schools, shrines, taverns, and neighborhood commerce.',landmarks:[['Southwest Commons','A large public square surrounded by everyday shops and eating houses.'],['Brick Rows','Dense residential blocks built during one of the city’s major southern expansions.'],['South Wall Walk','A broad interior road running beside the city wall.']]},
 spawn_spirits:{character:'The center of the Spawn’s domestic spirits industry. Breweries and distilleries operate at a scale made possible by the city’s immense population and trade network.',landmarks:[['Brewers’ Mile','A long industrial street dominated by breweries, cooperages, and distributors.'],['Distillers’ Court','A concentration of distilleries and specialist spirit merchants.'],['Barrel Yards','Coopers, storage sheds, loading courts, and stacks of casks awaiting distribution.'],['Tavern Row','A famously dense strip of drinking houses serving workers, merchants, and visitors.']]},
 spawn_stockyards:{character:'The city’s principal livestock intake. Desert herders and ranchers bring cattle to the nearest enormous market, where animals are sold, held, processed, and redistributed.',landmarks:[['Great Stockyard','A vast complex of pens divided into geometric holding blocks.'],['Cattle Exchange','The principal auction and wholesale livestock market.'],['Drovers’ Yard','Lodging, feed, stables, and services catering to herders arriving from the southeast.'],['Tanners’ Row','Leather processors and related trades positioned downwind of more fashionable districts.']]},
 spawn_bazaar:{character:'The southeastern face of the Spawn, where centuries of desert traffic have left their strongest cultural mark. It remains unmistakably Spawn, but its trade, food, lodging, and street life are more desert-influenced.',landmarks:[['Grand Bazaar','A sprawling open-air and covered market serving desert caravans, Spawn residents, foreign merchants, and specialist traders.'],['Caravan Courts','Large enclosed yards where desert caravans unload, rest, hire guards, and arrange onward trade.'],['Desert Gate Avenue','The final broad avenue leading southeast toward the Gate of the Endless Road.'],['Southeast Stables','Extensive stabling and animal services for caravan traffic.'],['Gate of the Endless Road','The monumental southeastern gate. The Endless Desert lies beyond it, but that road is not yet open to the Player Party.']]}
};

function spawnDistrictProfile(id=state.world.location){return SPAWN_DISTRICTS[id]||null}
function spawnAvenuesAt(id=state.world.location){return SPAWN_AVENUES.filter(a=>a.districts.includes(id))}
function spawnDistrictLocalIndex(id=state.world.location){const p=spawnDistrictProfile(id);return p?p.landmarks.map((x,i)=>({id:`${id}:${i}`,name:x[0],desc:x[1]})):[]}
function spawnDistrictAtmosphere(id=state.world.location){const p=spawnDistrictProfile(id);if(!p)return'';const traffic=(state.world.parties||[]).filter(x=>x.location===id||x.destination===id).length;return `${p.character} ${traffic>=4?'Traffic is exceptionally heavy even by Spawn standards.':traffic>=2?'The avenues carry a steady metropolitan flow of people and goods.':'The surrounding streets remain busy with ordinary city life.'}`}
function showSpawnDistrictGuide(id=state.world.location){
 const loc=worldLocation(id),p=spawnDistrictProfile(id);if(!p||locationRegion(id)!=='spawn')return showWorldArea();
 modalRouteEnter('showSpawnDistrictGuide',[id]);
 const avenues=spawnAvenuesAt(id),places=spawnDistrictLocalIndex(id),highroadExit=id==='spawn_northcentral'?`<h3>Highroad Gate</h3><div class="card"><b>Road to Shantium Region</b><br><small>The great road leaves the Spawn here for Southroad Camp, the Shantium-side roadhead.</small><br><button id="spawnHighroadExit">Cross into Shantium Region</button></div>`:'';
 overlay(`<h2>${esc(loc.name)}</h2><p>${esc(spawnDistrictAtmosphere(id))}</p><div class="notice compact"><b>City position:</b> ${Math.round(loc.x)} east • ${Math.round(loc.y)} south<br><b>District travel:</b> local movement through the Spawn does not consume a campaign day.</div><h3>Major Avenues</h3>${avenues.map(a=>`<div class="card compact"><b>${esc(a.name)}</b> • <small>${esc(a.axis)}</small><br>${esc(a.desc)}</div>`).join('')||'<p class="muted">Local streets connect this district to the surrounding grid.</p>'}${typeof spawnDistrictPopulationHTML==='function'?spawnDistrictPopulationHTML(id):''}${typeof spawnDistrictInstitutionsHTML==='function'?spawnDistrictInstitutionsHTML(id):''}${typeof spawnDistrictServicesHTML==='function'?spawnDistrictServicesHTML(id):''}${typeof spawnMarketDistrictCommerceHTML==='function'?spawnMarketDistrictCommerceHTML(id):''}${typeof spawnEconomyDistrictHTML==='function'?spawnEconomyDistrictHTML(id):''}${typeof spawnUrbanDistrictHTML==='function'?spawnUrbanDistrictHTML(id):''}${typeof spawnUrbanOpportunityHTML==='function'?spawnUrbanOpportunityHTML(id):''}${typeof spawnDistrictLawHTML==='function'?spawnDistrictLawHTML(id):''}${typeof spawnDistrictSocialHTML==='function'?spawnDistrictSocialHTML(id):''}${typeof spawnContractsDistrictHTML==='function'?spawnContractsDistrictHTML(id):''}${highroadExit}<h3>Places in ${esc(loc.name)}</h3><div class="choice-list compact">${places.map(x=>`<button data-spawnplace="${esc(x.id)}"><b>${esc(x.name)}</b><small>${esc(x.desc)}</small></button>`).join('')}</div><div class="dialog-footer"><button class="closeModal">Back to District</button></div>`,true);
 document.querySelectorAll('[data-spawnplace]').forEach(b=>b.onclick=()=>showSpawnLocalPlace(id,b.dataset.spawnplace));const highroadBtn=$('#spawnHighroadExit');if(highroadBtn)highroadBtn.onclick=()=>{const c=REGION_CONNECTIONS.find(x=>x.id==='southroad_spawn');if(!c)return actionResult('Road Connection Missing','The Highroad Gate cannot currently resolve the Shantium road connection.','bad',()=>showSpawnDistrictGuide(id));commitInterRegionJourney(c,'spawn_northcentral','southroad')};if(typeof wireSpawnDistrictServices==='function')wireSpawnDistrictServices(id);if(typeof wireSpawnMarketDistrictCommerce==='function')wireSpawnMarketDistrictCommerce(id);if(typeof wireSpawnEconomyDistrict==='function')wireSpawnEconomyDistrict(id);if(typeof wireSpawnUrbanDistrict==='function')wireSpawnUrbanDistrict(id);if(typeof wireSpawnUrbanOpportunity==='function')wireSpawnUrbanOpportunity(id);if(typeof wireSpawnDistrictLaw==='function')wireSpawnDistrictLaw(id);if(typeof wireSpawnDistrictSocial==='function')wireSpawnDistrictSocial(id);if(typeof wireSpawnContractsDistrict==='function')wireSpawnContractsDistrict(id);wireClose()
}
function showSpawnLocalPlace(districtId,placeId){
 const loc=worldLocation(districtId),place=spawnDistrictLocalIndex(districtId).find(x=>x.id===placeId);if(!place)return showSpawnDistrictGuide(districtId);
 modalRouteEnter('showSpawnLocalPlace',[districtId,placeId]);
 const nearby=(state.world.parties||[]).filter(p=>p.location===districtId).slice(0,4);
 overlay(`<h2>${esc(place.name)}</h2><p>${esc(place.desc)}</p><div class="notice compact"><b>${esc(loc.name)}</b><br>This is a local destination within the district, not a separate settlement. Walking here does not advance the campaign day.</div>${typeof spawnUrbanLocalActivityHTML==='function'?spawnUrbanLocalActivityHTML(districtId):''}${nearby.length?`<h3>Street Activity</h3>${nearby.map(p=>`<div class="card compact"><b>${esc(p.name)}</b><br><small>${esc(worldPartyBehavior(p).label)} • ${esc(p.faction||'Unaffiliated')}</small></div>`).join('')}`:'<p class="muted">Crowds, residents, workers, and ordinary traffic fill the surrounding streets.</p>'}<div class="dialog-footer"><button id="spawnPlaceBack">Back to ${esc(loc.name)}</button></div>`,true);
 $('#spawnPlaceBack').onclick=()=>modalNavBackOrFallback(()=>showSpawnDistrictGuide(districtId))
}
