/* v1.6.66.9 — Guardian Military Authorization & Land */
const GUARDIAN_MILITARY_CHARTER_VERSION=1;
function guardianMilitaryState(){const W=ensureWarFoundation();if(!W.guardianMilitary||typeof W.guardianMilitary!=='object')W.guardianMilitary={version:GUARDIAN_MILITARY_CHARTER_VERSION,authorization:null,land:null,history:[],lastController:null};const G=W.guardianMilitary;G.version=GUARDIAN_MILITARY_CHARTER_VERSION;if(!Array.isArray(G.history))G.history=[];return G}
function guardianMilitaryController(){return settlementControl('shantium')||'Shantium'}
function guardianMilitaryStanding(){return state.world.factionStanding?.[guardianMilitaryController()]||0}
function guardianMilitaryLandCost(){const standing=guardianMilitaryStanding();return Math.max(3500,Math.round((9000-standing*350)/250)*250)}
function guardianMilitaryCanPetition(){return guardianMilitaryStanding()>=0}
function guardianMilitaryEnsureControllerReview(){
 const G=guardianMilitaryState(),controller=guardianMilitaryController();if(G.lastController==null){G.lastController=controller;return}
 if(G.lastController===controller)return;const old=G.lastController;G.lastController=controller;
 if(G.authorization?.status==='granted'){G.authorization.status='review';G.authorization.reviewDay=state.world.day;G.authorization.reviewController=controller;G.history.push({day:state.world.day,type:'charter_review',text:`The change of authority in Shantium places the Guardian military charter under review by ${majorFaction(controller)?.short||controller}.`});recordWorldHistory(`Shantium's new authorities call the Guardian's military charter for review. Existing Guardian Hall facilities remain undisturbed while the separate military establishment awaits confirmation.`,'info','war')}
}
function guardianMilitaryPetition(){
 const G=guardianMilitaryState(),controller=guardianMilitaryController(),standing=guardianMilitaryStanding();if(G.authorization?.status==='granted'&&G.authorization.controller===controller)return showGuardianMilitaryAuthorization();
 if(!guardianMilitaryCanPetition())return actionResult('Military Charter Refused',`${majorFaction(controller)?.short||controller} officials will not authorize a separate Guardian military establishment while your standing with them is ${standing}. Improve relations before petitioning again.`,'bad',showGuardianMilitaryAuthorization);
 const fee=Math.max(250,750-Math.max(0,standing)*50);if(state.gold<fee)return actionResult('Petition Not Filed',`Formal surveys, legal instruments, and charter fees require ${fmt(fee)} gold.`,'bad',showGuardianMilitaryAuthorization);
 state.gold-=fee;G.authorization={status:'granted',controller,grantedDay:state.world.day,fee,standingAtGrant:standing,terms:'Independent Guardian field force; Hall private security remains separate.'};G.lastController=controller;G.history.push({day:state.world.day,type:'authorization',text:`${majorFaction(controller)?.short||controller} grants the Guardian authority to establish a separate military ground outside the Hall.`});recordWorldHistory(`${majorFaction(controller)?.short||controller} grants the Guardian a charter for a separate military establishment in Shantium. Guardian Hall and its private guard remain distinct from the new field force.`,'good','war');save();return actionResult('Military Charter Granted',`You may now acquire separate land in Shantium for a Guardian military establishment. Existing Guardian Hall facilities and Hall guards remain private Hall assets and are not converted into soldiers.`,'good',showGuardianMilitaryAuthorization)
}
function guardianMilitaryConfirmCharter(){
 const G=guardianMilitaryState(),controller=guardianMilitaryController(),standing=guardianMilitaryStanding();if(G.authorization?.status!=='review')return showGuardianMilitaryAuthorization();
 if(standing<0)return actionResult('Charter Review Unresolved',`${majorFaction(controller)?.short||controller} will not confirm the military charter at your current standing of ${standing}. Existing Hall facilities remain grandfathered, but new military construction is suspended.`,'bad',showGuardianMilitaryAuthorization);
 const fee=Math.max(0,500-standing*50);if(state.gold<fee)return actionResult('Charter Review Pending',`Confirmation requires ${fmt(fee)} gold in new surveys and legal filings.`,'bad',showGuardianMilitaryAuthorization);state.gold-=fee;G.authorization={...G.authorization,status:'granted',controller,confirmedDay:state.world.day,reviewFee:fee};G.history.push({day:state.world.day,type:'charter_confirmed',text:`${majorFaction(controller)?.short||controller} confirms the Guardian military charter after the change of authority.`});save();return actionResult('Charter Confirmed','The new authorities recognize the Guardian military charter. Existing military land and future construction remain authorized.','good',showGuardianMilitaryAuthorization)
}
function guardianMilitaryAcquireLand(){
 const G=guardianMilitaryState(),controller=guardianMilitaryController();if(G.authorization?.status!=='granted'||G.authorization.controller!==controller)return actionResult('Authorization Required','A valid charter from Shantium’s current political authority is required before military land can be acquired.','bad',showGuardianMilitaryAuthorization);if(G.land?.owned)return showGuardianMilitaryAuthorization();
 const cost=guardianMilitaryLandCost();if(state.gold<cost)return actionResult('Land Not Acquired',`The surveyed military ground costs ${fmt(cost)} gold. Your standing with ${majorFaction(controller)?.short||controller} affects the negotiated price.`,'bad',showGuardianMilitaryAuthorization);
 state.gold-=cost;G.land={owned:true,location:'shantium',acquiredDay:state.world.day,cost,controllerAtPurchase:controller,name:'Guardian Military Grounds',capacityStage:0};G.history.push({day:state.world.day,type:'land_acquired',text:`The Guardian acquires separate land in Shantium for the Guardian Military Grounds.`});recordWorldHistory(`The Guardian acquires a separate tract in Shantium for a future military establishment. Guardian Hall remains a private residence and headquarters rather than a barracks.`,'good','war');save();return actionResult('Military Grounds Acquired','The Guardian Military Grounds are now legally established. The land is separate from Guardian Hall and is ready for barracks development in the next stage of military expansion.','good',showGuardianMilitaryAuthorization)
}
function showGuardianMilitaryAuthorization(){modalRouteEnter('showGuardianMilitaryAuthorization',Array.from(arguments));guardianMilitaryEnsureControllerReview();const G=guardianMilitaryState(),controller=guardianMilitaryController(),standing=guardianMilitaryStanding(),auth=G.authorization,land=G.land,cost=guardianMilitaryLandCost(),name=majorFaction(controller)?.short||controller;
 const status=auth?.status==='granted'&&auth.controller===controller?`Charter granted by ${esc(name)}`:auth?.status==='review'?`Charter under review by ${esc(name)}`:'No military charter';
 overlay(`<h2>Guardian Military Establishment</h2><p>The Guardian Hall's private guard protects the Hall. Raising a field army is a separate undertaking and requires the consent of whoever governs Shantium.</p><div class="card compact"><div class="stat-row"><span>Current authority in Shantium</span><b>${esc(name)}</b></div><div class="stat-row"><span>Your standing</span><b>${standing}</b></div><div class="stat-row"><span>Military charter</span><b>${status}</b></div><div class="stat-row"><span>Military land</span><b>${land?.owned?esc(land.name):'Not acquired'}</b></div></div><div class="notice compact"><b>Guardian Hall is grandfathered.</b><br>The Hall, its defenses, and its private guards remain lawful existing institutions. They do not become part of the field military and do not satisfy the land requirement for barracks.</div><div class="choice-list">${!auth||auth.status==='refused'?`<button id="guardianMilitaryPetition" ${guardianMilitaryCanPetition()?'':'disabled'}>Petition ${esc(name)} for a Military Charter</button>`:''}${auth?.status==='review'?'<button id="guardianMilitaryReview">Seek Confirmation of the Charter</button>':''}${auth?.status==='granted'&&auth.controller===controller&&!land?.owned?`<button id="guardianMilitaryLand">Acquire Military Grounds — ${fmt(cost)} gold</button>`:''}${land?.owned?'<div class="notice success"><b>Guardian Military Grounds established.</b><br>Separate land is secured for the barracks, training grounds, armory, quartermaster stores, hospital, stables, and command facilities that can follow.</div>':''}</div><div class="dialog-footer"><button id="guardianMilitaryBack">Back to Guardian Hall</button></div>`,true);
 if($('#guardianMilitaryPetition'))$('#guardianMilitaryPetition').onclick=guardianMilitaryPetition;if($('#guardianMilitaryReview'))$('#guardianMilitaryReview').onclick=guardianMilitaryConfirmCharter;if($('#guardianMilitaryLand'))$('#guardianMilitaryLand').onclick=guardianMilitaryAcquireLand;$('#guardianMilitaryBack').onclick=()=>SOSServices.navigation.back(showHomeBase)
}
const __warStrategicDailyTickGuardianMilitary=warStrategicDailyTick;warStrategicDailyTick=function(){guardianMilitaryEnsureControllerReview();return __warStrategicDailyTickGuardianMilitary.apply(this,arguments)};
