/* v1.6.66.1 — Mobilization, Campaigns & Strategic AI */
const WAR_STRATEGY_VERSION=1;
function warStrategyState(){const W=ensureWarFoundation();if(!W.strategy||typeof W.strategy!=='object')W.strategy={version:WAR_STRATEGY_VERSION,lastTickDay:0,lastPlanningDay:0,contacts:[],history:[]};W.strategy.version=WAR_STRATEGY_VERSION;if(!Array.isArray(W.strategy.contacts))W.strategy.contacts=[];if(!Array.isArray(W.strategy.history))W.strategy.history=[];return W.strategy}
function warSideForFaction(w,f){return (w?.sides||[]).find(s=>s.includes(f))||null}
function warEnemiesForFaction(w,f){const own=warSideForFaction(w,f);if(!own)return[];return (w.sides||[]).filter(s=>s!==own).flat().filter(warFactionEligible)}
function warActiveFormations(f=null){return ensureWarFoundation().formations.filter(F=>!['destroyed','disbanded'].includes(F.status)&&(!f||F.faction===f))}
function warCampaigns(w){if(!Array.isArray(w.campaigns))w.campaigns=[];return w.campaigns}
function warSettlementValue(id){const L=worldLocation(id),S=settlementState(id);const tier={metropolis:7,city:6,town:4,village:3,outpost:2}[L?.settlementTier]||2;return tier*20+Math.min(60,(S?.population||100)/20)+Math.min(25,(S?.prosperity||50)/4)+(L?.type==='fort'?25:0)}
function warLocationDistance(a,b){const A=worldLocation(a),B=worldLocation(b);if(!A||!B)return 999;const regionPenalty=locationRegion(a)===locationRegion(b)?0:65;const dx=(A.x||0)-(B.x||0),dy=(A.y||0)-(B.y||0);return Math.sqrt(dx*dx+dy*dy)+regionPenalty}
function warChooseObjective(w,f){const enemies=warEnemiesForFaction(w,f);if(!enemies.length)return null;const base=warFactionBase(f);let targets=[];for(const e of enemies){for(const L of warFactionSettlements(e))targets.push({id:L.id,enemy:e,value:warSettlementValue(L.id),distance:warLocationDistance(base,L.id)})}if(!targets.length){for(const e of enemies){const id=warFactionBase(e);if(id)targets.push({id,enemy:e,value:warSettlementValue(id),distance:warLocationDistance(base,id)})}}targets.sort((a,b)=>(b.value-b.distance*.35)-(a.value-a.distance*.35));return targets[0]||null}
function warCreateCampaign(w,f){const target=warChooseObjective(w,f);if(!target)return null;const C={id:`wc_${state.world.day}_${uid().slice(0,6)}`,warId:w.id,faction:f,enemyFaction:target.enemy,type:'offensive',name:`${worldLocation(target.id)?.name||target.id} Campaign`,objective:'capture',target:target.id,staging:warFactionBase(f),status:'forming',phase:'mobilizing',createdDay:state.world.day,lastPlanDay:state.world.day,lastProgressDay:state.world.day,formationIds:[],progress:0};warCampaigns(w).push(C);ensureWarFoundation().history.push({day:state.world.day,type:'campaign_started',warId:w.id,campaignId:C.id,text:`${majorFaction(f).short} begins the ${C.name}.`});return C}
function warEnsureCampaigns(){for(const w of activeWars()){for(const side of w.sides||[])for(const f of side.filter(warFactionEligible)){let C=warCampaigns(w).find(c=>c.faction===f&&['forming','active','stalled'].includes(c.status));const occupation=C&&typeof warOccupationAt==='function'?warOccupationAt(C.target):null,enemyControls=C?(warEnemiesForFaction(w,f).includes(settlementControl(C.target))||(occupation&&occupation.attackerFaction===f&&occupation.status!=='consolidated')):false;if(!C||!worldLocation(C.target)||!enemyControls){if(C&&C.status!=='completed'){C.status='completed';C.completedDay=state.world.day}C=warCreateCampaign(w,f)}if(C&&state.world.day-C.lastPlanDay>=10){const t=warChooseObjective(w,f);if(t&&t.id!==C.target){C.target=t.id;C.enemyFaction=t.enemy;C.name=`${worldLocation(t.id)?.name||t.id} Campaign`;C.lastPlanDay=state.world.day;C.phase='reorienting'}}}}}
function warMobilizationTarget(f,w){const M=warMilitaryState(f),support=clamp(M.warSupport||50,10,95);return clamp(1+Math.floor((support-35)/25),1,3)}
function warMobilizeForWars(){const W=ensureWarFoundation();for(const w of activeWars())for(const side of w.sides||[])for(const f of side.filter(warFactionEligible)){const M=warMilitaryState(f),field=warActiveFormations(f).filter(F=>F.warId===w.id&&F.role==='field'),desired=warMobilizationTarget(f,w);if(field.length<desired&&state.world.day-(M.lastMobilizedDay||0)>=3){const available=Math.max(0,M.manpowerReserve-M.mobilized);if(available>=30){const F=createWarFormation(f,{role:'field',status:'mobilizing',strength:Math.min(95,Math.max(45,Math.round(available*.28)))});if(F){F.warId=w.id;F.mobilizeUntil=state.world.day+Math.max(1,Math.round(4-(M.readiness||50)/35));M.lastMobilizedDay=state.world.day;W.history.push({day:state.world.day,type:'mobilization',warId:w.id,formationId:F.id,text:`${F.name} is called into field service.`})}}}for(const F of field)if(F.status==='mobilizing'&&state.world.day>=(F.mobilizeUntil||F.createdDay+2)){F.status='ready';F.lastActionDay=state.world.day}}}
function warAssignCampaignForces(){const W=ensureWarFoundation();for(const w of activeWars())for(const C of warCampaigns(w).filter(c=>['forming','active','stalled'].includes(c.status))){const live=new Set(warActiveFormations(C.faction).filter(F=>F.warId===w.id).map(F=>F.id));C.formationIds=(C.formationIds||[]).filter(id=>live.has(id));const available=warActiveFormations(C.faction).filter(F=>F.warId===w.id&&F.role==='field'&&!F.campaignId&&!F.retreating&&!['mobilizing','recovering','engaged','occupying'].includes(F.status));for(const F of available){F.campaignId=C.id;C.formationIds.push(F.id)}if(C.formationIds.length){C.status='active';if(['forming','reorienting'].includes(C.phase))C.phase='advancing'}}}
function warRegionRouteStep(from,to){if(!from||!to||from===to)return null;const ra=locationRegion(from),rb=locationRegion(to);if(ra===rb)return {next:to,days:Math.max(1,worldTravelDays(from,to)),kind:'regional'};const queue=[[ra,[]]],seen=new Set([ra]);let path=null;while(queue.length){const [r,p]=queue.shift();if(r===rb){path=p;break}for(const nr of connectedRegions(r)){if(seen.has(nr))continue;seen.add(nr);queue.push([nr,p.concat(nr)])}}if(!path?.length)return null;const nr=path[0],conn=regionConnectionForRegions(ra,nr);if(!conn)return null;const gateway=locationRegion(conn.a)===ra?conn.a:conn.b,other=gateway===conn.a?conn.b:conn.a;if(from!==gateway)return {next:gateway,days:Math.max(1,worldTravelDays(from,gateway)),kind:'gateway',connectionId:conn.id};return {next:other,days:Math.max(1,conn.days||worldTravelDays(from,other)),kind:'cross_region',connectionId:conn.id}}
function warIssueFormationOrders(){const W=ensureWarFoundation();for(const w of activeWars())for(const C of warCampaigns(w).filter(c=>c.status==='active')){for(const id of C.formationIds||[]){const F=W.formations.find(x=>x.id===id);if(!F||['destroyed','disbanded','mobilizing','awaiting_engagement','engaged','recovering','occupying'].includes(F.status)||F.retreating)continue;if(F.location===C.target){F.destination=null;F.routeStep=null;F.travelRemaining=0;F.status='holding';C.phase='at_objective';C.progress=Math.max(C.progress||0,75);continue}if(!F.destination||F.destination!==C.target||!F.routeStep){const step=warRegionRouteStep(F.location,C.target);if(!step){F.status='holding';continue}F.destination=C.target;F.routeStep=step.next;F.travelRemaining=step.days;F.routeKind=step.kind;F.status='marching';F.lastActionDay=state.world.day}}}}
function warAdvanceFormations(){const W=ensureWarFoundation();for(const F of warActiveFormations()){if(F.status!=='marching'||!F.routeStep)continue;F.fatigue=clamp((F.fatigue||0)+2,0,100);F.supplyDays=Math.max(0,(F.supplyDays||0)-1);F.travelRemaining=Math.max(0,(F.travelRemaining||1)-1);if(F.travelRemaining>0)continue;const old=F.location;F.location=F.routeStep;F.routeStep=null;F.lastActionDay=state.world.day;if(typeof addRoutePressure==='function')addRoutePressure(old,F.location,.35);W.history.push({day:state.world.day,type:'formation_move',formationId:F.id,warId:F.warId,text:`${F.name} reaches ${worldLocation(F.location)?.name||F.location}.`});if(F.location===F.destination){if(F.retreating){F.status='recovering';F.recoverUntil=state.world.day+2;F.routeStep=null}else{F.status='holding';const w=W.wars.find(x=>x.id===F.warId),C=w?.campaigns?.find(x=>x.id===F.campaignId);if(C){C.phase='at_objective';C.progress=Math.max(C.progress||0,75);C.lastProgressDay=state.world.day}}}}}
function warDetectContacts(){
 const W=ensureWarFoundation(),S=warStrategyState(),live=warActiveFormations(),byLoc=new Map();
 for(const F of live){if(!byLoc.has(F.location))byLoc.set(F.location,[]);byLoc.get(F.location).push(F)}
 for(const [loc,list] of byLoc){
  if(list.length<2)continue;
  for(let i=0;i<list.length;i++)for(let j=i+1;j<list.length;j++){
   const A=list[i],B=list[j],w=warBetween(A.faction,B.faction);if(!w)continue;
   const key=[A.id,B.id].sort().join('|');let c=S.contacts.find(x=>x.key===key&&x.status==='active');
   if(!c){c={id:`contact_${state.world.day}_${uid().slice(0,5)}`,key,warId:w.id,location:loc,a:A.id,b:B.id,day:state.world.day,status:'active'};S.contacts.push(c);W.history.push({day:state.world.day,type:'enemy_contact',warId:w.id,text:`Opposing formations make contact near ${worldLocation(loc)?.name||loc}. Battle has not yet been resolved.`})}
   A.status='awaiting_engagement';B.status='awaiting_engagement';A.contactId=c.id;B.contactId=c.id;
   for(const F of [A,B]){const C=w.campaigns?.find(x=>x.id===F.campaignId);if(C){C.phase='enemy_contact';C.status='stalled'}}
  }
 }
 S.contacts=S.contacts.filter(c=>c.status==='active'||state.world.day-(c.day||0)<30).slice(-60)
}
function warStrategicDailyTick(){const S=warStrategyState();if(S.lastTickDay===state.world.day)return;S.lastTickDay=state.world.day;const perf=(n,fn)=>typeof sosPerfRun==='function'?sosPerfRun(n,fn):fn();perf('War — Mobilization',()=>warMobilizeForWars());perf('War — Campaign Planning',()=>warEnsureCampaigns());perf('War — Formation Orders',()=>{warAssignCampaignForces();warIssueFormationOrders()});perf('War — Military Movement',()=>warAdvanceFormations());perf('War — Contact Detection',()=>warDetectContacts());S.lastPlanningDay=state.world.day}
function warCampaignCard(C,w){const target=worldLocation(C.target)?.name||C.target,forces=(C.formationIds||[]).map(id=>ensureWarFoundation().formations.find(F=>F.id===id)).filter(Boolean),strength=forces.reduce((n,F)=>n+(F.strength||0),0);return `<div class="card"><div class="stat-row"><span><b>${esc(C.name)}</b></span><b>${esc((C.phase||C.status).replaceAll('_',' '))}</b></div><small>${esc(majorFaction(C.faction).short)} • objective: ${esc(C.objective)} ${esc(target)}</small><div class="compact">Assigned formations ${forces.length} • ${fmt(strength)} effectives • campaign progress ${Math.round(C.progress||0)}%</div></div>`}
function warFormationStatusLabel(F){const labels={garrison:'Garrison',mobilizing:'Mobilizing',ready:'Ready',marching:'Marching',holding:'Holding',awaiting_engagement:'Enemy Contact',engaged:'In Battle',recovering:'Recovering',destroyed:'Destroyed',disbanded:'Disbanded'};return labels[F.status]||F.status||'Active'}
function warFormationCard(F){const loc=worldLocation(F.location)?.name||F.location||'Unknown',dest=F.destination&&F.destination!==F.location?worldLocation(F.destination)?.name||F.destination:null,c=F.composition||{};return `<div class="card"><div class="stat-row"><span><b>${esc(F.name)}</b></span><b>${fmt(F.strength)} effectives</b></div><small>${esc(majorFaction(F.faction).short)} • ${esc(warFormationStatusLabel(F))} • ${esc(loc)}${dest?` → ${esc(dest)}`:''}</small><div class="compact">Infantry ${c.infantry||0} • Ranged ${c.ranged||0} • Cavalry ${c.cavalry||0} • Officers ${c.officers||0}<br>Morale ${Math.round(F.morale||0)}% • Readiness ${Math.round(F.readiness||0)}% • Supply ${Math.round(F.supplyDays||0)} days${F.status==='marching'?` • ${Math.max(0,F.travelRemaining||0)}d to next waypoint`:''}</div></div>`}
function showWarOverview(){modalRouteEnter('showWarOverview',Array.from(arguments));const W=ensureWarFoundation(),wars=activeWars(),forces=warActiveFormations(),S=warStrategyState(),mil=WAR_MAJOR_FACTIONS.filter(warFactionEligible).map(f=>{const M=warMilitaryState(f),fs=forces.filter(x=>x.faction===f),active=fs.reduce((n,x)=>n+x.strength,0);return `<div class="stat-row"><span>${esc(majorFaction(f).short)}</span><b>${fmt(active)} active • ${fmt(Math.max(0,M.manpowerReserve-M.mobilized))} reserve • readiness ${Math.round(M.readiness)}%</b></div>`}).join('');const warHtml=wars.length?wars.map(w=>`<div class="card"><div class="stat-row"><span><b>${esc(w.name)}</b></span><b>Day ${w.startedDay}</b></div><small>${esc(w.cause)}</small><div class="compact">${w.sides.map(s=>s.map(f=>esc(majorFaction(f).short)).join(' + ')).join(' ↔ ')}</div></div>`).join(''):'<div class="notice compact"><b>No declared wars.</b><br>Regional powers maintain forces and readiness. Strategic mobilization begins automatically when a formal war starts.</div>';const campaigns=wars.flatMap(w=>warCampaigns(w).filter(c=>!['completed','cancelled'].includes(c.status)).map(c=>warCampaignCard(c,w))).join('');const contacts=S.contacts.filter(c=>c.status==='active').map(c=>{const A=W.formations.find(F=>F.id===c.a),B=W.formations.find(F=>F.id===c.b);return `<div class="warning notice compact"><b>Opposing forces in contact — ${esc(worldLocation(c.location)?.name||c.location)}</b><br>${esc(A?.name||'Formation')} ↔ ${esc(B?.name||'Formation')}<br><small>Battle resolution is intentionally reserved for the upcoming combat layer.</small></div>`}).join('');overlay(`<h2>War & Military Affairs</h2><p class="muted">Persistent military establishments now mobilize, establish campaign objectives, issue field orders, and march through the regional world. Battles are not yet resolved in this stage.</p><h3>Wars</h3>${warHtml}<h3>Active Campaigns</h3>${campaigns||'<p class="muted">No active military campaigns.</p>'}${contacts?`<h3>Enemy Contact</h3>${contacts}`:''}<h3>Military Balance</h3><div class="card">${mil}</div><h3>Known Formations</h3>${forces.map(warFormationCard).join('')||'<p class="muted">No formations recorded.</p>'}<div class="dialog-footer"><button id="warOverviewBack">Back</button></div>`,true);$('#warOverviewBack').onclick=()=>SOSServices.navigation.back(showWorldPolitics)}
