/* v1.6.66.1 — War Foundation & Military World Model */
const WAR_FOUNDATION_VERSION=1;
const WAR_MAJOR_FACTIONS=['Coalition','Redstone','Bluestone','Spawn','Shantium'];
function warState(){if(!state?.world)return null;let W=state.world.war;if(!W||typeof W!=='object')W=state.world.war={version:WAR_FOUNDATION_VERSION,wars:[],formations:[],military:{},intel:[],history:[],nextFormationSerial:1,lastTickDay:0,lastLifecycleDay:0};W.version=WAR_FOUNDATION_VERSION;if(!Array.isArray(W.wars))W.wars=[];if(!Array.isArray(W.formations))W.formations=[];if(!W.military||typeof W.military!=='object')W.military={};if(!Array.isArray(W.intel))W.intel=[];if(!Array.isArray(W.history))W.history=[];if(!Number.isFinite(W.nextFormationSerial))W.nextFormationSerial=1;return W}
function warFactionEligible(f){return WAR_MAJOR_FACTIONS.includes(f)&&OPEN_WORLD_FACTIONS[f]}
function warFactionSettlements(f){return (typeof settlementWorldLocations==='function'?settlementWorldLocations():WORLD_LOCATIONS.filter(x=>state.world.settlements?.[x.id])).filter(l=>settlementControl(l.id)===f)}
function warFactionBase(f){const held=warFactionSettlements(f);if(held.length)return held.sort((a,b)=>(settlementState(b.id)?.prosperity||0)-(settlementState(a.id)?.prosperity||0))[0].id;return 'shantium'}
function warMilitaryState(f){const W=warState();if(!W.military[f]){const held=warFactionSettlements(f),pop=held.reduce((n,l)=>n+(settlementState(l.id)?.population||100),0),base=Math.max(80,Math.round(pop*.055)+held.length*35);W.military[f]={faction:f,manpowerReserve:base,mobilized:0,casualties:0,prisoners:0,readiness:clamp(48+held.length*4,40,78),warSupport:clamp(52+(state.world.factionStanding?.[f]||0),30,80),exhaustion:0,treasuryPressure:0,lastMobilizedDay:0}}return W.military[f]}
function warFormationName(f,n){const ordinal=n===1?'1st':n===2?'2nd':n===3?'3rd':`${n}th`;return `${majorFaction(f).short} ${ordinal} Field Company`}
function createWarFormation(f,{location=null,strength=0,role='garrison',status='ready'}={}){const W=warState(),M=warMilitaryState(f),serial=W.nextFormationSerial++,size=strength||clamp(Math.round(M.manpowerReserve*.18),45,110),actual=Math.min(size,Math.max(0,M.manpowerReserve-M.mobilized));if(actual<20)return null;M.mobilized+=actual;const ranged=Math.round(actual*.22),cavalry=Math.round(actual*.08),officers=Math.max(2,Math.round(actual*.035)),infantry=Math.max(0,actual-ranged-cavalry-officers);const F={id:`wf_${state.world.day}_${serial}_${uid().slice(0,5)}`,faction:f,name:warFormationName(f,serial),createdDay:state.world.day,location:location||warFactionBase(f),destination:null,status,role,strength:actual,maxStrength:actual,composition:{infantry,ranged,cavalry,officers},morale:clamp(M.readiness+rnd(-5,5),35,90),readiness:M.readiness,supplyDays:rnd(7,13),fatigue:0,experience:0,equipment:clamp(62+M.readiness*.25+rnd(-5,5),50,90),commander:null,warId:null,campaignId:null,lastActionDay:state.world.day};W.formations.push(F);return F}
function ensureWarFoundation(){const W=warState();for(const f of WAR_MAJOR_FACTIONS)if(warFactionEligible(f))warMilitaryState(f);if(!W.initializedDay){W.initializedDay=state.world.day;for(const f of WAR_MAJOR_FACTIONS){if(!warFactionEligible(f)||W.formations.some(x=>x.faction===f))continue;createWarFormation(f,{role:'garrison',status:'garrison'})}W.history.push({day:state.world.day,type:'foundation',text:'Regional powers formalize military establishments as tensions are tracked across Sengia.'});W.history=W.history.slice(-80)}return W}
function activeWars(){return ensureWarFoundation().wars.filter(w=>w.status==='active')}
function warBetween(a,b){return activeWars().find(w=>{const ia=(w.sides||[]).findIndex(s=>s.includes(a)),ib=(w.sides||[]).findIndex(s=>s.includes(b));return ia>=0&&ib>=0&&ia!==ib})||null}
function declareWar(a,b,cause='Escalating political confrontation'){if(!warFactionEligible(a)||!warFactionEligible(b)||a===b)return null;const W=ensureWarFoundation(),existing=warBetween(a,b);if(existing)return existing;const w={id:`war_${state.world.day}_${uid().slice(0,6)}`,name:`${majorFaction(a).short}–${majorFaction(b).short} War`,startedDay:state.world.day,endedDay:null,status:'active',cause,sides:[[a],[b]],support:{[a]:warMilitaryState(a).warSupport,[b]:warMilitaryState(b).warSupport},exhaustion:{[a]:0,[b]:0},casualties:{[a]:0,[b]:0},captured:{[a]:0,[b]:0},occupiedSettlements:[],campaigns:[],lastMajorEventDay:state.world.day};W.wars.push(w);for(const f of [a,b]){let force=W.formations.find(x=>x.faction===f&&!x.warId);if(!force)force=createWarFormation(f,{role:'field',status:'mobilizing'});if(force){force.warId=w.id;force.role='field';force.status='mobilizing'}warMilitaryState(f).lastMobilizedDay=state.world.day}W.history.push({day:state.world.day,type:'war_declared',warId:w.id,text:`War begins between ${majorFaction(a).short} and ${majorFaction(b).short}: ${cause}.`});recordWorldHistory(`WAR: ${majorFaction(a).short} and ${majorFaction(b).short} enter open conflict. ${cause}.`,'bad','war');return w}
function warTension(a,b){const rel=factionRelation(a,b);return clamp((-rel)*16,0,100)}
function warFoundationPoliticalCheck(){const W=ensureWarFoundation();for(let i=0;i<WAR_MAJOR_FACTIONS.length;i++)for(let j=i+1;j<WAR_MAJOR_FACTIONS.length;j++){const a=WAR_MAJOR_FACTIONS[i],b=WAR_MAJOR_FACTIONS[j];if(!warFactionEligible(a)||!warFactionEligible(b)||warBetween(a,b))continue;const t=warTension(a,b);if(factionRelation(a,b)<=-5&&t>=80&&state.world.day-(W.lastDeclarationDay||0)>=30&&chance(.035)){declareWar(a,b,'Relations collapse after sustained political hostility');W.lastDeclarationDay=state.world.day;return}}}
function warFoundationDailyTick(){const W=ensureWarFoundation();if(W.lastTickDay===state.world.day)return;W.lastTickDay=state.world.day;const perf=(n,fn)=>typeof sosPerfRun==='function'?sosPerfRun(n,fn):fn();perf('War — Political State',()=>warFoundationPoliticalCheck());perf('War — Military Readiness',()=>{const wars=activeWars();for(const f of WAR_MAJOR_FACTIONS){if(!warFactionEligible(f))continue;const M=warMilitaryState(f),atWar=wars.some(w=>w.sides.flat().includes(f));M.readiness=clamp(M.readiness+(atWar?.18:.04)-M.exhaustion*.001,35,95);M.warSupport=clamp(M.warSupport-(atWar?M.exhaustion*.0008:0),10,95)}});perf('War — Formation Lifecycle',()=>{for(const F of W.formations){if(F.status==='destroyed'||F.status==='disbanded')continue;F.strength=Math.max(0,Math.round(F.strength));if(F.strength<=0){F.status='destroyed';F.destroyedDay=state.world.day}}if(state.world.day%14===0){W.formations=W.formations.filter(F=>!['destroyed','disbanded'].includes(F.status)||state.world.day-(F.destroyedDay||F.disbandedDay||state.world.day)<45);W.history=W.history.slice(-100);W.intel=W.intel.filter(i=>state.world.day-(i.day||0)<60)}});W.lastLifecycleDay=state.world.day}
function warFormationStatusLabel(F){return F.status==='garrison'?'Garrison':F.status==='mobilizing'?'Mobilizing':F.status==='ready'?'Ready':F.status==='destroyed'?'Destroyed':F.status||'Active'}
function warFormationCard(F){const loc=worldLocation(F.location)?.name||F.location||'Unknown',c=F.composition||{};return `<div class="card"><div class="stat-row"><span><b>${esc(F.name)}</b></span><b>${fmt(F.strength)} effectives</b></div><small>${esc(majorFaction(F.faction).short)} • ${esc(warFormationStatusLabel(F))} • ${esc(loc)}</small><div class="compact">Infantry ${c.infantry||0} • Ranged ${c.ranged||0} • Cavalry ${c.cavalry||0} • Officers ${c.officers||0}<br>Morale ${Math.round(F.morale||0)}% • Readiness ${Math.round(F.readiness||0)}% • Supply ${Math.round(F.supplyDays||0)} days</div></div>`}
function showWarOverview(){modalRouteEnter('showWarOverview',Array.from(arguments));const W=ensureWarFoundation(),wars=activeWars(),forces=W.formations.filter(F=>!['destroyed','disbanded'].includes(F.status)),mil=WAR_MAJOR_FACTIONS.filter(warFactionEligible).map(f=>{const M=warMilitaryState(f),fs=forces.filter(x=>x.faction===f),active=fs.reduce((n,x)=>n+x.strength,0);return `<div class="stat-row"><span>${esc(majorFaction(f).short)}</span><b>${fmt(active)} active • ${fmt(Math.max(0,M.manpowerReserve-M.mobilized))} reserve • readiness ${Math.round(M.readiness)}%</b></div>`}).join('');const warHtml=wars.length?wars.map(w=>`<div class="card"><div class="stat-row"><span><b>${esc(w.name)}</b></span><b>Day ${w.startedDay}</b></div><small>${esc(w.cause)}</small><div class="compact">${w.sides.map(s=>s.map(f=>esc(majorFaction(f).short)).join(' + ')).join(' ↔ ')}</div></div>`).join(''):'<div class="notice compact"><b>No declared wars.</b><br>Regional powers maintain forces and military readiness, but no major powers are presently in formal open conflict.</div>';overlay(`<h2>War & Military Affairs</h2><p class="muted">Regional military establishments, declared wars, and known formations. This foundation tracks persistent forces; campaigning and battlefield movement will build on these records.</p><h3>Wars</h3>${warHtml}<h3>Military Balance</h3><div class="card">${mil}</div><h3>Known Formations</h3>${forces.map(warFormationCard).join('')||'<p class="muted">No formations recorded.</p>'}<div class="dialog-footer"><button id="warOverviewBack">Back</button></div>`,true);$('#warOverviewBack').onclick=()=>SOSServices.navigation.back(showWorldPolitics)}
(function installWarFoundationUI(){if(typeof showWorldPolitics==='function'){const base=showWorldPolitics;showWorldPolitics=function(){const r=base.apply(this,arguments),footer=document.querySelector('.dialog-footer');if(footer&&!document.getElementById('worldWarOverview')){const b=document.createElement('button');b.id='worldWarOverview';b.textContent='War & Military';b.onclick=showWarOverview;footer.insertBefore(b,footer.firstChild)}return r}}})();
