/* v1.6.66.8.1 — Guardian Hall War Notification Network */
const WAR_NOTIFICATION_VERSION=1;
function warNotificationState(){const W=ensureWarFoundation();if(!W.notifications||typeof W.notifications!=="object")W.notifications={version:WAR_NOTIFICATION_VERSION,records:[],lastTickDay:0};const N=W.notifications;N.version=WAR_NOTIFICATION_VERSION;if(!Array.isArray(N.records))N.records=[];return N}
function warNotificationRecord(w){return warNotificationState().records.find(n=>n.warId===w?.id)||null}
function warNotificationMessengerStrength(){if(typeof ensureHomeBase!=="function")return 0;ensureHomeBase();return Math.max(0,state.world.homeBase.staff?.messengers||0)}
function warNotificationQueue(w){if(!w||warNotificationRecord(w))return;const N=warNotificationState(),m=warNotificationMessengerStrength(),hallDelay=m>=6?1:m>=3?2:3;N.records.push({warId:w.id,declaredDay:w.startedDay||state.world.day,hallDueDay:state.world.day+hallDelay,hallAwareDay:null,guardianDueDay:null,guardianKnownDay:null,method:null,status:"watching"});if(typeof homeStaffReport==="function")homeStaffReport(`Standing wartime watch activated: Hall messengers are to listen for confirmation of the ${w.name} while carrying out their normal assignments.`,"info")}
function warGuardianAtHall(){return state.world?.location==="shantium"&&!(state.world?.travel&&state.world.travel.active)}
function warNotificationCourierDays(){const loc=state.world?.location||"shantium";if(loc==="shantium")return 0;let d=3;try{if(typeof tradeRouteDistanceDays==="function")d=tradeRouteDistanceDays("shantium",loc);else if(typeof worldTravelDays==="function")d=worldTravelDays("shantium",loc)}catch(e){}if(!Number.isFinite(d)||d>=90)d=6;return Math.max(1,Math.ceil(d*.55))}
function warNotificationHallReceive(n,w){n.hallAwareDay=state.world.day;n.status="hall_received";if(typeof homeStaffReport==="function")homeStaffReport(`WAR CONFIRMED: ${w.name}. Messengers have delivered verified notice to Guardian Hall. Priority riders are ordered to find the Guardian immediately.`,"bad");if(warGuardianAtHall()){n.guardianDueDay=state.world.day;n.method="Hall messengers"}else if(typeof crystalRemoteAvailable==="function"&&crystalRemoteAvailable()){n.guardianDueDay=state.world.day;n.method="Steward via Sending Crystal"}else{n.guardianDueDay=state.world.day+warNotificationCourierDays();n.method="priority Hall messenger"}recordWorldHistory(`Guardian Hall receives confirmed word of the ${w.name} and dispatches an official notice to the Guardian.`,"bad","war")}
function warNotificationDeliver(n,w){if(n.guardianKnownDay!=null)return;n.guardianKnownDay=state.world.day;n.status="delivered";const crystal=n.method==="Steward via Sending Crystal";n.alertPending=true;n.alertTitle="War Declared";n.alertText=crystal?`${state.world.homeBase.staff.steward.name} reaches you through the Sending Crystal with verified news from Hall messengers: ${w.name} has begun. ${w.cause}.`:`A Guardian Hall messenger reaches you with official confirmation: ${w.name} has begun. ${w.cause}.`;recordWorldHistory(`The Guardian is officially notified of the ${w.name} by ${n.method}.`,"bad","war");if(typeof homeStaffReport==="function")homeStaffReport(`The Guardian was officially notified of the ${w.name} by ${n.method}.`,"good")}
function warNotificationDailyTick(){const N=warNotificationState();if(N.lastTickDay===state.world.day)return;N.lastTickDay=state.world.day;for(const w of ensureWarFoundation().wars)if(w.status==="active"&&!warNotificationRecord(w))warNotificationQueue(w);for(const n of N.records){const w=ensureWarFoundation().wars.find(x=>x.id===n.warId);if(!w)continue;if(n.hallAwareDay==null&&state.world.day>=n.hallDueDay)warNotificationHallReceive(n,w);if(n.hallAwareDay!=null&&n.guardianKnownDay==null&&state.world.day>=n.guardianDueDay)warNotificationDeliver(n,w)}N.records=N.records.filter(n=>n.guardianKnownDay==null||state.world.day-n.guardianKnownDay<180).slice(-80)}
function warNotificationShowPending(){const n=warNotificationState().records.find(x=>x.alertPending);if(!n)return false;n.alertPending=false;const w=ensureWarFoundation().wars.find(x=>x.id===n.warId);if(typeof playSoundtrackTrackByTitle==="function")playSoundtrackTrackByTitle("The Bells of War",{returnToRotation:true});else if(typeof sfxWorld==="function")sfxWorld("politics");actionResult(n.alertTitle||"War Declared",n.alertText||`Guardian Hall confirms that ${w?.name||"a war"} has begun.`,"bad",renderOpenWorld);save();return true}
const __declareWarNotification=declareWar;declareWar=function(){const w=__declareWarNotification.apply(this,arguments);if(w)warNotificationQueue(w);return w};
const __warStrategicDailyTickNotification=warStrategicDailyTick;warStrategicDailyTick=function(){const out=__warStrategicDailyTickNotification.apply(this,arguments),perf=(n,fn)=>typeof sosPerfRun==="function"?sosPerfRun(n,fn):fn();perf("War — Hall Notification",()=>warNotificationDailyTick());return out};
const __renderOpenWorldWarNotification=renderOpenWorld;renderOpenWorld=function(){const r=__renderOpenWorldWarNotification.apply(this,arguments);if(warNotificationState().records.some(x=>x.alertPending))setTimeout(()=>warNotificationShowPending(),0);return r};
