/* v1.6.66.7 — POWs & Wartime Custody */
const WAR_POW_VERSION=1;
function warPowState(){
 const W=ensureWarFoundation();
 if(!W.pow||typeof W.pow!=='object')W.pow={version:WAR_POW_VERSION,lastTickDay:0,batches:[],specialCaptives:[],history:[],nextSerial:1};
 const P=W.pow;P.version=WAR_POW_VERSION;if(!Array.isArray(P.batches))P.batches=[];if(!Array.isArray(P.specialCaptives))P.specialCaptives=[];if(!Array.isArray(P.history))P.history=[];if(!Number.isFinite(P.nextSerial))P.nextSerial=1;return P
}
function warPowActiveBatches(){return warPowState().batches.filter(x=>x.count>0&&x.status==='held')}
function warPowHeldCount(holder=null,origin=null,warId=null){return warPowActiveBatches().filter(x=>(!holder||x.holderFaction===holder)&&(!origin||x.originFaction===origin)&&(!warId||x.warId===warId)).reduce((n,x)=>n+(x.count||0),0)}
function warPowCreateBatch({warId,holderFaction,originFaction,count,location=null,source='Field capture',battleId=null,operationId=null}={}){
 count=Math.max(0,Math.round(count||0));if(!count||!holderFaction||!originFaction||holderFaction===originFaction)return null;
 const P=warPowState(),existing=P.batches.find(x=>x.status==='held'&&x.warId===warId&&x.holderFaction===holderFaction&&x.originFaction===originFaction&&x.location===location&&state.world.day-(x.lastIntakeDay||x.capturedDay||0)<=2);
 if(existing){existing.count+=count;existing.lastIntakeDay=state.world.day;existing.intakes=(existing.intakes||0)+1;return existing}
 const B={id:`pow_${state.world.day}_${P.nextSerial++}_${uid().slice(0,4)}`,warId:warId||null,holderFaction,originFaction,count,capturedDay:state.world.day,lastIntakeDay:state.world.day,location:location||warFactionBase(holderFaction),source,battleId:battleId||null,operationId:operationId||null,status:'held',transferredToHall:0,exchanged:0,repatriated:0,ransomed:0,paroled:0};
 P.batches.push(B);P.history.push({day:state.world.day,type:'capture',batchId:B.id,warId:B.warId,text:`${majorFaction(holderFaction).short} takes custody of ${count} ${majorFaction(originFaction).short} prisoner${count===1?'':'s'} of war.`});
 return B
}
function warPowCaptureCommander(F,holderFaction,warId,location,sourceRef){
 if(!F?.commander||F.commanderCaptured)return null;const name=typeof F.commander==='string'?F.commander:(F.commander.name||F.commander.title);if(!name)return null;
 const P=warPowState(),S={id:`pow_special_${state.world.day}_${uid().slice(0,5)}`,warId,holderFaction,originFaction:F.faction,name,role:'Field commander',formationId:F.id,location,capturedDay:state.world.day,status:'held',sourceRef};P.specialCaptives.push(S);F.commanderCaptured=true;F.commander=null;P.history.push({day:state.world.day,type:'special_capture',specialId:S.id,warId,text:`${name}, commander of ${F.name}, is taken prisoner by ${majorFaction(holderFaction).short}.`});return S
}
function warPowDistributeBattleCaptives(B){
 if(!B||B.powProcessed)return;B.powProcessed=true;const W=ensureWarFoundation(),w=W.wars.find(x=>x.id===B.warId);if(!w)return;
 for(let side=0;side<2;side++){
  const count=Math.max(0,Math.round(B.casualties?.[side]?.captured||0));if(!count)continue;const originFactions=w.sides?.[side]||[],holderFactions=w.sides?.[side===0?1:0]||[];if(!originFactions.length||!holderFactions.length)continue;
  const holder=holderFactions[0],forces=warBattleSideFormations(B,side),weights=new Map();for(const F of forces)weights.set(F.faction,(weights.get(F.faction)||0)+Math.max(1,F.maxStrength||F.strength||1));const totalWeight=[...weights.values()].reduce((n,x)=>n+x,0)||originFactions.length;
  let left=count;for(let i=0;i<originFactions.length;i++){const f=originFactions[i],share=i===originFactions.length-1?left:Math.min(left,Math.max(0,Math.round(count*((weights.get(f)||1)/totalWeight))));left-=share;if(share)warPowCreateBatch({warId:B.warId,holderFaction:holder,originFaction:f,count:share,location:B.location,source:`Battle near ${worldLocation(B.location)?.name||B.location}`,battleId:B.id})}
  if(count>=2)for(const F of forces.filter(x=>x.commander))if(chance(Math.min(.55,.08+count/Math.max(20,F.maxStrength||F.strength||20))))warPowCaptureCommander(F,holder,B.warId,B.location,B.id)
 }
}
const __warBattleEndPow=warBattleEnd;warBattleEnd=function(B,winnerSide){const out=__warBattleEndPow.apply(this,arguments);warPowDistributeBattleCaptives(B);return out};
const __warTerritorialCapturePow=warTerritorialCapture;warTerritorialCapture=function(O,w,C,forces){const out=__warTerritorialCapturePow.apply(this,arguments),captured=Math.max(0,Math.round((O?.losses?.defender||0)*.18));if(captured&&O?.defenderFaction&&O?.attackerFaction){warPowCreateBatch({warId:O.warId,holderFaction:O.attackerFaction,originFaction:O.defenderFaction,count:captured,location:O.location,source:`Fall of ${worldLocation(O.location)?.name||O.location}`,operationId:O.id});w.captured[O.defenderFaction]=(w.captured[O.defenderFaction]||0)+captured;warMilitaryState(O.defenderFaction).prisoners=(warMilitaryState(O.defenderFaction).prisoners||0)+captured}return out};
function warPowBatchChange(B,amount,field,status){amount=Math.min(B.count,Math.max(0,Math.round(amount||0)));if(!amount)return 0;B.count-=amount;B[field]=(B[field]||0)+amount;if(B.count<=0){B.count=0;B.status=status}return amount}
function warPowExchangeTick(){
 const P=warPowState();for(const w of activeWars()){
  const batches=warPowActiveBatches().filter(x=>x.warId===w.id&&state.world.day-(x.capturedDay||0)>=7);if(batches.length<2)continue;
  for(const A of batches){if(A.count<=0)continue;const reciprocal=batches.find(B=>B.count>0&&B.holderFaction===A.originFaction&&B.originFaction===A.holderFaction);if(!reciprocal||A.id===reciprocal.id||!chance(.035))continue;const n=Math.min(A.count,reciprocal.count,Math.max(1,rnd(3,12)));warPowBatchChange(A,n,'exchanged','exchanged');warPowBatchChange(reciprocal,n,'exchanged','exchanged');P.history.push({day:state.world.day,type:'exchange',warId:w.id,text:`${n} prisoners from each side are exchanged between ${majorFaction(A.holderFaction).short} and ${majorFaction(A.originFaction).short}.`});ensureWarFoundation().history.push({day:state.world.day,type:'pow_exchange',warId:w.id,text:`A wartime prisoner exchange returns ${n} captives to each side.`});break}
 }
}
function warPowPostwarRepatriationTick(){
 const P=warPowState();for(const B of warPowActiveBatches()){
  const w=ensureWarFoundation().wars.find(x=>x.id===B.warId);if(!w||w.status==='active'||state.world.day-(w.endedDay||state.world.day)<2)continue;if(!chance(.35))continue;const n=warPowBatchChange(B,B.count,'repatriated','repatriated');if(n)P.history.push({day:state.world.day,type:'repatriation',warId:B.warId,text:`${n} ${majorFaction(B.originFaction).short} prisoners are repatriated from ${majorFaction(B.holderFaction).short} custody after the war.`})
 }
 for(const S of P.specialCaptives.filter(x=>x.status==='held')){const w=ensureWarFoundation().wars.find(x=>x.id===S.warId);if(w&&w.status!=='active'&&state.world.day-(w.endedDay||state.world.day)>=3&&chance(.2)){S.status='repatriated';S.releasedDay=state.world.day;P.history.push({day:state.world.day,type:'special_repatriation',warId:S.warId,text:`${S.name} is repatriated after the war.`})}}
}
function warPowHallEligibility(B){if(!B||B.status!=='held'||B.count<=0||!canAccessGuardianHall())return false;const standing=state.world.factionStanding?.[B.holderFaction]||0;return B.holderFaction==='Shantium'||standing>=8}
function warPowHallRoom(){return Math.max(0,homePrisonerCapacity()-hallPrisonerCount())}
function warPowTransferToHall(id){
 const B=warPowState().batches.find(x=>x.id===id);if(!warPowHallEligibility(B))return showWarPowCustody();const room=warPowHallRoom(),take=Math.min(B.count,room);if(take<=0)return actionResult('Guardian Hall Is Full','There is no secure capacity available for an additional wartime custodial transfer.','info',showWarPowCustody);
 const p={id:uid(),faction:B.originFaction,count:take,round:state.world.day,questioned:true,captureIntelDone:true,source:`Wartime custodial transfer from ${majorFaction(B.holderFaction).short}`,world:true,hallCustody:true,hallLabor:false,wartimePow:true,warId:B.warId,powBatchId:B.id,specialCustody:false};state.prisoners.push(p);if(typeof ensurePrisonerCustodyIII==='function')ensurePrisonerCustodyIII(p);if(typeof homePrisonerRecordAdmission==='function')homePrisonerRecordAdmission(p,false);warPowBatchChange(B,take,'transferredToHall','guardian_transferred');warPowState().history.push({day:state.world.day,type:'hall_transfer',batchId:B.id,warId:B.warId,text:`Guardian Hall accepts custody of ${take} ${majorFaction(B.originFaction).short} prisoner${take===1?'':'s'} transferred by ${majorFaction(B.holderFaction).short}.`});recordWorldHistory(`Guardian Hall accepts wartime custody of ${take} ${majorFaction(B.originFaction).short} prisoner${take===1?'':'s'}.`,'info','home');save();showWarPowCustody()
}
function warPowTransferSpecialToHall(id){
 const S=warPowState().specialCaptives.find(x=>x.id===id);if(!S||S.status!=='held'||!canAccessGuardianHall()||warPowHallRoom()<1)return showWarPowCustody();const standing=state.world.factionStanding?.[S.holderFaction]||0;if(S.holderFaction!=='Shantium'&&standing<8)return showWarPowCustody();const p={id:uid(),faction:S.originFaction,count:1,round:state.world.day,questioned:true,captureIntelDone:true,source:`Wartime transfer: ${S.name}`,world:true,hallCustody:true,hallLabor:false,wartimePow:true,warId:S.warId,powSpecialId:S.id,specialCustody:true,namedPersonNames:[S.name]};state.prisoners.push(p);if(typeof ensurePrisonerCustodyIII==='function')ensurePrisonerCustodyIII(p);if(typeof homePrisonerRecordAdmission==='function')homePrisonerRecordAdmission(p,false);S.status='guardian_hall';S.transferredDay=state.world.day;S.hallPrisonerId=p.id;warPowState().history.push({day:state.world.day,type:'special_hall_transfer',specialId:S.id,warId:S.warId,text:`Guardian Hall accepts custody of ${S.name}.`});recordWorldHistory(`Guardian Hall accepts wartime custody of ${S.name}, a captured ${majorFaction(S.originFaction).short} commander.`,'info','home');save();showWarPowCustody()
}
function warPowHallGroups(){
 const m=new Map();for(const p of (state.prisoners||[]).filter(x=>x.hallCustody&&x.wartimePow&&!x.specialCustody)){const k=`${p.warId||''}|${p.faction||'Unknown'}`,g=m.get(k)||{warId:p.warId||null,originFaction:p.faction||'Unknown',count:0,ids:[]};g.count+=Math.max(1,p.count||1);g.ids.push(p.id);m.set(k,g)}return [...m.values()].sort((a,b)=>b.count-a.count)
}
function warPowParoleHallGroup(warId,originFaction){
 if(!canAccessGuardianHall())return showWarPowCustody();const rows=(state.prisoners||[]).filter(p=>p.hallCustody&&p.wartimePow&&!p.specialCustody&&(p.warId||null)===(warId||null)&&(p.faction||'Unknown')===originFaction);if(!rows.length)return showWarPowCustody();const ids=new Set(rows.map(x=>x.id)),count=rows.reduce((n,x)=>n+Math.max(1,x.count||1),0);if(typeof homePrisonerPopulationDepartureHistory==='function')homePrisonerPopulationDepartureHistory(rows,'release');state.prisoners=state.prisoners.filter(x=>!ids.has(x.id));if(state.world.factionStanding?.[originFaction]!=null)state.world.factionStanding[originFaction]+=Math.max(1,Math.min(4,Math.round(count/8)));const w=ensureWarFoundation().wars.find(x=>x.id===warId);if(w&&w.support?.[originFaction]!=null)w.support[originFaction]=clamp((w.support[originFaction]||50)+1,0,100);warPowState().history.push({day:state.world.day,type:'parole',warId,originFaction,text:`Guardian Hall paroles ${count} ${majorFaction(originFaction).short} prisoner${count===1?'':'s'} of war on promise of non-hostile return.`});recordWorldHistory(`Guardian Hall paroles ${count} ${majorFaction(originFaction).short} wartime captive${count===1?'':'s'} and releases them from custody.`,'good','home');save();showWarPowCustody()
}
function warPowHallGroupCard(G){return `<div class="card compact"><div class="stat-row"><span><b>Guardian Hall custody</b></span><b>${fmt(G.count)} POW${G.count===1?'':'s'}</b></div>${esc(majorFaction(G.originFaction).short)} personnel${G.warId?` • wartime custody`:''}<div class="prisoner-actions"><button data-powparole="${esc(G.warId||'')}|${esc(G.originFaction)}">Parole Population</button><button data-powhallmanage="1">Open Hall Prisoner Management</button></div></div>`}
function warPowDailyTick(){const P=warPowState();if(P.lastTickDay===state.world.day)return;P.lastTickDay=state.world.day;warPowExchangeTick();warPowPostwarRepatriationTick();P.batches=P.batches.filter(x=>x.status==='held'||state.world.day-(x.capturedDay||state.world.day)<120).slice(-100);P.specialCaptives=P.specialCaptives.filter(x=>x.status==='held'||x.status==='guardian_hall'||state.world.day-(x.capturedDay||state.world.day)<180).slice(-50);P.history=P.history.slice(-140)}
const __warStrategicDailyTickPow=warStrategicDailyTick;warStrategicDailyTick=function(){const out=__warStrategicDailyTickPow.apply(this,arguments),perf=(n,fn)=>typeof sosPerfRun==='function'?sosPerfRun(n,fn):fn();perf('War — POW Custody',()=>warPowDailyTick());return out};
function warPowBatchCard(B){const loc=worldLocation(B.location)?.name||B.location||'Unknown',age=Math.max(0,state.world.day-(B.capturedDay||state.world.day)),can=warPowHallEligibility(B),room=warPowHallRoom();return `<div class="card compact"><div class="stat-row"><span><b>${esc(majorFaction(B.holderFaction).short)} custody</b></span><b>${fmt(B.count)} POW${B.count===1?'':'s'}</b></div>${esc(majorFaction(B.originFaction).short)} personnel • ${esc(loc)} • held ${age}d<br><small>${esc(B.source||'Wartime capture')}${B.exchanged?` • ${B.exchanged} exchanged`:''}${B.transferredToHall?` • ${B.transferredToHall} transferred to Hall`:''}</small>${can?`<div class="prisoner-actions"><button data-powhall="${esc(B.id)}" ${room?'':'disabled'}>Accept Custodial Transfer${room&&room<B.count?` (${room} spaces)`:''}</button></div>`:''}</div>`}
function warPowSpecialCard(S){const can=canAccessGuardianHall()&&(S.holderFaction==='Shantium'||(state.world.factionStanding?.[S.holderFaction]||0)>=8)&&warPowHallRoom()>0;return `<div class="card compact"><div class="stat-row"><span><b>${esc(S.name)}</b></span><b>${esc(S.status.replaceAll('_',' '))}</b></div>${esc(S.role)} • ${esc(majorFaction(S.originFaction).short)} • held by ${esc(majorFaction(S.holderFaction).short)}${can&&S.status==='held'?`<div class="prisoner-actions"><button data-powspecialhall="${esc(S.id)}">Transfer to Guardian Hall</button></div>`:''}</div>`}
function showWarPowCustody(){
 modalRouteEnter('showWarPowCustody',Array.from(arguments));const P=warPowState(),held=warPowActiveBatches(),special=P.specialCaptives.filter(x=>['held','guardian_hall'].includes(x.status)),hallGroups=warPowHallGroups(),total=held.reduce((n,x)=>n+x.count,0),hall=(state.prisoners||[]).filter(x=>x.hallCustody&&x.wartimePow).reduce((n,x)=>n+(x.count||1),0),recent=P.history.slice(-12).reverse().map(x=>`<div class="compact"><b>Day ${x.day}</b> — ${esc(x.text)}</div>`).join('');
 overlay(`<h2>Prisoners of War & Wartime Custody</h2><div class="notice compact"><b>${fmt(total)} ordinary POWs remain in faction custody.</b><br>${fmt(hall)} wartime captive${hall===1?' is':'s are'} presently held at Guardian Hall. Ordinary soldiers are tracked as populations; commanders and other exceptional captives remain individual records.</div><h3>Custody Populations</h3>${held.map(warPowBatchCard).join('')||'<p class="muted">No ordinary prisoners of war are currently recorded in faction custody.</p>'}<h3>Guardian Hall Wartime Custody</h3>${hallGroups.map(warPowHallGroupCard).join('')||'<p class="muted">No ordinary prisoners of war are currently held at Guardian Hall.</p>'}<h3>Special Captives</h3>${special.map(warPowSpecialCard).join('')||'<p class="muted">No individually tracked wartime captives.</p>'}<h3>Recent Custody History</h3>${recent||'<p class="muted">No wartime custody history yet.</p>'}<div class="notice compact muted">Reciprocal faction-held POW populations can be exchanged during prolonged wars. Remaining faction-held prisoners are gradually repatriated after peace. Prisoners accepted into Guardian Hall become part of the Hall's normal capacity, security, work-crew, exchange, ransom, release, and handover systems.</div><div class="dialog-footer"><button id="warPowBack">Back to War & Military Affairs</button></div>`,true);
 document.querySelectorAll('[data-powhall]').forEach(b=>b.onclick=()=>warPowTransferToHall(b.dataset.powhall));document.querySelectorAll('[data-powspecialhall]').forEach(b=>b.onclick=()=>warPowTransferSpecialToHall(b.dataset.powspecialhall));document.querySelectorAll('[data-powparole]').forEach(b=>b.onclick=()=>{const [warId,...rest]=b.dataset.powparole.split('|');warPowParoleHallGroup(warId||null,rest.join('|'))});document.querySelectorAll('[data-powhallmanage]').forEach(b=>b.onclick=showHomePrisoners);$('#warPowBack').onclick=()=>SOSServices.navigation.back(showWarOverview)
}
const __showWarOverviewPow=showWarOverview;showWarOverview=function(){const r=__showWarOverviewPow.apply(this,arguments),dlg=document.querySelector('.dialog');if(!dlg)return r;const footer=dlg.querySelector('.dialog-footer');if(footer&&!document.getElementById('warPowOpen')){const held=warPowHeldCount(),special=warPowState().specialCaptives.filter(x=>x.status==='held').length,wrap=document.createElement('div');wrap.innerHTML=`<h3>Prisoners of War</h3><div class="card compact"><div class="stat-row"><span>Faction-held ordinary POWs</span><b>${fmt(held)}</b></div><div class="stat-row"><span>Individually tracked captives</span><b>${fmt(special)}</b></div><button id="warPowOpen">POWs & Wartime Custody</button></div>`;while(wrap.firstChild)dlg.insertBefore(wrap.firstChild,footer);const b=document.getElementById('warPowOpen');if(b)b.onclick=showWarPowCustody}return r};
