function politicalCampaignMomentumLabel(v){return v>=6?'Surging':v>=3?'Strong':v>=1?'Building':v<=-4?'Badly stalled':v<=-1?'Stalled':SOSText("politics_campaigns_civic.politicalCampaignMomentumLabel.001")}
function politicalCampaignNeed(locId,faction){
 const p=localPoliticalProfile(locId,faction),rival=localPoliticalRival(locId,faction),rp=rival?localPoliticalProfile(locId,rival):null,ps=politicalSettlement(locId),control=settlementControl(locId);
 if(ps.pending?.challenger&&ps.pending.challenger!==faction)return {metric:'counter',label:SOSText("politics_campaigns_civic.politicalCampaignNeed.001",majorFaction(ps.pending.challenger).short),rival:ps.pending.challenger,reason:SOSText("politics_campaigns_civic.politicalCampaignNeed.002",majorFaction(ps.pending.challenger).short)};
 if(rival&&rp&&(rp.overall>=p.overall-3||settlementLeanScore(locId,rival)>=settlementLeanScore(locId,faction)-1))return {metric:'counter',label:SOSText("politics_campaigns_civic.politicalCampaignNeed.003",majorFaction(rival).short),rival,reason:SOSText("politics_campaigns_civic.politicalCampaignNeed.004",majorFaction(rival).short,majorFaction(faction).short)};
 const deficits=[
  {metric:'legitimacy',label:SOSText("politics_campaigns_civic.politicalCampaignNeed.005"),score:62-p.legitimacy,reason:SOSText("politics_campaigns_civic.politicalCampaignNeed.006")},
  {metric:'support',label:SOSText("politics_campaigns_civic.politicalCampaignNeed.007"),score:60-p.publicSupport,reason:SOSText("politics_campaigns_civic.politicalCampaignNeed.008")},
  {metric:'organization',label:SOSText("politics_campaigns_civic.politicalCampaignNeed.009"),score:58-p.organization,reason:SOSText("politics_campaigns_civic.politicalCampaignNeed.010")},
  {metric:'merchant',label:SOSText("politics_campaigns_civic.politicalCampaignNeed.011"),score:52-p.merchantBacking,reason:SOSText("politics_campaigns_civic.politicalCampaignNeed.012")},
  {metric:'security',label:SOSText("politics_campaigns_civic.politicalCampaignNeed.013"),score:52-p.securityInfluence,reason:SOSText("politics_campaigns_civic.politicalCampaignNeed.014")}
 ].sort((a,b)=>b.score-a.score);
 const need=deficits[0];need.rival=rival;if(control===faction&&p.legitimacy<55){need.metric='legitimacy';need.label=SOSText("politics_campaigns_civic.politicalCampaignNeed.015");need.reason=SOSText("politics_campaigns_civic.politicalCampaignNeed.016")}return need
}
const POLITICAL_CAMPAIGN_NAMES={
 Redstone:{support:SOSText("politics_campaigns_civic.politicalCampaignNeed.017"),organization:SOSText("politics_campaigns_civic.politicalCampaignNeed.018"),legitimacy:SOSText("politics_campaigns_civic.politicalCampaignNeed.019"),merchant:SOSText("politics_campaigns_civic.politicalCampaignNeed.020"),security:SOSText("politics_campaigns_civic.politicalCampaignNeed.021"),counter:SOSText("politics_campaigns_civic.politicalCampaignNeed.022")},
 Independent:{support:SOSText("politics_campaigns_civic.politicalCampaignNeed.023"),organization:SOSText("politics_campaigns_civic.politicalCampaignNeed.024"),legitimacy:SOSText("politics_campaigns_civic.politicalCampaignNeed.025"),merchant:SOSText("politics_campaigns_civic.politicalCampaignNeed.026"),security:SOSText("politics_campaigns_civic.politicalCampaignNeed.027"),counter:SOSText("politics_campaigns_civic.politicalCampaignNeed.028")},
 Coalition:{support:SOSText("politics_campaigns_civic.politicalCampaignNeed.029"),organization:SOSText("politics_campaigns_civic.politicalCampaignNeed.030"),legitimacy:SOSText("politics_campaigns_civic.politicalCampaignNeed.031"),merchant:SOSText("politics_campaigns_civic.politicalCampaignNeed.032"),security:SOSText("politics_campaigns_civic.politicalCampaignNeed.033"),counter:SOSText("politics_campaigns_civic.politicalCampaignNeed.034")},
 Bluestone:{support:SOSText("politics_campaigns_civic.politicalCampaignNeed.035"),organization:SOSText("politics_campaigns_civic.politicalCampaignNeed.036"),legitimacy:SOSText("politics_campaigns_civic.politicalCampaignNeed.037"),merchant:SOSText("politics_campaigns_civic.politicalCampaignNeed.038"),security:SOSText("politics_campaigns_civic.politicalCampaignNeed.039"),counter:SOSText("politics_campaigns_civic.politicalCampaignNeed.040")},
 Shantium:{support:SOSText("politics_campaigns_civic.politicalCampaignNeed.041"),organization:SOSText("politics_campaigns_civic.politicalCampaignNeed.042"),legitimacy:SOSText("politics_campaigns_civic.politicalCampaignNeed.043"),merchant:SOSText("politics_campaigns_civic.politicalCampaignNeed.044"),security:SOSText("politics_campaigns_civic.politicalCampaignNeed.045"),counter:SOSText("politics_campaigns_civic.politicalCampaignNeed.046")},
 Spawn:{support:SOSText("politics_campaigns_civic.politicalCampaignNeed.047"),organization:SOSText("politics_campaigns_civic.politicalCampaignNeed.048"),legitimacy:SOSText("politics_campaigns_civic.politicalCampaignNeed.049"),merchant:SOSText("politics_campaigns_civic.politicalCampaignNeed.050"),security:SOSText("politics_campaigns_civic.politicalCampaignNeed.051"),counter:SOSText("politics_campaigns_civic.politicalCampaignNeed.052")},
 Mercenaries:{support:SOSText("politics_campaigns_civic.politicalCampaignNeed.053"),organization:SOSText("politics_campaigns_civic.politicalCampaignNeed.054"),legitimacy:SOSText("politics_campaigns_civic.politicalCampaignNeed.055"),merchant:SOSText("politics_campaigns_civic.politicalCampaignNeed.056"),security:SOSText("politics_campaigns_civic.politicalCampaignNeed.057"),counter:SOSText("politics_campaigns_civic.politicalCampaignNeed.058")}
};
function politicalCampaignType(metric,faction){
 if(metric==='security')return chance(.55)?'visit':'hunt';
 if(metric==='merchant')return chance(.55)?'delivery':'diplomacy';
 if(metric==='organization')return chance(.55)?'delivery':'visit';
 if(metric==='legitimacy')return chance(.62)?'procure':'visit';
 if(metric==='counter')return'diplomacy';
 return chance(.55)?'diplomacy':'visit'
}
function politicalCampaignEffects(metric){
 const rows={
  support:{support:1.8,organization:.5,legitimacy:.25,power:2.5,pressure:.7,rivalSupport:.55,rivalOrganization:.15},
  organization:{support:.6,organization:2,legitimacy:.2,power:2.6,pressure:1,presence:1,rivalSupport:.2,rivalOrganization:.45},
  legitimacy:{support:1,organization:.25,legitimacy:2,merchant:.4,power:2.7,pressure:.65,rivalSupport:.4,rivalOrganization:.15},
  merchant:{support:.7,organization:.35,merchant:2,legitimacy:.25,power:2.6,pressure:.55,rivalSupport:.3,rivalMerchant:.6},
  security:{support:.55,organization:.5,legitimacy:.75,security:2,power:3,pressure:.8,rivalSupport:.3,rivalOrganization:.2},
  counter:{support:1,organization:1,legitimacy:.2,power:2.8,pressure:1.1,rivalSupport:1.2,rivalOrganization:.8}
 };return {...(rows[metric]||rows.support)}
}
function politicalCampaignChannel(metric){return metric==='merchant'||metric==='legitimacy'?'trade':metric==='security'?'security':metric==='organization'?'personnel':'politics'}
function politicalCampaignEffectText(q){
 const e=q?.politicalEffects||{},bits=[];if(e.support)bits.push(SOSText("politics_campaigns_civic.politicalCampaignEffectText.001",e.support));if(e.organization)bits.push(SOSText("politics_campaigns_civic.politicalCampaignEffectText.002",e.organization));if(e.legitimacy)bits.push(SOSText("politics_campaigns_civic.politicalCampaignEffectText.003",e.legitimacy));if(e.merchant)bits.push(SOSText("politics_campaigns_civic.politicalCampaignEffectText.004",e.merchant));if(e.security)bits.push(SOSText("politics_campaigns_civic.politicalCampaignEffectText.005",e.security));if(e.rivalSupport)bits.push(SOSText("politics_campaigns_civic.politicalCampaignEffectText.006",e.rivalSupport));if(e.rivalOrganization)bits.push(SOSText("politics_campaigns_civic.politicalCampaignEffectText.007",e.rivalOrganization));return bits.join(' • ')
}
function politicalCampaignDescription(locId,faction,need,type,target){
 const here=worldLocation(locId).name,to=worldLocation(target)?.name||here,priority=currentFactionPriority(faction).label;
 if(need.metric==='support')return SOSText("politics_campaigns_civic.politicalCampaignDescription.001",majorFaction(faction).name,here,priority.toLowerCase());
 if(need.metric==='organization')return SOSText("politics_campaigns_civic.politicalCampaignDescription.002",majorFaction(faction).short,here,to);
 if(need.metric==='legitimacy')return SOSText("politics_campaigns_civic.politicalCampaignDescription.003",majorFaction(faction).short,here);
 if(need.metric==='merchant')return SOSText("politics_campaigns_civic.politicalCampaignDescription.004",majorFaction(faction).short,here,to);
 if(need.metric==='security')return SOSText("politics_campaigns_civic.politicalCampaignDescription.005",majorFaction(faction).short,here);
 return SOSText("politics_campaigns_civic.politicalCampaignDescription.006",majorFaction(faction).short,majorFaction(need.rival).short)
}
function politicalCampaignActiveOrOffered(locId,faction){
 return [...(state.world.quests||[]),...(state.world.contracts?.[locId]||[])].find(q=>q.politicalCampaign&&q.politicalLocId===locId&&q.politicalFaction===faction&&['offered','active','ready'].includes(q.status))
}
function generatePoliticalCampaignContract(locId,faction,force=false){
 if(!OPEN_WORLD_FACTIONS[faction]||!state.world.settlements?.[locId])return null;const c=politicalCampaignState(locId,faction),standing=state.world.factionStanding[faction]||0;
 if(!force&&state.world.day-(c.lastCommissionDay||-99)<2)return null;if(politicalCampaignActiveOrOffered(locId,faction))return null;if(standing<0)return null;
 const need=politicalCampaignNeed(locId,faction),type=politicalCampaignType(need.metric,faction),same=regionalSettlements(locationRegion(locId)).filter(x=>x.id!==locId&&!x.hidden),target=(type==='procure'?locId:(pick(same)?.id||locId)),q=generateContract(locId,type,{target,faction});
 q.politicalCampaign=true;q.politicalLocId=locId;q.politicalFaction=faction;q.politicalRival=need.rival||null;q.politicalMetric=need.metric;q.politicalNeed=need.label;q.politicalReason=need.reason;q.politicalEffects=politicalCampaignEffects(need.metric);q.politicalChannel=politicalCampaignChannel(need.metric);q.chainKey=`politics:${locId}:${faction}:${need.metric}`;q.name=POLITICAL_CAMPAIGN_NAMES[faction]?.[need.metric]||SOSText("politics_campaigns_civic.generatePoliticalCampaignContract.001",majorFaction(faction).short);q.variantName=q.name;q.desc=politicalCampaignDescription(locId,faction,need,type,q.target);q.reward+=28+Math.max(0,Math.round((localPoliticalProfile(locId,need.rival||faction).overall-localPoliticalProfile(locId,faction).overall)*.5));q.paymentMode='origin_agent';q.paymentLocation=locId;q.paymentPayer=contractPaymentAgentLabel(q,locId,'origin_agent');q.paymentExplanation=SOSText("politics_campaigns_civic.generatePoliticalCampaignContract.002",q.paymentPayer,worldLocation(locId).name);
 c.lastCommissionDay=state.world.day;c.history.push({day:state.world.day,type:'commissioned',contractId:q.id,text:SOSText("politics_campaigns_civic.generatePoliticalCampaignContract.003",q.name,need.label.toLowerCase())});c.history=c.history.slice(-20);
 state.world.contracts[locId]=state.world.contracts[locId]||[];state.world.contracts[locId].unshift(q);state.world.contracts[locId]=state.world.contracts[locId].slice(0,4);recordLocalPoliticalAction(locId,faction,'campaign_commission',SOSText("politics_campaigns_civic.generatePoliticalCampaignContract.004",majorFaction(faction).short,q.name,need.reason));return q
}
function applyPoliticalCampaignConsequences(q){
 if(!q?.politicalCampaign||q.politicalConsequencesApplied)return'';q.politicalConsequencesApplied=true;const locId=q.politicalLocId||q.origin,faction=q.politicalFaction||q.faction,e=q.politicalEffects||{},c=politicalCampaignState(locId,faction),rival=q.politicalRival,before=politicalOutcomeSnapshot(locId,[faction,rival]);
 applyLocalPoliticalEffects(locId,faction,{support:e.support||0,organization:e.organization||0,legitimacy:e.legitimacy||0,merchant:e.merchant||0,security:e.security||0,power:e.power||0,pressure:e.pressure||0,presence:e.presence||0,days:12},SOSText("politics_campaigns_civic.applyPoliticalCampaignConsequences.001",q.name),q.politicalChannel||'politics');
 if(rival&&OPEN_WORLD_FACTIONS[rival]){const rc=localPoliticalFactionState(locId,rival);rc.support=clamp((rc.support||0)-(e.rivalSupport||0),-6,12);rc.organization=clamp((rc.organization||0)-(e.rivalOrganization||0),-6,12);rc.merchant=clamp((rc.merchant||0)-(e.rivalMerchant||0),-6,12);politicalSettlement(locId).pressure[rival]=Math.max(0,(politicalSettlement(locId).pressure[rival]||0)-((e.rivalSupport||0)+(e.rivalOrganization||0))*.25)}
 c.successes++;c.momentum=clamp(c.momentum+2,-8,10);adjustPoliticalCapital(locId,faction,4,SOSText("politics_campaigns_civic.applyPoliticalCampaignConsequences.002",q.name,majorFaction(faction).short));c.heat=clamp(c.heat+2.25,0,10);c.lastResultDay=state.world.day;c.history.push({day:state.world.day,type:'success',contractId:q.id,text:`${q.name} succeeds. ${politicalCampaignEffectText(q)}`});c.history=c.history.slice(-20);recordLocalPoliticalAction(locId,faction,'campaign_success',SOSText("politics_campaigns_civic.applyPoliticalCampaignConsequences.003",q.name,majorFaction(faction).short));q.politicalOutcome={before,after:politicalOutcomeSnapshot(locId,[faction,rival]),notes:[SOSText("politics_campaigns_civic.applyPoliticalCampaignConsequences.004",politicalCampaignMomentumLabel(c.momentum))]};return politicalCampaignEffectText(q)
}
function applyPoliticalCampaignFailure(q,reason=SOSText("politics_campaigns_civic.applyPoliticalCampaignFailure.001"),abandoned=false){
 if(!q?.politicalCampaign||q.politicalFailureApplied||q.politicalConsequencesApplied)return'';q.politicalFailureApplied=true;const locId=q.politicalLocId||q.origin,faction=q.politicalFaction||q.faction,c=politicalCampaignState(locId,faction),fc=localPoliticalFactionState(locId,faction),rival=q.politicalRival,before=politicalOutcomeSnapshot(locId,[faction,rival]);
 fc.organization=clamp((fc.organization||0)-(abandoned?.75:.4),-6,12);fc.legitimacy=clamp((fc.legitimacy||0)-(abandoned?.45:.2),-6,12);if(rival&&OPEN_WORLD_FACTIONS[rival]){const rc=localPoliticalFactionState(locId,rival);rc.support=clamp((rc.support||0)+(abandoned?.65:.4),-6,12)}
 c.failures++;c.momentum=clamp(c.momentum-(abandoned?2:1),-8,10);adjustPoliticalCapital(locId,faction,-(abandoned?2:1),SOSText("politics_campaigns_civic.applyPoliticalCampaignFailure.002",q.name));c.heat=clamp(c.heat+.5,0,10);c.lastResultDay=state.world.day;c.history.push({day:state.world.day,type:abandoned?'abandoned':'failed',contractId:q.id,text:`${q.name}: ${reason}`});c.history=c.history.slice(-20);recordLocalPoliticalAction(locId,faction,'campaign_failure',SOSText("politics_campaigns_civic.applyPoliticalCampaignFailure.003",q.name,majorFaction(faction).short));q.politicalOutcome={before,after:politicalOutcomeSnapshot(locId,[faction,rival]),notes:[reason]};return SOSText("politics_campaigns_civic.applyPoliticalCampaignFailure.004")
}
function simulateLocalPoliticalCampaignDay(locId){
 const ps=politicalSettlement(locId);for(const [f,c] of Object.entries(ps.campaigns||{})){if(!OPEN_WORLD_FACTIONS[f])continue;c.heat=Math.max(0,(c.heat||0)-.28);c.momentum=(c.momentum||0)*.985;if(c.heat<1.2)continue;const rival=localPoliticalRival(locId,f);if(!rival)continue;const rp=localPoliticalProfile(locId,rival),chanceCounter=clamp(.045+c.heat*.012+rp.organization/1700,.04,.22);if(!chance(chanceCounter))continue;const rc=localPoliticalFactionState(locId,rival),fc=localPoliticalFactionState(locId,f),strength=rp.organization>=65?.55:.35;rc.support=clamp((rc.support||0)+strength,-6,12);rc.organization=clamp((rc.organization||0)+strength*.6,-6,12);fc.support=clamp((fc.support||0)-strength*.25,-6,12);ps.pressure[rival]=clamp((ps.pressure[rival]||0)+.15,0,12);c.heat=Math.max(0,c.heat-.8);const text=SOSText("politics_campaigns_civic.simulateLocalPoliticalCampaignDay.001",majorFaction(rival).short,majorFaction(f).short);ps.civicHistory.push({day:state.world.day,faction:rival,action:'counter_campaign',text});ps.civicHistory=ps.civicHistory.slice(-30);if(chance(.28))recordWorldNews(SOSText("politics_campaigns_civic.simulateLocalPoliticalCampaignDay.002",worldLocation(locId).name,majorFaction(rival).short),'info')}
}
function politicalCampaignSourceHTML(q){
 if(!q?.politicalCampaign)return'';return SOSText("politics_campaigns_civic.politicalCampaignSourceHTML.001",esc(majorFaction(q.politicalFaction||q.faction).name),esc(worldLocation(q.politicalLocId||q.origin).name),esc(q.politicalNeed||'Strengthen the local campaign'),esc(q.politicalReason||''),esc(politicalCampaignEffectText(q)),q.politicalRival?`<br>Main rival: ${esc(majorFaction(q.politicalRival).short)}`:'')
}
function markLocalPoliticsDirty(locId){const ps=politicalSettlement(locId);ps.uiRevision=(ps.uiRevision||0)+1;ps.uiUpdatedDay=state.world.day;return ps.uiRevision}
function recordLocalPoliticalAction(locId,faction,action,text){
 const ps=politicalSettlement(locId),row={day:state.world.day,faction,action,text};ps.civicHistory.push(row);ps.civicHistory=ps.civicHistory.slice(-30);ps.lastCivicActionDay=state.world.day;markLocalPoliticsDirty(locId);politicalHistory(`${worldLocation(locId).name}: ${text}`,'info');if(typeof queuePoliticalRetaliationExposure==='function')queuePoliticalRetaliationExposure(locId,'political_action')
}
function applyPoliticalDamage(locId,faction,damage,scale=1){
 if(!faction||!OPEN_WORLD_FACTIONS[faction]||!damage)return;const ps=politicalSettlement(locId),c=localPoliticalFactionState(locId,faction);
 for(const k of ['support','organization','legitimacy','merchant','security'])if(damage[k])c[k]=clamp((c[k]||0)-damage[k]*scale,-6,12);
 if(damage.pressure)ps.pressure[faction]=Math.max(0,(ps.pressure[faction]||0)-damage.pressure*scale);
 if(damage.lean)ps.lean[faction]=clamp((ps.lean[faction]||0)-damage.lean*scale,-6,12);c.lastActionDay=state.world.day
}
function applyLocalPoliticalEffects(locId,faction,effect,reason,channel='politics'){
 const ps=politicalSettlement(locId),c=localPoliticalFactionState(locId,faction),presence=state.world.factionPresence[locId]||(state.world.factionPresence[locId]={});
 for(const k of ['support','organization','legitimacy','merchant','security'])if(effect[k])c[k]=clamp((c[k]||0)+effect[k],-6,12);
 c.lastActionDay=state.world.day;
 if(effect.presence)presence[faction]=clamp((presence[faction]||0)+effect.presence,0,12);
 if(effect.pressure)ps.pressure[faction]=clamp((ps.pressure[faction]||0)+effect.pressure,0,12);
 if(effect.power)recordFactionPower(locId,faction,channel,effect.power,reason,effect.days||10);
 const rival=effect.rival?localPoliticalRival(locId,faction):null;
 if(rival){const d=typeof effect.rival==='object'?effect.rival:{support:Number(effect.rival)||0,pressure:(Number(effect.rival)||0)*.35,lean:(Number(effect.rival)||0)*.25};applyPoliticalDamage(locId,rival,d,1);if(effect.rivalSpillover!==false){for(const other of localPoliticalFactions(locId))if(other!==faction&&other!==rival)applyPoliticalDamage(locId,other,d,.2)}}
 markLocalPoliticsDirty(locId)
}
function decayLocalPoliticalCivic(locId){
 const ps=politicalSettlement(locId),control=settlementControl(locId),ss=settlementState(locId),rr=roadRights(locId);
 for(const [f,c] of Object.entries(ps.civic||{})){if(!OPEN_WORLD_FACTIONS[f])continue;if(state.world.day-(c.lastActionDay||0)>=6){for(const k of ['support','organization','legitimacy','merchant','security']){if(c[k]>0)c[k]=Math.max(0,c[k]-.12);else if(c[k]<0)c[k]=Math.min(0,c[k]+.08)}}}
 const ruling=localPoliticalFactionState(locId,control);if(ss.security<38)ruling.legitimacy=clamp(ruling.legitimacy-.10,-6,12);if(ss.prosperity<38)ruling.legitimacy=clamp(ruling.legitimacy-.10,-6,12);
 if(rr.openness<=3&&[SOSText("politics_campaigns_civic.decayLocalPoliticalCivic.001"),SOSText("politics_campaigns_civic.decayLocalPoliticalCivic.002")].includes(control)){const ind=localPoliticalFactionState(locId,SOSText("politics_campaigns_civic.decayLocalPoliticalCivic.003"));ind.support=clamp(ind.support+.08,-6,12)}
}
function guardianPublicEndorsement(){
 ensureWorldState();if(!state.world.guardianPublicEndorsement||typeof state.world.guardianPublicEndorsement!=='object')state.world.guardianPublicEndorsement={faction:null,day:-99,history:[]};
 const e=state.world.guardianPublicEndorsement;if(!Array.isArray(e.history))e.history=[];if(!Number.isFinite(e.day))e.day=-99;return e
}
function guardianEndorsementSwitchReady(){const e=guardianPublicEndorsement();return !e.faction||state.world.day-(e.day||-99)>=7}
function guardianEndorsementButtonState(faction){
 const e=guardianPublicEndorsement();
 if(e.faction===faction)return {disabled:true,label:SOSText("politics_campaigns_civic.guardianEndorsementButtonState.001"),reason:SOSText("politics_campaigns_civic.guardianEndorsementButtonState.002",majorFaction(faction).short)};
 if(e.faction&&!guardianEndorsementSwitchReady()){const left=Math.max(1,7-(state.world.day-e.day));return {disabled:true,label:SOSText("politics_campaigns_civic.guardianEndorsementButtonState.003",majorFaction(faction).short),reason:SOSText("politics_campaigns_civic.guardianEndorsementButtonState.004",majorFaction(e.faction).short,left,left===1?'':'s')}}
 return {disabled:false,label:e.faction?SOSText("politics_campaigns_civic.guardianEndorsementButtonState.005",majorFaction(faction).short):SOSText("politics_campaigns_civic.guardianEndorsementButtonState.006"),reason:e.faction?SOSText("politics_campaigns_civic.guardianEndorsementButtonState.007",majorFaction(e.faction).short):''}
}
const LOCAL_POLITICAL_ACTIONS={
 rally:{title:SOSText("politics_campaigns_civic.guardianEndorsementButtonState.008"),cost:12,desc:SOSText("politics_campaigns_civic.guardianEndorsementButtonState.009"),channel:'politics'},
 endorse:{title:SOSText("politics_campaigns_civic.guardianEndorsementButtonState.010"),cost:0,desc:SOSText("politics_campaigns_civic.guardianEndorsementButtonState.011"),channel:'guardian'},
 organize:{title:SOSText("politics_campaigns_civic.guardianEndorsementButtonState.012"),cost:8,desc:SOSText("politics_campaigns_civic.guardianEndorsementButtonState.013"),channel:'personnel'},
 petition:{title:SOSText("politics_campaigns_civic.guardianEndorsementButtonState.014"),cost:6,desc:SOSText("politics_campaigns_civic.guardianEndorsementButtonState.015"),channel:'politics'},
 relief:{title:SOSText("politics_campaigns_civic.guardianEndorsementButtonState.016"),cost:30,desc:SOSText("politics_campaigns_civic.guardianEndorsementButtonState.017"),channel:'trade'},
 repairs:{title:SOSText("politics_campaigns_civic.guardianEndorsementButtonState.018"),cost:34,desc:SOSText("politics_campaigns_civic.guardianEndorsementButtonState.019"),channel:'trade'}
};
function politicalActionCost(locId,id){const ss=settlementState(locId),a=LOCAL_POLITICAL_ACTIONS[id];if(!a)return 0;if(id==='relief')return a.cost+(ss.prosperity<45?6:0);if(id==='repairs')return a.cost+(ss.prosperity<40?4:0);return a.cost}
function politicalActionReturnToActivities(locId){return navigateTownMenu('politicalActivities',{locId})}
function persistPoliticalDiagnosticFallback(err,system='Political Action',action='',details={}){
 const key='sosRuntimeJavascriptErrorsV1';
 try{
  const current=JSON.parse(localStorage.getItem(key)||'[]'),rows=Array.isArray(current)?current:[],day=state?.world?.day??null,locId=state?.world?.location||null;
  let locName=locId;try{locName=locId?(worldLocation(locId)?.name||locId):null}catch{}
  const message=err?.message||String(err||'Unknown political simulation error'),stack=String(err?.stack||'').split('\n').map(x=>x.trim()).filter(Boolean),where=stack.find(x=>/\.html:\d+|\.js:\d+|<anonymous>:\d+/.test(x))||'';
  const line=`[JS ERROR] ${message}${where?` • ${where.replace(/^at\s+/,'')}`:''}`,detailLocation=details?.location||details?.locId||'';
  const row={time:new Date().toISOString(),kind:'recoverable',line,day,mode:state?.mode||null,location:locName,system,action,detailLocation,faction:details?.faction||'',rollbackRestored:details?.rollbackRestored??null,fallbackPersisted:true};
  const same=(a,b)=>a&&a.line===b.line&&a.day===b.day&&a.system===b.system&&a.action===b.action;
  const last=rows[rows.length-1];if(!same(last,row))rows.push(row);
  localStorage.setItem(key,JSON.stringify(rows.slice(-40)));
  // Keep a second copy inside campaign state so World Journal diagnostics do not depend on browser storage alone.
  if(state?.world){
   if(!state.world.runtimeDiagnostics||typeof state.world.runtimeDiagnostics!=='object')state.world.runtimeDiagnostics={};
   if(!Array.isArray(state.world.runtimeDiagnostics.errors))state.world.runtimeDiagnostics.errors=[];
   const campaignRows=state.world.runtimeDiagnostics.errors,lastCampaign=campaignRows[campaignRows.length-1];
   if(!same(lastCampaign,row))campaignRows.push({...row,campaignPersisted:true});
   state.world.runtimeDiagnostics.errors=campaignRows.slice(-40);
  }
  return true
 }catch(fallbackError){console.error('[Politics] Could not persist political diagnostic fallback.',fallbackError);return false}
}
function recordPoliticalTransactionError(err,system,label,context={}){
 let recorded=false;
 try{if(typeof reportRecoverableGameError==='function'){reportRecoverableGameError(err,system,label,context);recorded=true}}catch(logError){console.error('[Politics] Primary Journal error reporter failed.',logError)}
 // Always write the independent fallback/campaign copy too; duplicate suppression keeps one visible entry.
 const fallbackRecorded=persistPoliticalDiagnosticFallback(err,system,label,context);
 return recorded||fallbackRecorded
}
function politicalActionTransaction(label,fallback,fn,context={}){
 let snapshot=null;try{snapshot=JSON.stringify(state)}catch(e){console.warn('[Politics] Could not prepare rollback snapshot.',e)}
 try{return fn()}catch(e){
  console.error(`[Politics] ${label} failed; rolling back the political action.`,e);
  let rollbackRestored=false;
  if(snapshot){try{state=JSON.parse(snapshot);ensureWorldState();rollbackRestored=true}catch(restoreError){console.error('[Politics] Political rollback restore failed.',restoreError);recordPoliticalTransactionError(restoreError,'Political Rollback',label,{...context,rollbackRestored:false})}}
  try{save()}catch(saveError){console.error('[Politics] Could not save rolled-back political state.',saveError);recordPoliticalTransactionError(saveError,'Political Rollback Save',label,{...context,rollbackRestored})}
  recordPoliticalTransactionError(e,'Political Action',label,{...context,rollbackRestored});
  try{save()}catch(diagSaveError){console.error('[Politics] Could not save campaign diagnostic copy.',diagSaveError)}
  return actionResult(SOSText("politics_campaigns_civic.politicalActionTransaction.001"),SOSText("politics_campaigns_civic.politicalActionTransaction.003"),'bad',fallback)
 }
}
function executeLocalPoliticalAction(locId,faction,id){
 const a=LOCAL_POLITICAL_ACTIONS[id];if(!a||!OPEN_WORLD_FACTIONS[faction])return showLocalPoliticalActions(locId);
 const standing=state.world.factionStanding[faction]||0,rep=localReputation(locId),cost=politicalActionCost(locId,id);
 if(standing<=-4)return actionResult(SOSText("politics_campaigns_civic.executeLocalPoliticalAction.001"),SOSText("politics_campaigns_civic.executeLocalPoliticalAction.002",majorFaction(faction).name),'bad',()=>showFactionCivicActions(locId,faction));
 if(id==='endorse'){const es=guardianEndorsementButtonState(faction);if(es.disabled)return actionResult(es.label,es.reason,'info',()=>showFactionCivicActions(locId,faction))}
 if(id==='organize'&&standing<2)return actionResult(SOSText("politics_campaigns_civic.executeLocalPoliticalAction.010"),SOSText("politics_campaigns_civic.executeLocalPoliticalAction.011",majorFaction(faction).short),'info',()=>showFactionCivicActions(locId,faction));
 if(state.gold<cost)return actionResult(SOSText("politics_campaigns_civic.executeLocalPoliticalAction.003"),SOSText("politics_campaigns_civic.executeLocalPoliticalAction.004",a.title,cost),'bad',()=>showFactionCivicActions(locId,faction));
 return politicalActionTransaction(a.title,()=>navigateTownMenu('factionCivic',{locId,faction}),()=>{
  const before=politicalOutcomeSnapshot(locId,[faction,localPoliticalRival(locId,faction)]),ss=settlementState(locId);
  if(cost)state.gold-=cost;
  let effect={},text='',tone='good',standingGain=0,repGain=0,roll=0;
  if(id==='rally'){roll=rnd(1,20)+stat(state,'cha')+Math.floor(rep/2)+Math.floor(standing/3);if(roll>=16){effect={support:2,organization:1,legitimacy:.5,power:3,pressure:1,rival:{support:.75,organization:.3,legitimacy:.2,pressure:.3,lean:.2}};text=SOSText("politics_campaigns_civic.executeLocalPoliticalAction.005",majorFaction(faction).short);standingGain=1}else{effect={support:.5,organization:.5,power:.5};text=SOSText("politics_campaigns_civic.executeLocalPoliticalAction.006");tone='info'}}
  if(id==='endorse'){const e=guardianPublicEndorsement(),oldFaction=e.faction,impact=rep>=8?2:rep>=3?1.5:rep>=0?1:.5;effect={support:impact,legitimacy:rep>=3?1:.25,power:1.5+impact*.5,pressure:.5,rival:impact>=1.5?{support:.5,legitimacy:.2,pressure:.18,lean:.12}:0};
   if(oldFaction&&oldFaction!==faction){adjustFactionStanding(oldFaction,-1,SOSText("politics_campaigns_civic.executeLocalPoliticalAction.007",majorFaction(faction).short));const oldP=localPoliticalFactionState(locId,oldFaction);oldP.support=clamp((oldP.support||0)-.75,-6,12);oldP.legitimacy=clamp((oldP.legitimacy||0)-.25,-6,12);text=SOSText("politics_campaigns_civic.executeLocalPoliticalAction.008",majorFaction(oldFaction).short,majorFaction(faction).short,worldLocation(locId).name)}
   else text=SOSText("politics_campaigns_civic.executeLocalPoliticalAction.009",majorFaction(faction).short,worldLocation(locId).name,rep>=8?'The endorsement carries considerable local weight.':rep>=3?'The endorsement is taken seriously by people who know the company.':'The statement is noticed, though the Guardian’s local pull is limited.');
   e.faction=faction;e.day=state.world.day;e.history.push({day:state.world.day,faction,from:oldFaction||null,locId});e.history=e.history.slice(-12);standingGain=1}
  if(id==='organize'){effect={organization:2,support:standing>=6?1:.5,power:2.5,pressure:.75,presence:1,rival:{support:.35,organization:.35,pressure:.15,lean:.1}};text=SOSText("politics_campaigns_civic.executeLocalPoliticalAction.012",majorFaction(faction).short);standingGain=chance(.35)?1:0}
  if(id==='petition'){roll=rnd(1,20)+stat(state,'cha')+Math.floor(rep/2);if(roll>=15){effect={support:1.5,organization:1,legitimacy:.5,power:2.5,pressure:.75,rival:{support:.5,organization:.2,legitimacy:.15,pressure:.2,lean:.12}};text=SOSText("politics_campaigns_civic.executeLocalPoliticalAction.013")}else{effect={organization:.75,support:.25,power:.5};text=SOSText("politics_campaigns_civic.executeLocalPoliticalAction.014");tone='info'}}
  if(id==='relief'){const bonus=ss.prosperity<45?.75:0;effect={support:1.25+bonus,legitimacy:2,merchant:.5,power:2.75,pressure:.5,rival:{support:.4,legitimacy:.25,merchant:.1,pressure:.12,lean:.1}};ss.prosperity=Math.min(100,ss.prosperity+2);text=SOSText("politics_campaigns_civic.executeLocalPoliticalAction.015",majorFaction(faction).short);repGain=1;standingGain=1}
  if(id==='repairs'){effect={support:.75,legitimacy:2,merchant:1,security:.75,power:2.5,pressure:.5,rival:{support:.35,legitimacy:.3,merchant:.15,pressure:.12,lean:.1}};ss.prosperity=Math.min(100,ss.prosperity+2);ss.security=Math.min(100,ss.security+1);text=SOSText("politics_campaigns_civic.executeLocalPoliticalAction.016",majorFaction(faction).short);repGain=1;standingGain=1}
  applyLocalPoliticalEffects(locId,faction,effect,text,a.channel);adjustPoliticalCapital(locId,faction,id==='relief'||id==='repairs'?2:id==='organize'?1.5:1,SOSText("politics_campaigns_civic.executeLocalPoliticalAction.017",a.title));
  if(standingGain)adjustFactionStanding(faction,standingGain,SOSText("politics_campaigns_civic.executeLocalPoliticalAction.018",worldLocation(locId).name));
  if(repGain)changeLocalReputation(locId,repGain,SOSText("politics_campaigns_civic.executeLocalPoliticalAction.019",majorFaction(faction).short));
  recordLocalPoliticalAction(locId,faction,id,text);const notes=[];if(effect.rival)notes.push(SOSText("politics_campaigns_civic.executeLocalPoliticalAction.020",majorFaction(faction).short));if(cost)notes.push(SOSText("politics_campaigns_civic.executeLocalPoliticalAction.021",cost));
  if(['organize','relief','repairs'].includes(id))advanceWorldDays(1,`${a.title} in ${worldLocation(locId).name}`);
  const after=politicalOutcomeSnapshot(locId,[faction,localPoliticalRival(locId,faction)]);
  sfxWorld('politics');save();return showPoliticalOutcome(a.title,text,before,after,{tone,notes,back:()=>politicalActionReturnToActivities(locId)})
 },{location:worldLocation(locId)?.name||locId,faction:majorFaction(faction)?.short||faction})
}
function executeIndependentCivicAction(locId,id){
 if(!['relief','works','forum'].includes(id))return showIndependentCivicActions(locId);
 const label=SOSText("politics_campaigns_civic.executeIndependentCivicAction.016");
 const required=id==='relief'?24:id==='works'?30:12;if(state.gold<required)return actionResult(id==='relief'?SOSText("politics_campaigns_civic.executeIndependentCivicAction.001"):id==='works'?SOSText("politics_campaigns_civic.executeIndependentCivicAction.005"):SOSText("politics_campaigns_civic.executeIndependentCivicAction.009"),id==='relief'?SOSText("politics_campaigns_civic.executeIndependentCivicAction.002",required):id==='works'?SOSText("politics_campaigns_civic.executeIndependentCivicAction.006",required):SOSText("politics_campaigns_civic.executeIndependentCivicAction.010",required),'bad',()=>showIndependentCivicActions(locId));
 return politicalActionTransaction(label,()=>navigateTownMenu('independentCivic',{locId}),()=>{
  const before=politicalOutcomeSnapshot(locId),ps=politicalSettlement(locId),ss=settlementState(locId);let cost=0,text='',tone='good';
  if(id==='relief'){cost=24;state.gold-=cost;ss.prosperity=Math.min(100,ss.prosperity+2);changeLocalReputation(locId,2,SOSText("politics_campaigns_civic.executeIndependentCivicAction.003"));ps.autonomy=Math.min(10,ps.autonomy+.5);text=SOSText("politics_campaigns_civic.executeIndependentCivicAction.004")}
  if(id==='works'){cost=30;state.gold-=cost;ss.prosperity=Math.min(100,ss.prosperity+2);ss.security=Math.min(100,ss.security+1);changeLocalReputation(locId,2,SOSText("politics_campaigns_civic.executeIndependentCivicAction.007"));ps.autonomy=Math.min(10,ps.autonomy+.5);text=SOSText("politics_campaigns_civic.executeIndependentCivicAction.008")}
  if(id==='forum'){cost=12;state.gold-=cost;const rows=Object.entries(ps.pressure||{}).sort((a,b)=>b[1]-a[1]);for(const [f] of rows.slice(0,2))ps.pressure[f]=Math.max(0,(ps.pressure[f]||0)-.35);ps.autonomy=Math.min(10,ps.autonomy+1);changeLocalReputation(locId,1,SOSText("politics_campaigns_civic.executeIndependentCivicAction.011"));text=SOSText("politics_campaigns_civic.executeIndependentCivicAction.012")}
  recordLocalPoliticalAction(locId,SOSText("politics_campaigns_civic.executeIndependentCivicAction.013"),id,text);const notes=cost?[SOSText("politics_campaigns_civic.executeIndependentCivicAction.014",cost)]:[];if(id!=='forum')advanceWorldDays(1,SOSText("politics_campaigns_civic.executeIndependentCivicAction.015",worldLocation(locId).name));const after=politicalOutcomeSnapshot(locId);save();return showPoliticalOutcome(SOSText("politics_campaigns_civic.executeIndependentCivicAction.016"),text,before,after,{tone,notes,back:()=>politicalActionReturnToActivities(locId)})
 },{location:worldLocation(locId)?.name||locId,faction:'Independent'})
}
const LEGITIMATE_OPPOSITION_ACTIONS={
 rally_against:{title:'Hold an Opposition Rally',cost:14,desc:'Organize a lawful public rally arguing against the faction’s local agenda.',difficulty:15,damage:{support:1.5,organization:.5,legitimacy:.25,pressure:.45,lean:.25}},
 disparage:{title:'Disparage Their Leaders in Public',cost:8,desc:'Attack the faction’s leadership, judgment, and record in speeches and public conversations.',difficulty:14,damage:{support:.55,legitimacy:1.05,pressure:.25,lean:.2}},
 debate:{title:'Challenge Their Rivals to a Public Debate',cost:10,desc:'Demand a public debate with a prominent local representative. Winning can badly damage credibility; losing can strengthen them.',difficulty:16,damage:{support:1,legitimacy:1.25,organization:.25,pressure:.35,lean:.25}},
 critique:{title:'Publish a Public Critique',cost:6,desc:'Circulate a detailed lawful critique of the faction’s policies and local record.',difficulty:13,damage:{support:.4,legitimacy:.8,merchant:.2,pressure:.2,lean:.15}},
 counter_petition:{title:'Organize a Counter-Petition',cost:8,desc:'Mobilize residents against the faction’s current demands and organizing drive.',difficulty:14,damage:{support:.4,organization:.8,pressure:1,lean:.2}},
 expose_failures:{title:'Expose Their Policy Failures',cost:10,desc:'Make a public case that local insecurity, poverty, closed roads, or other failures reflect badly on the faction.',difficulty:15,damage:{support:.55,legitimacy:1.1,pressure:.35,lean:.2},context:true},
 counter_campaign:{title:'Mount a Counter-Campaign',cost:20,desc:'Coordinate a sustained legal campaign to blunt the faction’s local organization and momentum.',difficulty:16,damage:{support:1,organization:1.5,legitimacy:.35,pressure:1.2,lean:.35},dayScale:true},
 court_constituency:{title:'Court Their Constituency',cost:14,desc:'Try to peel merchants, civic groups, security interests, and other local supporters away from the faction.',difficulty:16,damage:{support:.55,merchant:.8,security:.55,organization:.35,pressure:.3,lean:.2}},
 government_record:{title:'Attack the Government’s Record',cost:12,desc:'Hold the faction responsible for the settlement’s security, prosperity, restrictions, and recent governing record.',difficulty:14,damage:{support:.75,legitimacy:1.35,pressure:.65,lean:.35},incumbent:true,context:true},
 protest_drive:{title:'Organize a Protest Drive',cost:18,desc:'Coordinate lawful demonstrations, speakers, placards, and neighborhood meetings against the faction in power.',difficulty:15,damage:{support:1.1,organization:.65,legitimacy:.65,pressure:1.05,lean:.45},incumbent:true},
 no_confidence:{title:'Demand a Change of Government',cost:24,desc:'Make the case publicly that the governing faction has lost its mandate and should yield control.',difficulty:17,damage:{support:1.25,organization:.75,legitimacy:1.25,pressure:1.35,lean:.6},incumbent:true,dayScale:true}
};
function legitimateOppositionActionState(locId,target){const ps=politicalSettlement(locId);if(!ps.legalOpposition||typeof ps.legalOpposition!=='object')ps.legalOpposition={};if(!ps.legalOpposition[target])ps.legalOpposition[target]={lastActionDay:-99,history:[]};return ps.legalOpposition[target]}
function legitimateOppositionDayState(locId){const ps=politicalSettlement(locId),day=state.world.day;if(!ps.legalOppositionDay||ps.legalOppositionDay.day!==day)ps.legalOppositionDay={day,count:0,used:[]};if(!Array.isArray(ps.legalOppositionDay.used))ps.legalOppositionDay.used=[];if(!Number.isFinite(ps.legalOppositionDay.count))ps.legalOppositionDay.count=0;return ps.legalOppositionDay}
function legitimateOppositionScale(locId){const n=legitimateOppositionDayState(locId).count;return n<=0?1:n===1?.8:n===2?.65:.5}
function legitimateOppositionIncumbentMultiplier(locId,target,a){if(settlementControl(locId)!==target)return 1;let mult=1.25;if(a?.context){const ss=settlementState(locId),rr=roadRights(locId);if(ss.security<45)mult+=.1;if(ss.prosperity<45)mult+=.1;if(rr.openness<=4)mult+=.1}return Math.min(1.55,mult)}
function executeLegitimateOppositionAction(locId,target,id){
 const a=LEGITIMATE_OPPOSITION_ACTIONS[id];if(!a||!OPEN_WORLD_FACTIONS[target])return showLegitimateOppositionActions(locId,target);const os=legitimateOppositionActionState(locId,target),ds=legitimateOppositionDayState(locId),rep=localReputation(locId),standing=state.world.factionStanding[target]||0,key=`${target}:${id}`;if(ds.count>=4)return actionResult('Political Work Exhausted',`You have already led four major counter-political actions in ${worldLocation(locId).name} today.`,'info',()=>showLegitimateOppositionActions(locId,target));if(ds.used.includes(key))return actionResult('Action Already Used Today',`You have already used ${a.title.toLowerCase()} against ${majorFaction(target).short} today.`,'info',()=>showLegitimateOppositionActions(locId,target));if(state.gold<a.cost)return actionResult('Not Enough Gold',`${a.title} requires ${a.cost} gold.`,'bad',()=>showLegitimateOppositionActions(locId,target));
 return politicalActionTransaction(a.title,()=>showLegitimateOppositionActions(locId,target),()=>{ensureLocalPoliticalLeadership(locId);const before=politicalOutcomeSnapshot(locId,[target,localPoliticalRival(locId,target)]),ss=settlementState(locId),leader=politicalLeaderCandidates(locId,target)[0],leaderStrength=leader?.a?.support||2,contextBonus=a.context?((ss.security<45?2:0)+(ss.prosperity<45?2:0)+(roadRights(locId).openness<=4?1:0)):0,difficulty=a.difficulty+Math.floor(localPoliticalProfile(locId,target).legitimacy/25)+Math.max(0,leaderStrength-3)-contextBonus,roll=rnd(1,20)+stat(state,'cha')+Math.floor(rep/3),success=roll>=difficulty;state.gold-=a.cost;let tone=success?'good':'bad',text,damage={...a.damage};
  const actionScale=legitimateOppositionScale(locId),incumbentMult=legitimateOppositionIncumbentMultiplier(locId,target,a);if(success){if(a.incumbent&&settlementControl(locId)!==target){for(const k of Object.keys(damage))damage[k]*=.6}if(a.context&&contextBonus===0)for(const k of Object.keys(damage))damage[k]*=.65;applyPoliticalDamage(locId,target,damage,actionScale*incumbentMult);text=`The Guardian’s ${a.title.toLowerCase()} lands effectively, weakening ${majorFaction(target).short} in ${worldLocation(locId).name}.`}
  else{const tc=localPoliticalFactionState(locId,target),backfire=id==='debate'?0.65:0.35;tc.support=clamp((tc.support||0)+backfire,-6,12);tc.legitimacy=clamp((tc.legitimacy||0)+(id==='debate'?.5:.2),-6,12);text=id==='debate'?`${majorFaction(target).short} gets the better of the public exchange and leaves with fresh momentum.`:`The public effort fails to land cleanly, giving ${majorFaction(target).short} a modest sympathy boost.`}
  os.lastActionDay=state.world.day;ds.count++;ds.used.push(key);os.history.push({day:state.world.day,id,success,text,actionScale});os.history=os.history.slice(-20);recordLocalPoliticalAction(locId,'Civic','legal_opposition',`${a.title} against ${majorFaction(target).short}: ${success?'effective':'unsuccessful'}.`);if(a.dayScale)advanceWorldDays(1,`${a.title} in ${worldLocation(locId).name}`);markLocalPoliticsDirty(locId);const after=politicalOutcomeSnapshot(locId,[target,localPoliticalRival(locId,target)]);save();return showPoliticalOutcome(a.title,text,before,after,{tone,success,notes:[`Target: ${majorFaction(target).name}`,settlementControl(locId)===target?'The governing faction is more exposed to attacks on its public record.':'The target does not currently govern this settlement.',`Public political action • ${a.cost} gold`,a.dayScale?'This was a day-scale organizing effort.':'This action occurred within the current campaign day.'],back:()=>politicalActionReturnToActivities(locId)})},{location:worldLocation(locId)?.name||locId,faction:majorFaction(target)?.short||target})
}
function showLegitimateOppositionActions(locId=state.world.location,target=null){modalRouteEnter('politicalOpposition',Array.from(arguments));ensureLocalPoliticalLeadership(locId);const factions=localPoliticalFactions(locId);if(!target){overlay(`<h2>${esc(worldLocation(locId).name)} — Oppose a Faction</h2><p>Use lawful public politics to weaken a rival faction without resorting to covert or criminal action.</p><div class="political-profile-list">${localPoliticalGlanceRowsHTML(locId,'activities')}</div><div class="choice-list">${factions.map(f=>{const p=localPoliticalProfile(locId,f);return `<button class="political-action-faction" data-oppositiontarget="${f}"><span><b>${esc(majorFaction(f).name)}</b><small>${esc(politicalSupportLabel(p.publicSupport))} support • ${esc(politicalLegitimacyLabel(p.legitimacy))}</small></span><b>${p.overall}</b></button>`}).join('')}</div><div class="dialog-footer"><button id="oppositionBack">Back to Political Activities</button></div>`,true);document.querySelectorAll('[data-oppositiontarget]').forEach(b=>b.onclick=()=>showLegitimateOppositionActions(locId,b.dataset.oppositiontarget));document.querySelectorAll('[data-politicalfaction]').forEach(b=>b.onclick=()=>showLegitimateOppositionActions(locId,b.dataset.politicalfaction));$('#oppositionBack').onclick=()=>SOSServices.navigation.back(()=>showLocalPoliticalActions(locId));return}
 const os=legitimateOppositionActionState(locId,target),ds=legitimateOppositionDayState(locId),leader=politicalLeaderCandidates(locId,target)[0],limitReached=ds.count>=4;overlay(`<h2>Oppose ${esc(majorFaction(target).short)} — ${esc(worldLocation(locId).name)}</h2><div class="notice compact"><b>Legal political opposition</b><br>${leader?`Visible local representative: <b>${esc(leader.n.name)}</b> — ${esc(typeof npcPoliticalRoleLabel==='function'?npcPoliticalRoleLabel(leader.n,leader.a):leader.n.role)}`:'No prominent representative is currently visible.'}<br><small>${limitReached?'You have already led four major counter-political actions today.':`You may lead ${4-ds.count} more major counter-political action${4-ds.count===1?'':'s'} today. Repeating the same tactic against the same faction must wait until tomorrow.`}</small></div><div class="choice-list">${Object.entries(LEGITIMATE_OPPOSITION_ACTIONS).map(([id,a])=>{const used=ds.used.includes(`${target}:${id}`);return `<button data-oppositionaction="${id}" ${limitReached||used?'disabled':''}><b>${esc(a.title)}</b><br><small>${esc(a.desc)} • ${a.cost}g${a.dayScale?' • advances 1 day':''}${ds.count===1?' • reduced effect':ds.count===2?' • further reduced effect':ds.count>=3?' • substantially reduced effect':''}</small></button>`}).join('')}</div><div class="dialog-footer"><button id="oppositionTargetBack">Back to Faction Selection</button></div>`,true);document.querySelectorAll('[data-oppositionaction]').forEach(b=>b.onclick=()=>executeLegitimateOppositionAction(locId,target,b.dataset.oppositionaction));$('#oppositionTargetBack').onclick=()=>SOSServices.navigation.back(()=>showLegitimateOppositionActions(locId,null))
}

function showFactionCivicActions(locId,faction,parent='politics'){modalRouteEnter(SOSText("politics_campaigns_civic.showFactionCivicActions.001"),Array.from(arguments));
 const p=localPoliticalProfile(locId,faction),standing=state.world.factionStanding[faction]||0;
 overlay(SOSText("politics_campaigns_civic.showFactionCivicActions.002",esc(worldLocation(locId).name),esc(majorFaction(faction).short),esc(politicalSupportLabel(p.publicSupport)),esc(politicalOrganizationLabel(p.organization)),esc(politicalLegitimacyLabel(p.legitimacy)),standing>=0?'+':'',standing,guardianPublicEndorsement().faction?`Guardian public endorsement: <b>${esc(majorFaction(guardianPublicEndorsement().faction).short)}</b> since Day ${guardianPublicEndorsement().day}`:'Guardian public endorsement: <b>None</b>',Object.entries(LOCAL_POLITICAL_ACTIONS).map(([id,a])=>{const cost=politicalActionCost(locId,id),es=id==='endorse'?guardianEndorsementButtonState(faction):null,locked=(id==='organize'&&standing<2)||!!es?.disabled,label=es?.label||a.title,desc=id==='organize'&&standing<2?'Requires faction standing 2.':es?.reason||a.desc;return `<button data-civicaction="${id}" ${locked?'disabled':''}><b>${esc(label)}</b><br><small>${esc(desc)}${cost?` • ${cost}g`:''}</small></button>`}).join('')),true);
 document.querySelectorAll('[data-civicaction]').forEach(b=>b.onclick=()=>executeLocalPoliticalAction(locId,faction,b.dataset.civicaction));$('#seekPoliticalEndorsement').onclick=()=>showPoliticalEndorsementPeople(locId,faction);$('#civicFactionBack').onclick=()=>parent===SOSText("politics_campaigns_civic.showFactionCivicActions.003")&&townNavCurrent?townNavBackOrExit():showLocalPoliticalActions(locId)
}
function showIndependentCivicActions(locId){modalRouteEnter(SOSText("politics_campaigns_civic.showIndependentCivicActions.001"),Array.from(arguments));
 const ps=politicalSettlement(locId);overlay(SOSText("politics_campaigns_civic.showIndependentCivicActions.002",esc(worldLocation(locId).name),ps.autonomy),true);document.querySelectorAll('[data-independentcivic]').forEach(b=>b.onclick=()=>executeIndependentCivicAction(locId,b.dataset.independentcivic));$('#independentCivicBack').onclick=()=>townNavCurrent?.route==='independentCivic'?townNavBackOrExit():showLocalPoliticalActions(locId)
}
function showPoliticalCampaignDesk(locId=state.world.location,faction=null,parent='politics'){modalRouteEnter(SOSText("politics_campaigns_civic.showPoliticalCampaignDesk.001"),Array.from(arguments));
 if(!faction){
  const factions=localPoliticalFactions(locId);overlay(SOSText("politics_campaigns_civic.showPoliticalCampaignDesk.002",esc(worldLocation(locId).name),factions.map(f=>{const c=politicalCampaignState(locId,f),need=politicalCampaignNeed(locId,f),existing=politicalCampaignActiveOrOffered(locId,f);return `<button class="political-action-faction" data-campaignfaction="${f}"><span><b>${esc(majorFaction(f).name)}</b><small>${esc(need.label)}${need.rival?` • Rival: ${esc(majorFaction(need.rival).short)}`:''}${existing?` • ${esc(contractStatusLabel(existing))}: ${esc(existing.name)}`:''}</small></span><b>${esc(politicalCampaignMomentumLabel(c.momentum))}</b></button>`}).join('')),true);document.querySelectorAll('[data-campaignfaction]').forEach(b=>b.onclick=()=>showPoliticalCampaignDesk(locId,b.dataset.campaignfaction));$('#campaignDeskBack').onclick=()=>SOSServices.navigation.back(()=>showSettlementPolitics(locId));return
 }
 const c=politicalCampaignState(locId,faction),need=politicalCampaignNeed(locId,faction),existing=politicalCampaignActiveOrOffered(locId,faction),standing=state.world.factionStanding[faction]||0,cooldown=Math.max(0,2-(state.world.day-(c.lastCommissionDay||-99))),recent=(c.history||[]).slice(-6).reverse();
 overlay(SOSText("politics_campaigns_civic.showPoliticalCampaignDesk.003",esc(worldLocation(locId).name),esc(majorFaction(faction).short),esc(need.label),esc(need.reason),need.rival?`<br><b>Main rival:</b> ${esc(majorFaction(need.rival).name)}`:'',esc(politicalCampaignMomentumLabel(c.momentum)),c.momentum.toFixed(1),c.successes||0,c.failures||0,existing?`<div class="regional-contract-source"><b>${esc(existing.name)}</b><br>${esc(contractStatusLabel(existing))}<br><small>${esc(existing.desc)}</small><br><button id="campaignExistingContract">Review Contract</button></div>`:`<button id="campaignCommission" ${standing<0||cooldown>0?'disabled':''}><b>Request Political Campaign Work</b><br><small>${standing<0?'Faction standing must be nonnegative':cooldown>0?`New commission available in ${cooldown} day${cooldown===1?'':'s'}`:`Commission work aimed at: ${esc(need.label)}`}</small></button>`,recent.map(x=>`<div class="card compact"><b>Day ${x.day}</b> — ${esc(x.text)}</div>`).join('')||'<p class="muted">No organized campaign history yet.</p>'),true);
 if($('#campaignExistingContract'))$('#campaignExistingContract').onclick=()=>showContractDetails(existing.id);if($('#campaignCommission'))$('#campaignCommission').onclick=()=>{const before=politicalOutcomeSnapshot(locId,[faction]),q=generatePoliticalCampaignContract(locId,faction,true);if(!q)return actionResult(SOSText("politics_campaigns_civic.showPoliticalCampaignDesk.004"),SOSText("politics_campaigns_civic.showPoliticalCampaignDesk.005"),'info',()=>showPoliticalCampaignDesk(locId,faction));const after=politicalOutcomeSnapshot(locId,[faction]);save();showPoliticalOutcome(SOSText("politics_campaigns_civic.showPoliticalCampaignDesk.006"),SOSText("politics_campaigns_civic.showPoliticalCampaignDesk.007",q.name),before,after,{tone:'info',notes:[SOSText("politics_campaigns_civic.showPoliticalCampaignDesk.008",q.politicalNeed),SOSText("politics_campaigns_civic.showPoliticalCampaignDesk.009",politicalCampaignEffectText(q))],back:()=>showContractBoard(locId)})};$('#campaignFactionBack').onclick=()=>parent===SOSText("politics_campaigns_civic.showPoliticalCampaignDesk.010")&&townNavCurrent?townNavBackOrExit():showPoliticalCampaignDesk(locId)
}
const POLITICAL_COVERT_ACTIONS={
 garbage:{title:SOSText("politics_campaigns_civic.showPoliticalCampaignDesk.011"),desc:SOSText("politics_campaigns_civic.showPoliticalCampaignDesk.012"),cost:18,success:88,exposure:22,evidence:18,skill:'cha',crime:'trespass',severity:1,effect:{organization:1.35,support:.45},benefit:{support:.3},petty:true},
 notices:{title:SOSText("politics_campaigns_civic.showPoliticalCampaignDesk.013"),desc:SOSText("politics_campaigns_civic.showPoliticalCampaignDesk.014"),cost:10,success:82,exposure:25,evidence:24,skill:'dex',crime:'trespass',severity:1,effect:{organization:.875,support:.625},benefit:{organization:.3}},
 redirect:{title:SOSText("politics_campaigns_civic.showPoliticalCampaignDesk.015"),desc:SOSText("politics_campaigns_civic.showPoliticalCampaignDesk.016"),cost:25,success:68,exposure:34,evidence:42,skill:'cha',crime:'theft',severity:2,effect:{organization:1.4625,merchant:2.025},benefit:{merchant:.6,organization:.25}},
 records:{title:SOSText("politics_campaigns_civic.showPoliticalCampaignDesk.017"),desc:SOSText("politics_campaigns_civic.showPoliticalCampaignDesk.018"),cost:28,success:59,exposure:41,evidence:52,skill:'dex',crime:'theft',severity:3,effect:{organization:2.43,support:.45},benefit:{organization:.55}},
 stockpile:{title:SOSText("politics_campaigns_civic.showPoliticalCampaignDesk.019"),desc:SOSText("politics_campaigns_civic.showPoliticalCampaignDesk.020"),cost:36,success:53,exposure:51,evidence:66,skill:'dex',crime:'robbery',severity:4,effect:{organization:1.875,merchant:1.575,security:.375},benefit:{organization:.65,merchant:.35}},
 supporter:{title:SOSText("politics_campaigns_civic.showPoliticalCampaignDesk.021"),desc:SOSText("politics_campaigns_civic.showPoliticalCampaignDesk.022"),cost:22,success:62,exposure:47,evidence:56,skill:'dex',crime:'assault',severity:3,effect:{support:1.4,organization:1.3125},benefit:{support:.4,organization:.3},named:true},
 forged_letters:{title:'Plant Forged Correspondence',desc:'Plant convincing letters or records that appear to implicate the rival faction in corruption, collusion, or betrayal.',cost:35,success:58,exposure:42,evidence:58,skill:'cha',crime:'fraud',severity:3,effect:{support:.6125,organization:.6125,legitimacy:2.1875},benefit:{support:.3,legitimacy:.25}},
 event_sabotage:{title:'Sabotage Rival Public Event',desc:'Disrupt a rally, speech, fundraiser, or organizing event before it can build momentum.',cost:30,success:66,exposure:44,evidence:50,skill:'dex',crime:'vandalism',severity:2,effect:{support:.8,organization:1.8},benefit:{organization:.4}},
 falseflag_market:{title:'Stage False-Flag Attack on Market District',desc:'Acquire rival colors and identifying material, attack the local Market District, and try to make witnesses blame the selected faction.',cost:60,success:64,exposure:56,evidence:66,skill:'dex',crime:'robbery',severity:5,effect:{},benefit:{},special:'falseflag_market'}
};

function politicalLeaderInjuryDuration(npcId,day){const seed=[...String(npcId||'leader')].reduce((n,c)=>n+c.charCodeAt(0),0)+(day||0);return 7+(seed%8)}
function refreshPoliticalLeaderInjuries(locId){
 const c=politicalCovertState(locId);
 // Repair legacy successful wound raids that predate explicit recovery tracking.
 for(const h of c.history||[]){if(h?.id!=='leader_wound'||!h.npcId||c.deadNpcs[h.npcId]||c.injuredNpcs[h.npcId]||(c.recoveredWounds[h.npcId]||-1)>=h.day)continue;const a=npcFactionAlignment(h.npcId),days=politicalLeaderInjuryDuration(h.npcId,h.day);c.injuredNpcs[h.npcId]={day:h.day,untilDay:h.day+days,target:h.target,originalSupport:Math.max(3,(a.support||0)+2),legacy:true}}
 for(const [npcId,inj] of Object.entries(c.injuredNpcs)){if(!inj||c.deadNpcs[npcId]){delete c.injuredNpcs[npcId];continue}if(state.world.day<(inj.untilDay||0))continue;const a=npcFactionAlignment(npcId);a.support=clamp(Math.max(a.support||0,Math.max(3,(inj.originalSupport||3)-1)),-3,5);a.public=true;a.reason=`Recovered from political-raid injuries on Day ${state.world.day}.`;c.recoveredWounds[npcId]=inj.day||state.world.day;delete c.injuredNpcs[npcId];npcMemoryAdd(npcId,'Recovered from injuries sustained in a political attack.',0)}
 return c.injuredNpcs
}
function politicalLeaderInjury(locId,npcId){refreshPoliticalLeaderInjuries(locId);return politicalCovertState(locId).injuredNpcs[npcId]||null}
function injurePoliticalLeader(locId,npcId,target,originalSupport){const c=politicalCovertState(locId),days=politicalLeaderInjuryDuration(npcId,state.world.day),untilDay=state.world.day+days;c.injuredNpcs[npcId]={day:state.world.day,untilDay,target,originalSupport:Math.max(3,originalSupport||3)};return c.injuredNpcs[npcId]}
function politicalCovertTargetPeople(locId,faction){refreshPoliticalLeaderInjuries(locId);const c=politicalCovertState(locId);return settlementNpcsPresent(locId).map(n=>({n,a:npcFactionAlignment(n.id),r:npcRelationshipState(n.id)})).filter(x=>x.a?.faction===faction&&(x.a.support||0)>=2&&!c.deadNpcs[x.n.id]&&!c.injuredNpcs[x.n.id]).sort((a,b)=>(b.a.support||0)-(a.a.support||0)||(b.r.familiarity||0)-(a.r.familiarity||0))}
function politicalCovertTargetLabel(locId,faction){const top=politicalCovertTargetPeople(locId,faction)[0];return top?`${top.n.name} (${top.n.role})`:factionPostName(locId,faction)}
function politicalCovertOdds(locId,target,id){const a=POLITICAL_COVERT_ACTIONS[id],p=localPoliticalProfile(locId,target),ss=settlementState(locId),skill=a.skill==='cha'?stat(state,'cha'):stat(state,'dex')+Math.floor((state.scouting||0)/2),fame=Math.max(0,localReputation(locId));return {success:clamp(Math.round(a.success+(skill-8)*2-p.organization*.08),25,95),exposure:clamp(Math.round(a.exposure+ss.security*.12+p.organization*.10+fame*.8-(stat(state,'dex')-8)*1.4-(state.scouting||0)),8,92),evidence:clamp(Math.round(a.evidence+ss.security*.14),10,94)}}
