function politicalCampaignMomentumLabel(v){return v>=6?'Surging':v>=3?'Strong':v>=1?'Building':v<=-4?'Badly stalled':v<=-1?'Stalled':SOSText("politics_campaigns_civic.politicalCampaignMomentumLabel.001")}
function politicalCampaignNeed(locId,faction){
 const p=localPoliticalProfile(locId,faction),rival=localPoliticalRival(locId,faction),rp=rival?localPoliticalProfile(locId,rival):null,ps=politicalSettlement(locId),control=settlementControl(locId);
 if(ps.pending?.challenger&&ps.pending.challenger!==faction)return {metric:'counter',label:SOSText("politics_campaigns_civic.politicalCampaignNeed.001",majorFaction(ps.pending.challenger).short),rival:ps.pending.challenger,reason:SOSText("politics_campaigns_civic.politicalCampaignNeed.002",majorFaction(ps.pending.challenger).short)};
 if(rival&&rp&&(rp.overall>=p.overall-3||settlementLeanScore(locId,rival)>=settlementLeanScore(locId,faction)-1))return {metric:'counter',label:SOSText("politics_campaigns_civic.politicalCampaignNeed.003",majorFaction(rival).short),rival,reason:SOSText("politics_campaigns_civic.politicalCampaignNeed.004",majorFaction(rival).short,majorFaction(faction).short)};
 const deficits=[
  {metric:'legitimacy',label:SOSText("politics_campaigns_civic.politicalCampaignNeed.005"),score:62-p.legitimacy,reason:SOSText("politics_campaigns_civic.politicalCampaignNeed.006")},
  {metric:'support',label:SOSText("politics_campaigns_civic.politicalCampaignNeed.007"),score:60-p.publicSupport,reason:SOSText("politics_campaigns_civic.politicalCampaignNeed.008")},
  {metric:'organization',label:SOSText("politics_campaigns_civic.politicalCampaignNeed.009"),score:58-p.organization,reason:SOSText("politics_campaigns_civic.politicalCampaignNeed.010")},
  {metric:'merchant',label:SOSText("politics_campaigns_civic.politicalCampaignNeed.011"),score:52-p.merchantBacking,reason:SOSText("politics_campaigns_civic.politicalCampaignNeed.012")},
  {metric:'security',label:SOSText("politics_campaigns_civic.politicalCampaignNeed.013"),score:52-p.securityInfluence,reason:SOSText("politics_campaigns_civic.politicalCampaignNeed.014")}
 ].sort((a,b)=>b.score-a.score);
 const need=deficits[0];need.rival=rival;if(control===faction&&p.legitimacy<55){need.metric='legitimacy';need.label=SOSText("politics_campaigns_civic.politicalCampaignNeed.015");need.reason=SOSText("politics_campaigns_civic.politicalCampaignNeed.016")}return need
}
const POLITICAL_CAMPAIGN_NAMES={
 Redstone:{support:SOSText("politics_campaigns_civic.politicalCampaignNeed.017"),organization:SOSText("politics_campaigns_civic.politicalCampaignNeed.018"),legitimacy:SOSText("politics_campaigns_civic.politicalCampaignNeed.019"),merchant:SOSText("politics_campaigns_civic.politicalCampaignNeed.020"),security:SOSText("politics_campaigns_civic.politicalCampaignNeed.021"),counter:SOSText("politics_campaigns_civic.politicalCampaignNeed.022")},
 Independent:{support:SOSText("politics_campaigns_civic.politicalCampaignNeed.023"),organization:SOSText("politics_campaigns_civic.politicalCampaignNeed.024"),legitimacy:SOSText("politics_campaigns_civic.politicalCampaignNeed.025"),merchant:SOSText("politics_campaigns_civic.politicalCampaignNeed.026"),security:SOSText("politics_campaigns_civic.politicalCampaignNeed.027"),counter:SOSText("politics_campaigns_civic.politicalCampaignNeed.028")},
 Coalition:{support:SOSText("politics_campaigns_civic.politicalCampaignNeed.029"),organization:SOSText("politics_campaigns_civic.politicalCampaignNeed.030"),legitimacy:SOSText("politics_campaigns_civic.politicalCampaignNeed.031"),merchant:SOSText("politics_campaigns_civic.politicalCampaignNeed.032"),security:SOSText("politics_campaigns_civic.politicalCampaignNeed.033"),counter:SOSText("politics_campaigns_civic.politicalCampaignNeed.034")},
 Bluestone:{support:SOSText("politics_campaigns_civic.politicalCampaignNeed.035"),organization:SOSText("politics_campaigns_civic.politicalCampaignNeed.036"),legitimacy:SOSText("politics_campaigns_civic.politicalCampaignNeed.037"),merchant:SOSText("politics_campaigns_civic.politicalCampaignNeed.038"),security:SOSText("politics_campaigns_civic.politicalCampaignNeed.039"),counter:SOSText("politics_campaigns_civic.politicalCampaignNeed.040")},
 Shantium:{support:SOSText("politics_campaigns_civic.politicalCampaignNeed.041"),organization:SOSText("politics_campaigns_civic.politicalCampaignNeed.042"),legitimacy:SOSText("politics_campaigns_civic.politicalCampaignNeed.043"),merchant:SOSText("politics_campaigns_civic.politicalCampaignNeed.044"),security:SOSText("politics_campaigns_civic.politicalCampaignNeed.045"),counter:SOSText("politics_campaigns_civic.politicalCampaignNeed.046")},
 Spawn:{support:SOSText("politics_campaigns_civic.politicalCampaignNeed.047"),organization:SOSText("politics_campaigns_civic.politicalCampaignNeed.048"),legitimacy:SOSText("politics_campaigns_civic.politicalCampaignNeed.049"),merchant:SOSText("politics_campaigns_civic.politicalCampaignNeed.050"),security:SOSText("politics_campaigns_civic.politicalCampaignNeed.051"),counter:SOSText("politics_campaigns_civic.politicalCampaignNeed.052")},
 Mercenaries:{support:SOSText("politics_campaigns_civic.politicalCampaignNeed.053"),organization:SOSText("politics_campaigns_civic.politicalCampaignNeed.054"),legitimacy:SOSText("politics_campaigns_civic.politicalCampaignNeed.055"),merchant:SOSText("politics_campaigns_civic.politicalCampaignNeed.056"),security:SOSText("politics_campaigns_civic.politicalCampaignNeed.057"),counter:SOSText("politics_campaigns_civic.politicalCampaignNeed.058")}
};
function politicalCampaignType(metric,faction){
 if(metric==='security')return chance(.55)?'visit':'hunt';
 if(metric==='merchant')return chance(.55)?'delivery':'diplomacy';
 if(metric==='organization')return chance(.55)?'delivery':'visit';
 if(metric==='legitimacy')return chance(.62)?'procure':'visit';
 if(metric==='counter')return'diplomacy';
 return chance(.55)?'diplomacy':'visit'
}
function politicalCampaignEffects(metric){
 const rows={
  support:{support:1.8,organization:.5,legitimacy:.25,power:2.5,pressure:.7,rivalSupport:.55,rivalOrganization:.15},
  organization:{support:.6,organization:2,legitimacy:.2,power:2.6,pressure:1,presence:1,rivalSupport:.2,rivalOrganization:.45},
  legitimacy:{support:1,organization:.25,legitimacy:2,merchant:.4,power:2.7,pressure:.65,rivalSupport:.4,rivalOrganization:.15},
  merchant:{support:.7,organization:.35,merchant:2,legitimacy:.25,power:2.6,pressure:.55,rivalSupport:.3,rivalMerchant:.6},
  security:{support:.55,organization:.5,legitimacy:.75,security:2,power:3,pressure:.8,rivalSupport:.3,rivalOrganization:.2},
  counter:{support:1,organization:1,legitimacy:.2,power:2.8,pressure:1.1,rivalSupport:1.2,rivalOrganization:.8}
 };return {...(rows[metric]||rows.support)}
}
function politicalCampaignChannel(metric){return metric==='merchant'||metric==='legitimacy'?'trade':metric==='security'?'security':metric==='organization'?'personnel':'politics'}
function politicalCampaignEffectText(q){
 const e=q?.politicalEffects||{},bits=[];if(e.support)bits.push(SOSText("politics_campaigns_civic.politicalCampaignEffectText.001",e.support));if(e.organization)bits.push(SOSText("politics_campaigns_civic.politicalCampaignEffectText.002",e.organization));if(e.legitimacy)bits.push(SOSText("politics_campaigns_civic.politicalCampaignEffectText.003",e.legitimacy));if(e.merchant)bits.push(SOSText("politics_campaigns_civic.politicalCampaignEffectText.004",e.merchant));if(e.security)bits.push(SOSText("politics_campaigns_civic.politicalCampaignEffectText.005",e.security));if(e.rivalSupport)bits.push(SOSText("politics_campaigns_civic.politicalCampaignEffectText.006",e.rivalSupport));if(e.rivalOrganization)bits.push(SOSText("politics_campaigns_civic.politicalCampaignEffectText.007",e.rivalOrganization));return bits.join(' • ')
}
function politicalCampaignDescription(locId,faction,need,type,target){
 const here=worldLocation(locId).name,to=worldLocation(target)?.name||here,priority=currentFactionPriority(faction).label;
 if(need.metric==='support')return SOSText("politics_campaigns_civic.politicalCampaignDescription.001",majorFaction(faction).name,here,priority.toLowerCase());
 if(need.metric==='organization')return SOSText("politics_campaigns_civic.politicalCampaignDescription.002",majorFaction(faction).short,here,to);
 if(need.metric==='legitimacy')return SOSText("politics_campaigns_civic.politicalCampaignDescription.003",majorFaction(faction).short,here);
 if(need.metric==='merchant')return SOSText("politics_campaigns_civic.politicalCampaignDescription.004",majorFaction(faction).short,here,to);
 if(need.metric==='security')return SOSText("politics_campaigns_civic.politicalCampaignDescription.005",majorFaction(faction).short,here);
 return SOSText("politics_campaigns_civic.politicalCampaignDescription.006",majorFaction(faction).short,majorFaction(need.rival).short)
}
function politicalCampaignActiveOrOffered(locId,faction){
 return [...(state.world.quests||[]),...(state.world.contracts?.[locId]||[])].find(q=>q.politicalCampaign&&q.politicalLocId===locId&&q.politicalFaction===faction&&['offered','active','ready'].includes(q.status))
}
function generatePoliticalCampaignContract(locId,faction,force=false){
 if(!OPEN_WORLD_FACTIONS[faction]||!state.world.settlements?.[locId])return null;const c=politicalCampaignState(locId,faction),standing=state.world.factionStanding[faction]||0;
 if(!force&&state.world.day-(c.lastCommissionDay||-99)<2)return null;if(politicalCampaignActiveOrOffered(locId,faction))return null;if(standing<0)return null;
 const need=politicalCampaignNeed(locId,faction),type=politicalCampaignType(need.metric,faction),same=regionalSettlements(locationRegion(locId)).filter(x=>x.id!==locId&&!x.hidden),target=(type==='procure'?locId:(pick(same)?.id||locId)),q=generateContract(locId,type,{target,faction});
 q.politicalCampaign=true;q.politicalLocId=locId;q.politicalFaction=faction;q.politicalRival=need.rival||null;q.politicalMetric=need.metric;q.politicalNeed=need.label;q.politicalReason=need.reason;q.politicalEffects=politicalCampaignEffects(need.metric);q.politicalChannel=politicalCampaignChannel(need.metric);q.chainKey=`politics:${locId}:${faction}:${need.metric}`;q.name=POLITICAL_CAMPAIGN_NAMES[faction]?.[need.metric]||SOSText("politics_campaigns_civic.generatePoliticalCampaignContract.001",majorFaction(faction).short);q.variantName=q.name;q.desc=politicalCampaignDescription(locId,faction,need,type,q.target);q.reward+=28+Math.max(0,Math.round((localPoliticalProfile(locId,need.rival||faction).overall-localPoliticalProfile(locId,faction).overall)*.5));q.paymentMode='origin_agent';q.paymentLocation=locId;q.paymentPayer=contractPaymentAgentLabel(q,locId,'origin_agent');q.paymentExplanation=SOSText("politics_campaigns_civic.generatePoliticalCampaignContract.002",q.paymentPayer,worldLocation(locId).name);
 c.lastCommissionDay=state.world.day;c.history.push({day:state.world.day,type:'commissioned',contractId:q.id,text:SOSText("politics_campaigns_civic.generatePoliticalCampaignContract.003",q.name,need.label.toLowerCase())});c.history=c.history.slice(-20);
 state.world.contracts[locId]=state.world.contracts[locId]||[];state.world.contracts[locId].unshift(q);state.world.contracts[locId]=state.world.contracts[locId].slice(0,4);recordLocalPoliticalAction(locId,faction,'campaign_commission',SOSText("politics_campaigns_civic.generatePoliticalCampaignContract.004",majorFaction(faction).short,q.name,need.reason));return q
}
function applyPoliticalCampaignConsequences(q){
 if(!q?.politicalCampaign||q.politicalConsequencesApplied)return'';q.politicalConsequencesApplied=true;const locId=q.politicalLocId||q.origin,faction=q.politicalFaction||q.faction,e=q.politicalEffects||{},c=politicalCampaignState(locId,faction),rival=q.politicalRival,before=politicalOutcomeSnapshot(locId,[faction,rival]);
 applyLocalPoliticalEffects(locId,faction,{support:e.support||0,organization:e.organization||0,legitimacy:e.legitimacy||0,merchant:e.merchant||0,security:e.security||0,power:e.power||0,pressure:e.pressure||0,presence:e.presence||0,days:12},SOSText("politics_campaigns_civic.applyPoliticalCampaignConsequences.001",q.name),q.politicalChannel||'politics');
 if(rival&&OPEN_WORLD_FACTIONS[rival]){const rc=localPoliticalFactionState(locId,rival);rc.support=clamp((rc.support||0)-(e.rivalSupport||0),-6,12);rc.organization=clamp((rc.organization||0)-(e.rivalOrganization||0),-6,12);rc.merchant=clamp((rc.merchant||0)-(e.rivalMerchant||0),-6,12);politicalSettlement(locId).pressure[rival]=Math.max(0,(politicalSettlement(locId).pressure[rival]||0)-((e.rivalSupport||0)+(e.rivalOrganization||0))*.25)}
 c.successes++;c.momentum=clamp(c.momentum+2,-8,10);adjustPoliticalCapital(locId,faction,4,SOSText("politics_campaigns_civic.applyPoliticalCampaignConsequences.002",q.name,majorFaction(faction).short));c.heat=clamp(c.heat+2.25,0,10);c.lastResultDay=state.world.day;c.history.push({day:state.world.day,type:'success',contractId:q.id,text:`${q.name} succeeds. ${politicalCampaignEffectText(q)}`});c.history=c.history.slice(-20);recordLocalPoliticalAction(locId,faction,'campaign_success',SOSText("politics_campaigns_civic.applyPoliticalCampaignConsequences.003",q.name,majorFaction(faction).short));q.politicalOutcome={before,after:politicalOutcomeSnapshot(locId,[faction,rival]),notes:[SOSText("politics_campaigns_civic.applyPoliticalCampaignConsequences.004",politicalCampaignMomentumLabel(c.momentum))]};return politicalCampaignEffectText(q)
}
function applyPoliticalCampaignFailure(q,reason=SOSText("politics_campaigns_civic.applyPoliticalCampaignFailure.001"),abandoned=false){
 if(!q?.politicalCampaign||q.politicalFailureApplied||q.politicalConsequencesApplied)return'';q.politicalFailureApplied=true;const locId=q.politicalLocId||q.origin,faction=q.politicalFaction||q.faction,c=politicalCampaignState(locId,faction),fc=localPoliticalFactionState(locId,faction),rival=q.politicalRival,before=politicalOutcomeSnapshot(locId,[faction,rival]);
 fc.organization=clamp((fc.organization||0)-(abandoned?.75:.4),-6,12);fc.legitimacy=clamp((fc.legitimacy||0)-(abandoned?.45:.2),-6,12);if(rival&&OPEN_WORLD_FACTIONS[rival]){const rc=localPoliticalFactionState(locId,rival);rc.support=clamp((rc.support||0)+(abandoned?.65:.4),-6,12)}
 c.failures++;c.momentum=clamp(c.momentum-(abandoned?2:1),-8,10);adjustPoliticalCapital(locId,faction,-(abandoned?2:1),SOSText("politics_campaigns_civic.applyPoliticalCampaignFailure.002",q.name));c.heat=clamp(c.heat+.5,0,10);c.lastResultDay=state.world.day;c.history.push({day:state.world.day,type:abandoned?'abandoned':'failed',contractId:q.id,text:`${q.name}: ${reason}`});c.history=c.history.slice(-20);recordLocalPoliticalAction(locId,faction,'campaign_failure',SOSText("politics_campaigns_civic.applyPoliticalCampaignFailure.003",q.name,majorFaction(faction).short));q.politicalOutcome={before,after:politicalOutcomeSnapshot(locId,[faction,rival]),notes:[reason]};return SOSText("politics_campaigns_civic.applyPoliticalCampaignFailure.004")
}
function simulateLocalPoliticalCampaignDay(locId){
 const ps=politicalSettlement(locId);for(const [f,c] of Object.entries(ps.campaigns||{})){if(!OPEN_WORLD_FACTIONS[f])continue;c.heat=Math.max(0,(c.heat||0)-.28);c.momentum=(c.momentum||0)*.985;if(c.heat<1.2)continue;const rival=localPoliticalRival(locId,f);if(!rival)continue;const rp=localPoliticalProfile(locId,rival),chanceCounter=clamp(.045+c.heat*.012+rp.organization/1700,.04,.22);if(!chance(chanceCounter))continue;const rc=localPoliticalFactionState(locId,rival),fc=localPoliticalFactionState(locId,f),strength=rp.organization>=65?.55:.35;rc.support=clamp((rc.support||0)+strength,-6,12);rc.organization=clamp((rc.organization||0)+strength*.6,-6,12);fc.support=clamp((fc.support||0)-strength*.25,-6,12);ps.pressure[rival]=clamp((ps.pressure[rival]||0)+.15,0,12);c.heat=Math.max(0,c.heat-.8);const text=SOSText("politics_campaigns_civic.simulateLocalPoliticalCampaignDay.001",majorFaction(rival).short,majorFaction(f).short);ps.civicHistory.push({day:state.world.day,faction:rival,action:'counter_campaign',text});ps.civicHistory=ps.civicHistory.slice(-30);if(chance(.28))recordWorldNews(SOSText("politics_campaigns_civic.simulateLocalPoliticalCampaignDay.002",worldLocation(locId).name,majorFaction(rival).short),'info')}
}
function politicalCampaignSourceHTML(q){
 if(!q?.politicalCampaign)return'';return SOSText("politics_campaigns_civic.politicalCampaignSourceHTML.001",esc(majorFaction(q.politicalFaction||q.faction).name),esc(worldLocation(q.politicalLocId||q.origin).name),esc(q.politicalNeed||'Strengthen the local campaign'),esc(q.politicalReason||''),esc(politicalCampaignEffectText(q)),q.politicalRival?`<br>Main rival: ${esc(majorFaction(q.politicalRival).short)}`:'')
}
function recordLocalPoliticalAction(locId,faction,action,text){
 const ps=politicalSettlement(locId),row={day:state.world.day,faction,action,text};ps.civicHistory.push(row);ps.civicHistory=ps.civicHistory.slice(-30);ps.lastCivicActionDay=state.world.day;politicalHistory(`${worldLocation(locId).name}: ${text}`,'info')
}
function applyLocalPoliticalEffects(locId,faction,effect,reason,channel='politics'){
 const ps=politicalSettlement(locId),c=localPoliticalFactionState(locId,faction),presence=state.world.factionPresence[locId]||(state.world.factionPresence[locId]={});
 for(const k of ['support','organization','legitimacy','merchant','security'])if(effect[k])c[k]=clamp((c[k]||0)+effect[k],-6,12);
 c.lastActionDay=state.world.day;
 if(effect.presence)presence[faction]=clamp((presence[faction]||0)+effect.presence,0,12);
 if(effect.pressure)ps.pressure[faction]=clamp((ps.pressure[faction]||0)+effect.pressure,0,12);
 if(effect.power)recordFactionPower(locId,faction,channel,effect.power,reason,effect.days||10);
 const rival=effect.rival?localPoliticalRival(locId,faction):null;
 if(rival){const rc=localPoliticalFactionState(locId,rival);rc.support=clamp((rc.support||0)-effect.rival,-6,12);ps.pressure[rival]=Math.max(0,(ps.pressure[rival]||0)-effect.rival*.35);ps.lean[rival]=clamp((ps.lean[rival]||0)-effect.rival*.25,-6,12)}
}
function decayLocalPoliticalCivic(locId){
 const ps=politicalSettlement(locId),control=settlementControl(locId),ss=settlementState(locId),rr=roadRights(locId);
 for(const [f,c] of Object.entries(ps.civic||{})){if(!OPEN_WORLD_FACTIONS[f])continue;if(state.world.day-(c.lastActionDay||0)>=6){for(const k of ['support','organization','legitimacy','merchant','security']){if(c[k]>0)c[k]=Math.max(0,c[k]-.12);else if(c[k]<0)c[k]=Math.min(0,c[k]+.08)}}}
 const ruling=localPoliticalFactionState(locId,control);if(ss.security<38)ruling.legitimacy=clamp(ruling.legitimacy-.10,-6,12);if(ss.prosperity<38)ruling.legitimacy=clamp(ruling.legitimacy-.10,-6,12);
 if(rr.openness<=3&&[SOSText("politics_campaigns_civic.decayLocalPoliticalCivic.001"),SOSText("politics_campaigns_civic.decayLocalPoliticalCivic.002")].includes(control)){const ind=localPoliticalFactionState(locId,SOSText("politics_campaigns_civic.decayLocalPoliticalCivic.003"));ind.support=clamp(ind.support+.08,-6,12)}
}
function guardianPublicEndorsement(){
 ensureWorldState();if(!state.world.guardianPublicEndorsement||typeof state.world.guardianPublicEndorsement!=='object')state.world.guardianPublicEndorsement={faction:null,day:-99,history:[]};
 const e=state.world.guardianPublicEndorsement;if(!Array.isArray(e.history))e.history=[];if(!Number.isFinite(e.day))e.day=-99;return e
}
function guardianEndorsementSwitchReady(){const e=guardianPublicEndorsement();return !e.faction||state.world.day-(e.day||-99)>=7}
function guardianEndorsementButtonState(faction){
 const e=guardianPublicEndorsement();
 if(e.faction===faction)return {disabled:true,label:SOSText("politics_campaigns_civic.guardianEndorsementButtonState.001"),reason:SOSText("politics_campaigns_civic.guardianEndorsementButtonState.002",majorFaction(faction).short)};
 if(e.faction&&!guardianEndorsementSwitchReady()){const left=Math.max(1,7-(state.world.day-e.day));return {disabled:true,label:SOSText("politics_campaigns_civic.guardianEndorsementButtonState.003",majorFaction(faction).short),reason:SOSText("politics_campaigns_civic.guardianEndorsementButtonState.004",majorFaction(e.faction).short,left,left===1?'':'s')}}
 return {disabled:false,label:e.faction?SOSText("politics_campaigns_civic.guardianEndorsementButtonState.005",majorFaction(faction).short):SOSText("politics_campaigns_civic.guardianEndorsementButtonState.006"),reason:e.faction?SOSText("politics_campaigns_civic.guardianEndorsementButtonState.007",majorFaction(e.faction).short):''}
}
const LOCAL_POLITICAL_ACTIONS={
 rally:{title:SOSText("politics_campaigns_civic.guardianEndorsementButtonState.008"),cost:12,desc:SOSText("politics_campaigns_civic.guardianEndorsementButtonState.009"),channel:'politics'},
 endorse:{title:SOSText("politics_campaigns_civic.guardianEndorsementButtonState.010"),cost:0,desc:SOSText("politics_campaigns_civic.guardianEndorsementButtonState.011"),channel:'guardian'},
 organize:{title:SOSText("politics_campaigns_civic.guardianEndorsementButtonState.012"),cost:8,desc:SOSText("politics_campaigns_civic.guardianEndorsementButtonState.013"),channel:'personnel'},
 petition:{title:SOSText("politics_campaigns_civic.guardianEndorsementButtonState.014"),cost:6,desc:SOSText("politics_campaigns_civic.guardianEndorsementButtonState.015"),channel:'politics'},
 relief:{title:SOSText("politics_campaigns_civic.guardianEndorsementButtonState.016"),cost:30,desc:SOSText("politics_campaigns_civic.guardianEndorsementButtonState.017"),channel:'trade'},
 repairs:{title:SOSText("politics_campaigns_civic.guardianEndorsementButtonState.018"),cost:34,desc:SOSText("politics_campaigns_civic.guardianEndorsementButtonState.019"),channel:'trade'}
};
function politicalActionCost(locId,id){const ss=settlementState(locId),a=LOCAL_POLITICAL_ACTIONS[id];if(!a)return 0;if(id==='relief')return a.cost+(ss.prosperity<45?6:0);if(id==='repairs')return a.cost+(ss.prosperity<40?4:0);return a.cost}
function executeLocalPoliticalAction(locId,faction,id){
 const a=LOCAL_POLITICAL_ACTIONS[id];if(!a||!OPEN_WORLD_FACTIONS[faction])return showLocalPoliticalActions(locId);
 const before=politicalOutcomeSnapshot(locId,[faction,localPoliticalRival(locId,faction)]),standing=state.world.factionStanding[faction]||0,rep=localReputation(locId),cost=politicalActionCost(locId,id),ss=settlementState(locId),ps=politicalSettlement(locId);
 if(standing<=-4)return actionResult(SOSText("politics_campaigns_civic.executeLocalPoliticalAction.001"),SOSText("politics_campaigns_civic.executeLocalPoliticalAction.002",majorFaction(faction).name),'bad',()=>showFactionCivicActions(locId,faction));
 if(id==='endorse'){const es=guardianEndorsementButtonState(faction);if(es.disabled)return actionResult(es.label,es.reason,'info',()=>showFactionCivicActions(locId,faction))}
 if(state.gold<cost)return actionResult(SOSText("politics_campaigns_civic.executeLocalPoliticalAction.003"),SOSText("politics_campaigns_civic.executeLocalPoliticalAction.004",a.title,cost),'bad',()=>showFactionCivicActions(locId,faction));
 if(cost)state.gold-=cost;
 let effect={},text='',tone='good',standingGain=0,repGain=0,roll=0;
 if(id==='rally'){roll=rnd(1,20)+stat(state,'cha')+Math.floor(rep/2)+Math.floor(standing/3);if(roll>=16){effect={support:2,organization:1,legitimacy:.5,power:3,pressure:1,rival:.75};text=SOSText("politics_campaigns_civic.executeLocalPoliticalAction.005",majorFaction(faction).short);standingGain=1}else{effect={support:.5,organization:.5,power:.5};text=SOSText("politics_campaigns_civic.executeLocalPoliticalAction.006");tone='info'}}
 if(id==='endorse'){const e=guardianPublicEndorsement(),oldFaction=e.faction,impact=rep>=8?2:rep>=3?1.5:rep>=0?1:.5;effect={support:impact,legitimacy:rep>=3?1:.25,power:1.5+impact*.5,pressure:.5,rival:impact>=1.5?.5:0};
  if(oldFaction&&oldFaction!==faction){adjustFactionStanding(oldFaction,-1,SOSText("politics_campaigns_civic.executeLocalPoliticalAction.007",majorFaction(faction).short));const oldP=localPoliticalFactionState(locId,oldFaction);oldP.support=clamp((oldP.support||0)-.75,-6,12);oldP.legitimacy=clamp((oldP.legitimacy||0)-.25,-6,12);text=SOSText("politics_campaigns_civic.executeLocalPoliticalAction.008",majorFaction(oldFaction).short,majorFaction(faction).short,worldLocation(locId).name)}
  else text=SOSText("politics_campaigns_civic.executeLocalPoliticalAction.009",majorFaction(faction).short,worldLocation(locId).name,rep>=8?'The endorsement carries considerable local weight.':rep>=3?'The endorsement is taken seriously by people who know the company.':'The statement is noticed, though the Guardian’s local pull is limited.');
  e.faction=faction;e.day=state.world.day;e.history.push({day:state.world.day,faction,from:oldFaction||null,locId});e.history=e.history.slice(-12);standingGain=1}
 if(id==='organize'){if(standing<2){if(cost)state.gold+=cost;return actionResult(SOSText("politics_campaigns_civic.executeLocalPoliticalAction.010"),SOSText("politics_campaigns_civic.executeLocalPoliticalAction.011",majorFaction(faction).short),'info',()=>showFactionCivicActions(locId,faction))}effect={organization:2,support:standing>=6?1:.5,power:2.5,pressure:.75,presence:1,rival:.35};text=SOSText("politics_campaigns_civic.executeLocalPoliticalAction.012",majorFaction(faction).short);standingGain=chance(.35)?1:0}
 if(id==='petition'){roll=rnd(1,20)+stat(state,'cha')+Math.floor(rep/2);if(roll>=15){effect={support:1.5,organization:1,legitimacy:.5,power:2.5,pressure:.75,rival:.5};text=SOSText("politics_campaigns_civic.executeLocalPoliticalAction.013")}else{effect={organization:.75,support:.25,power:.5};text=SOSText("politics_campaigns_civic.executeLocalPoliticalAction.014");tone='info'}}
 if(id==='relief'){const bonus=ss.prosperity<45?.75:0;effect={support:1.25+bonus,legitimacy:2,merchant:.5,power:2.75,pressure:.5,rival:.4};ss.prosperity=Math.min(100,ss.prosperity+2);text=SOSText("politics_campaigns_civic.executeLocalPoliticalAction.015",majorFaction(faction).short);repGain=1;standingGain=1}
 if(id==='repairs'){effect={support:.75,legitimacy:2,merchant:1,security:.75,power:2.5,pressure:.5,rival:.35};ss.prosperity=Math.min(100,ss.prosperity+2);ss.security=Math.min(100,ss.security+1);text=SOSText("politics_campaigns_civic.executeLocalPoliticalAction.016",majorFaction(faction).short);repGain=1;standingGain=1}
 applyLocalPoliticalEffects(locId,faction,effect,text,a.channel);adjustPoliticalCapital(locId,faction,id==='relief'||id==='repairs'?2:id==='organize'?1.5:1,SOSText("politics_campaigns_civic.executeLocalPoliticalAction.017",a.title));
 if(standingGain)adjustFactionStanding(faction,standingGain,SOSText("politics_campaigns_civic.executeLocalPoliticalAction.018",worldLocation(locId).name));
 if(repGain)changeLocalReputation(locId,repGain,SOSText("politics_campaigns_civic.executeLocalPoliticalAction.019",majorFaction(faction).short));
 recordLocalPoliticalAction(locId,faction,id,text);const notes=[];if(effect.rival)notes.push(SOSText("politics_campaigns_civic.executeLocalPoliticalAction.020",majorFaction(faction).short));if(cost)notes.push(SOSText("politics_campaigns_civic.executeLocalPoliticalAction.021",cost));
 advanceWorldDays(1,`${a.title} in ${worldLocation(locId).name}`);
 const after=politicalOutcomeSnapshot(locId,[faction,localPoliticalRival(locId,faction)]);
 save();showPoliticalOutcome(a.title,text,before,after,{tone,notes,back:()=>townNavCurrent?.route==='factionCivic'?townNavBackOrExit():showLocalPoliticalActions(locId)})
}
function executeIndependentCivicAction(locId,id){
 const before=politicalOutcomeSnapshot(locId),ps=politicalSettlement(locId),ss=settlementState(locId);let cost=0,text='',tone='good';
 if(id==='relief'){cost=24;if(state.gold<cost)return actionResult(SOSText("politics_campaigns_civic.executeIndependentCivicAction.001"),SOSText("politics_campaigns_civic.executeIndependentCivicAction.002",cost),'bad',()=>showIndependentCivicActions(locId));state.gold-=cost;ss.prosperity=Math.min(100,ss.prosperity+2);changeLocalReputation(locId,2,SOSText("politics_campaigns_civic.executeIndependentCivicAction.003"));ps.autonomy=Math.min(10,ps.autonomy+.5);text=SOSText("politics_campaigns_civic.executeIndependentCivicAction.004")}
 if(id==='works'){cost=30;if(state.gold<cost)return actionResult(SOSText("politics_campaigns_civic.executeIndependentCivicAction.005"),SOSText("politics_campaigns_civic.executeIndependentCivicAction.006",cost),'bad',()=>showIndependentCivicActions(locId));state.gold-=cost;ss.prosperity=Math.min(100,ss.prosperity+2);ss.security=Math.min(100,ss.security+1);changeLocalReputation(locId,2,SOSText("politics_campaigns_civic.executeIndependentCivicAction.007"));ps.autonomy=Math.min(10,ps.autonomy+.5);text=SOSText("politics_campaigns_civic.executeIndependentCivicAction.008")}
 if(id==='forum'){cost=12;if(state.gold<cost)return actionResult(SOSText("politics_campaigns_civic.executeIndependentCivicAction.009"),SOSText("politics_campaigns_civic.executeIndependentCivicAction.010",cost),'bad',()=>showIndependentCivicActions(locId));state.gold-=cost;const rows=Object.entries(ps.pressure||{}).sort((a,b)=>b[1]-a[1]);for(const [f] of rows.slice(0,2))ps.pressure[f]=Math.max(0,(ps.pressure[f]||0)-.35);ps.autonomy=Math.min(10,ps.autonomy+1);changeLocalReputation(locId,1,SOSText("politics_campaigns_civic.executeIndependentCivicAction.011"));text=SOSText("politics_campaigns_civic.executeIndependentCivicAction.012")}
 recordLocalPoliticalAction(locId,SOSText("politics_campaigns_civic.executeIndependentCivicAction.013"),id,text);const notes=cost?[SOSText("politics_campaigns_civic.executeIndependentCivicAction.014",cost)]:[];advanceWorldDays(1,SOSText("politics_campaigns_civic.executeIndependentCivicAction.015",worldLocation(locId).name));const after=politicalOutcomeSnapshot(locId);save();showPoliticalOutcome(SOSText("politics_campaigns_civic.executeIndependentCivicAction.016"),text,before,after,{tone,notes,back:()=>townNavCurrent?.route==='independentCivic'?townNavBackOrExit():showLocalPoliticalActions(locId)})
}
function showFactionCivicActions(locId,faction,parent='politics'){modalRouteEnter(SOSText("politics_campaigns_civic.showFactionCivicActions.001"),Array.from(arguments));
 const p=localPoliticalProfile(locId,faction),standing=state.world.factionStanding[faction]||0;
 overlay(SOSText("politics_campaigns_civic.showFactionCivicActions.002",esc(worldLocation(locId).name),esc(majorFaction(faction).short),esc(politicalSupportLabel(p.publicSupport)),esc(politicalOrganizationLabel(p.organization)),esc(politicalLegitimacyLabel(p.legitimacy)),standing>=0?'+':'',standing,guardianPublicEndorsement().faction?`Guardian public endorsement: <b>${esc(majorFaction(guardianPublicEndorsement().faction).short)}</b> since Day ${guardianPublicEndorsement().day}`:'Guardian public endorsement: <b>None</b>',Object.entries(LOCAL_POLITICAL_ACTIONS).map(([id,a])=>{const cost=politicalActionCost(locId,id),es=id==='endorse'?guardianEndorsementButtonState(faction):null,locked=(id==='organize'&&standing<2)||!!es?.disabled,label=es?.label||a.title,desc=id==='organize'&&standing<2?'Requires faction standing 2.':es?.reason||a.desc;return `<button data-civicaction="${id}" ${locked?'disabled':''}><b>${esc(label)}</b><br><small>${esc(desc)}${cost?` • ${cost}g`:''}</small></button>`}).join('')),true);
 document.querySelectorAll('[data-civicaction]').forEach(b=>b.onclick=()=>executeLocalPoliticalAction(locId,faction,b.dataset.civicaction));$('#seekPoliticalEndorsement').onclick=()=>showPoliticalEndorsementPeople(locId,faction);$('#civicFactionBack').onclick=()=>parent===SOSText("politics_campaigns_civic.showFactionCivicActions.003")&&townNavCurrent?townNavBackOrExit():showLocalPoliticalActions(locId)
}
function showIndependentCivicActions(locId){modalRouteEnter(SOSText("politics_campaigns_civic.showIndependentCivicActions.001"),Array.from(arguments));
 const ps=politicalSettlement(locId);overlay(SOSText("politics_campaigns_civic.showIndependentCivicActions.002",esc(worldLocation(locId).name),ps.autonomy),true);document.querySelectorAll('[data-independentcivic]').forEach(b=>b.onclick=()=>executeIndependentCivicAction(locId,b.dataset.independentcivic));$('#independentCivicBack').onclick=()=>townNavCurrent?.route==='independentCivic'?townNavBackOrExit():showLocalPoliticalActions(locId)
}
function showPoliticalCampaignDesk(locId=state.world.location,faction=null,parent='politics'){modalRouteEnter(SOSText("politics_campaigns_civic.showPoliticalCampaignDesk.001"),Array.from(arguments));
 if(!faction){
  const factions=localPoliticalFactions(locId);overlay(SOSText("politics_campaigns_civic.showPoliticalCampaignDesk.002",esc(worldLocation(locId).name),factions.map(f=>{const c=politicalCampaignState(locId,f),need=politicalCampaignNeed(locId,f),existing=politicalCampaignActiveOrOffered(locId,f);return `<button class="political-action-faction" data-campaignfaction="${f}"><span><b>${esc(majorFaction(f).name)}</b><small>${esc(need.label)}${need.rival?` • Rival: ${esc(majorFaction(need.rival).short)}`:''}${existing?` • ${esc(contractStatusLabel(existing))}: ${esc(existing.name)}`:''}</small></span><b>${esc(politicalCampaignMomentumLabel(c.momentum))}</b></button>`}).join('')),true);document.querySelectorAll('[data-campaignfaction]').forEach(b=>b.onclick=()=>showPoliticalCampaignDesk(locId,b.dataset.campaignfaction));$('#campaignDeskBack').onclick=()=>SOSServices.navigation.back(()=>showSettlementPolitics(locId));return
 }
 const c=politicalCampaignState(locId,faction),need=politicalCampaignNeed(locId,faction),existing=politicalCampaignActiveOrOffered(locId,faction),standing=state.world.factionStanding[faction]||0,cooldown=Math.max(0,2-(state.world.day-(c.lastCommissionDay||-99))),recent=(c.history||[]).slice(-6).reverse();
 overlay(SOSText("politics_campaigns_civic.showPoliticalCampaignDesk.003",esc(worldLocation(locId).name),esc(majorFaction(faction).short),esc(need.label),esc(need.reason),need.rival?`<br><b>Main rival:</b> ${esc(majorFaction(need.rival).name)}`:'',esc(politicalCampaignMomentumLabel(c.momentum)),c.momentum.toFixed(1),c.successes||0,c.failures||0,existing?`<div class="regional-contract-source"><b>${esc(existing.name)}</b><br>${esc(contractStatusLabel(existing))}<br><small>${esc(existing.desc)}</small><br><button id="campaignExistingContract">Review Contract</button></div>`:`<button id="campaignCommission" ${standing<0||cooldown>0?'disabled':''}><b>Request Political Campaign Work</b><br><small>${standing<0?'Faction standing must be nonnegative':cooldown>0?`New commission available in ${cooldown} day${cooldown===1?'':'s'}`:`Commission work aimed at: ${esc(need.label)}`}</small></button>`,recent.map(x=>`<div class="card compact"><b>Day ${x.day}</b><br>${esc(x.text)}</div>`).join('')||'<p class="muted">No organized campaign history yet.</p>'),true);
 if($('#campaignExistingContract'))$('#campaignExistingContract').onclick=()=>showContractDetails(existing.id);if($('#campaignCommission'))$('#campaignCommission').onclick=()=>{const before=politicalOutcomeSnapshot(locId,[faction]),q=generatePoliticalCampaignContract(locId,faction,true);if(!q)return actionResult(SOSText("politics_campaigns_civic.showPoliticalCampaignDesk.004"),SOSText("politics_campaigns_civic.showPoliticalCampaignDesk.005"),'info',()=>showPoliticalCampaignDesk(locId,faction));const after=politicalOutcomeSnapshot(locId,[faction]);save();showPoliticalOutcome(SOSText("politics_campaigns_civic.showPoliticalCampaignDesk.006"),SOSText("politics_campaigns_civic.showPoliticalCampaignDesk.007",q.name),before,after,{tone:'info',notes:[SOSText("politics_campaigns_civic.showPoliticalCampaignDesk.008",q.politicalNeed),SOSText("politics_campaigns_civic.showPoliticalCampaignDesk.009",politicalCampaignEffectText(q))],back:()=>showContractBoard(locId)})};$('#campaignFactionBack').onclick=()=>parent===SOSText("politics_campaigns_civic.showPoliticalCampaignDesk.010")&&townNavCurrent?townNavBackOrExit():showPoliticalCampaignDesk(locId)
}
const POLITICAL_COVERT_ACTIONS={
 garbage:{title:SOSText("politics_campaigns_civic.showPoliticalCampaignDesk.011"),desc:SOSText("politics_campaigns_civic.showPoliticalCampaignDesk.012"),cost:18,success:88,exposure:22,evidence:18,skill:'cha',crime:'trespass',severity:1,effect:{organization:.45,support:.15},benefit:{support:.15},petty:true},
 notices:{title:SOSText("politics_campaigns_civic.showPoliticalCampaignDesk.013"),desc:SOSText("politics_campaigns_civic.showPoliticalCampaignDesk.014"),cost:10,success:82,exposure:25,evidence:24,skill:'dex',crime:'trespass',severity:1,effect:{organization:.35,support:.25},benefit:{organization:.15}},
 redirect:{title:SOSText("politics_campaigns_civic.showPoliticalCampaignDesk.015"),desc:SOSText("politics_campaigns_civic.showPoliticalCampaignDesk.016"),cost:25,success:68,exposure:34,evidence:42,skill:'cha',crime:'theft',severity:2,effect:{organization:.65,merchant:.9},benefit:{merchant:.35,organization:.15}},
 records:{title:SOSText("politics_campaigns_civic.showPoliticalCampaignDesk.017"),desc:SOSText("politics_campaigns_civic.showPoliticalCampaignDesk.018"),cost:28,success:59,exposure:41,evidence:52,skill:'dex',crime:'theft',severity:3,effect:{organization:1.35,support:.25},benefit:{organization:.35}},
 stockpile:{title:SOSText("politics_campaigns_civic.showPoliticalCampaignDesk.019"),desc:SOSText("politics_campaigns_civic.showPoliticalCampaignDesk.020"),cost:36,success:53,exposure:51,evidence:66,skill:'dex',crime:'robbery',severity:4,effect:{organization:1.25,merchant:1.05,security:.25},benefit:{organization:.45,merchant:.25}},
 supporter:{title:SOSText("politics_campaigns_civic.showPoliticalCampaignDesk.021"),desc:SOSText("politics_campaigns_civic.showPoliticalCampaignDesk.022"),cost:22,success:62,exposure:47,evidence:56,skill:'dex',crime:'assault',severity:3,effect:{support:.8,organization:.75},benefit:{support:.25,organization:.2},named:true},
 forged_letters:{title:'Plant Forged Correspondence',desc:'Plant convincing letters or records that appear to implicate the rival faction in corruption, collusion, or betrayal.',cost:35,success:58,exposure:42,evidence:58,skill:'cha',crime:'fraud',severity:3,effect:{support:.35,organization:.35,legitimacy:1.25},benefit:{support:.2,legitimacy:.15}},
 event_sabotage:{title:'Sabotage Rival Public Event',desc:'Disrupt a rally, speech, fundraiser, or organizing event before it can build momentum.',cost:30,success:66,exposure:44,evidence:50,skill:'dex',crime:'vandalism',severity:2,effect:{support:.4,organization:.9},benefit:{organization:.25}},
 falseflag_market:{title:'Stage False-Flag Attack on Market District',desc:'Acquire rival colors and identifying material, attack the local Market District, and try to make witnesses blame the selected faction.',cost:60,success:64,exposure:56,evidence:66,skill:'dex',crime:'robbery',severity:5,effect:{},benefit:{},special:'falseflag_market'}
};

function politicalLeaderInjuryDuration(npcId,day){const seed=[...String(npcId||'leader')].reduce((n,c)=>n+c.charCodeAt(0),0)+(day||0);return 7+(seed%8)}
function refreshPoliticalLeaderInjuries(locId){
 const c=politicalCovertState(locId);
 // Repair legacy successful wound raids that predate explicit recovery tracking.
 for(const h of c.history||[]){if(h?.id!=='leader_wound'||!h.npcId||c.deadNpcs[h.npcId]||c.injuredNpcs[h.npcId]||(c.recoveredWounds[h.npcId]||-1)>=h.day)continue;const a=npcFactionAlignment(h.npcId),days=politicalLeaderInjuryDuration(h.npcId,h.day);c.injuredNpcs[h.npcId]={day:h.day,untilDay:h.day+days,target:h.target,originalSupport:Math.max(3,(a.support||0)+2),legacy:true}}
 for(const [npcId,inj] of Object.entries(c.injuredNpcs)){if(!inj||c.deadNpcs[npcId]){delete c.injuredNpcs[npcId];continue}if(state.world.day<(inj.untilDay||0))continue;const a=npcFactionAlignment(npcId);a.support=clamp(Math.max(a.support||0,Math.max(3,(inj.originalSupport||3)-1)),-3,5);a.public=true;a.reason=`Recovered from political-raid injuries on Day ${state.world.day}.`;c.recoveredWounds[npcId]=inj.day||state.world.day;delete c.injuredNpcs[npcId];npcMemoryAdd(npcId,'Recovered from injuries sustained in a political attack.',0)}
 return c.injuredNpcs
}
function politicalLeaderInjury(locId,npcId){refreshPoliticalLeaderInjuries(locId);return politicalCovertState(locId).injuredNpcs[npcId]||null}
function injurePoliticalLeader(locId,npcId,target,originalSupport){const c=politicalCovertState(locId),days=politicalLeaderInjuryDuration(npcId,state.world.day),untilDay=state.world.day+days;c.injuredNpcs[npcId]={day:state.world.day,untilDay,target,originalSupport:Math.max(3,originalSupport||3)};return c.injuredNpcs[npcId]}
function politicalCovertTargetPeople(locId,faction){refreshPoliticalLeaderInjuries(locId);const c=politicalCovertState(locId);return settlementNpcsPresent(locId).map(n=>({n,a:npcFactionAlignment(n.id),r:npcRelationshipState(n.id)})).filter(x=>x.a?.faction===faction&&(x.a.support||0)>=2&&!c.deadNpcs[x.n.id]&&!c.injuredNpcs[x.n.id]).sort((a,b)=>(b.a.support||0)-(a.a.support||0)||(b.r.familiarity||0)-(a.r.familiarity||0))}
function politicalCovertTargetLabel(locId,faction){const top=politicalCovertTargetPeople(locId,faction)[0];return top?`${top.n.name} (${top.n.role})`:factionPostName(locId,faction)}
function politicalCovertOdds(locId,target,id){const a=POLITICAL_COVERT_ACTIONS[id],p=localPoliticalProfile(locId,target),ss=settlementState(locId),skill=a.skill==='cha'?stat(state,'cha'):stat(state,'dex')+Math.floor((state.scouting||0)/2),fame=Math.max(0,localReputation(locId));return {success:clamp(Math.round(a.success+(skill-8)*2-p.organization*.08),25,95),exposure:clamp(Math.round(a.exposure+ss.security*.12+p.organization*.10+fame*.8-(stat(state,'dex')-8)*1.4-(state.scouting||0)),8,92),evidence:clamp(Math.round(a.evidence+ss.security*.14),10,94)}}
