function politicalWitnessMethods(){
 const cls=guardianClass(),rows=[{id:'none',name:SOSText("politics_covert_raids.politicalWitnessMethods.001"),desc:SOSText("politics_covert_raids.politicalWitnessMethods.002"),exposure:0,evidence:0,severity:0,cost:0}];
 rows.push({id:'bribe',name:SOSText("politics_covert_raids.politicalWitnessMethods.018"),desc:SOSText("politics_covert_raids.politicalWitnessMethods.019"),exposure:-22,evidence:-6,severity:1,cost:18});
 rows.push({id:'intimidate',name:SOSText("politics_covert_raids.politicalWitnessMethods.020"),desc:SOSText("politics_covert_raids.politicalWitnessMethods.021"),exposure:-16,evidence:-7,severity:2,cost:0});
 if([SOSText("politics_covert_raids.politicalWitnessMethods.003"),SOSText("politics_covert_raids.politicalWitnessMethods.004"),SOSText("politics_covert_raids.politicalWitnessMethods.005")].includes(cls))rows.push({id:'stun',name:SOSText("politics_covert_raids.politicalWitnessMethods.006"),desc:SOSText("politics_covert_raids.politicalWitnessMethods.007"),exposure:-18,evidence:-8,severity:2,cost:0});
 if([SOSText("politics_covert_raids.politicalWitnessMethods.008"),SOSText("politics_covert_raids.politicalWitnessMethods.009")].includes(cls))rows.push({id:'disguise',name:SOSText("politics_covert_raids.politicalWitnessMethods.010"),desc:SOSText("politics_covert_raids.politicalWitnessMethods.011"),exposure:-28,evidence:-15,severity:0,cost:0});
 if([SOSText("politics_covert_raids.politicalWitnessMethods.012"),SOSText("politics_covert_raids.politicalWitnessMethods.013")].includes(cls))rows.push({id:'memory',name:SOSText("politics_covert_raids.politicalWitnessMethods.014"),desc:SOSText("politics_covert_raids.politicalWitnessMethods.015"),exposure:-25,evidence:-22,severity:1,cost:0});
 rows.push({id:'remove',name:SOSText("politics_covert_raids.politicalWitnessMethods.016"),desc:SOSText("politics_covert_raids.politicalWitnessMethods.017"),exposure:-42,evidence:-28,severity:7,atrocity:true,cost:0});return rows
}
function politicalWitnessMethod(id){return politicalWitnessMethods().find(x=>x.id===id)||politicalWitnessMethods()[0]}
function politicalCompanionsLeftBehind(prep){return !!(prep?.leaveCompanions||prep?.companionsLeftBehind)}
function politicalRaidActor(op,capitalized=true){const solo=politicalCompanionsLeftBehind(op),s=solo?'the Guardian':SOSText("politics_covert_raids.politicalRaidActor.001");return capitalized?s[0].toUpperCase()+s.slice(1):s}
function politicalPreparedOdds(locId,target,id,prep={}){const base=politicalCovertOdds(locId,target,id),m=politicalWitnessMethod(prep.witnessMethod||'none'),intimidationBonus=m.id==='intimidate'?Math.max(0,Math.min(12,(stat(state,'cha')-8)*2)):0;return {...base,exposure:clamp(base.exposure+m.exposure-intimidationBonus+(politicalCompanionsLeftBehind(prep)?-4:0),3,96),evidence:clamp(base.evidence+m.evidence,3,98)}}
function politicalWitnessNotes(locId,target,sponsor,prep,identified,evidence,baseSeverity,context){
 const m=politicalWitnessMethod(prep?.witnessMethod||'none'),notes=[];if(m.id==='none')return notes;
 if(m.id==='disguise')notes.push(identified?'The disguise is partly defeated by the circumstances; some witnesses still connect the Guardian to the operation.':SOSText("politics_covert_raids.politicalWitnessNotes.001"));
 if(m.id==='memory')notes.push(identified?'The memory-working is incomplete; enough recollection survives to identify the Guardian.':SOSText("politics_covert_raids.politicalWitnessNotes.002"));
 if(m.id==='stun'){notes.push(identified?'The attempt to leave witnesses dazed does not prevent identification.':SOSText("politics_covert_raids.politicalWitnessNotes.003"));if(identified&&evidence){const p=politicallyProtectedCrime('assault',locId,target,sponsor,{witnessed:true,severity:Math.max(2,baseSeverity),desc:SOSText("politics_covert_raids.politicalWitnessNotes.004",context)});if(p.note)notes.push(p.note)}}
 if(m.id==='bribe')notes.push(identified?SOSText("politics_covert_raids.politicalWitnessNotes.007"):SOSText("politics_covert_raids.politicalWitnessNotes.008"));
 if(m.id==='intimidate'){notes.push(identified?SOSText("politics_covert_raids.politicalWitnessNotes.009"):SOSText("politics_covert_raids.politicalWitnessNotes.010"));if(identified&&evidence){const p=politicallyProtectedCrime('threat',locId,target,sponsor,{witnessed:true,severity:Math.max(2,Math.min(4,baseSeverity)),desc:SOSText("politics_covert_raids.politicalWitnessNotes.011",context)});if(p.note)notes.push(p.note)}}
 if(m.id==='remove'){const tc=localPoliticalFactionState(locId,target);tc.support=clamp(tc.support+.65,-6,12);notes.push(SOSText("politics_covert_raids.politicalWitnessNotes.005"));if(sponsor&&OPEN_WORLD_FACTIONS[sponsor]){const sc=localPoliticalFactionState(locId,sponsor);sc.legitimacy=clamp(sc.legitimacy-1.1,-6,12)}if(identified||evidence){const p=politicallyProtectedCrime('murder',locId,target,sponsor,{witnessed:true,severity:7,desc:SOSText("politics_covert_raids.politicalWitnessNotes.006",context)});if(p.note)notes.push(p.note)}}
 return notes
}
function showPoliticalOperationPreparation(locId,sponsor,target,kind,callback,npcId=null){modalRouteEnter(SOSText("politics_covert_raids.showPoliticalOperationPreparation.001"),Array.from(arguments));
 const methods=politicalWitnessMethods(),active=activeRoadCompanions(),violent=['raid','intimidate','falseflag'].includes(kind),title=kind==='raid'?'Prepare Political Raid':kind==='intimidate'?'Prepare Political Intimidation':SOSText("politics_covert_raids.showPoliticalOperationPreparation.002");
 const baseId=kind==='covert'?'records':null;
 const activeNames=active.length?active.map(x=>esc(x.name)).join(', '):'None active',leaveText=SOSText("politics_covert_raids.showPoliticalOperationPreparation.004"),bringText=active.length?(violent?SOSText("politics_covert_raids.showPoliticalOperationPreparation.005"):SOSText("politics_covert_raids.showPoliticalOperationPreparation.006")):SOSText("politics_covert_raids.showPoliticalOperationPreparation.007");
 overlay(SOSText("politics_covert_raids.showPoliticalOperationPreparation.003",title,activeNames,active.length?'':'disabled',active.length?(violent?'They will fight beside you and remember what happened.':'They assist with the operation and may approve or object afterward.'):'No active companions are available to bring.',methods.map((m,i)=>`<button data-witnessmethod="${m.id}" class="${i===0?'selected':''}" aria-pressed="${i===0?'true':'false'}"><b>${esc(m.name)}</b><br><small>${esc(m.desc)}${m.cost?` • ${m.cost}g`:''}${kind==='covert'&&baseId&&POLITICAL_COVERT_ACTIONS[baseId]?` • typical exposure modifier ${m.exposure>0?'+':''}${m.exposure}%`:''}</small></button>`).join(''),'success',leaveText),true);
 let partyMode='leave',witnessMethod=methods[0]?.id||'none';
 const syncCompanionPrepNotice=()=>{const coming=partyMode==='bring',box=$('#politicalCompanionNotice'),text=$('#politicalCompanionNoticeText');if(box)box.className=`${coming?'warning':'success'} notice`;if(text)text.textContent=coming?bringText:leaveText};
 const syncWitnessPrepChoice=()=>{document.querySelectorAll('[data-witnessmethod]').forEach(x=>{const selected=x.dataset.witnessmethod===witnessMethod;x.classList.toggle('selected',selected);x.setAttribute('aria-pressed',selected?'true':'false')});const method=politicalWitnessMethod(witnessMethod),proceed=$('#politicalPrepProceed');if(proceed){proceed.disabled=(method.cost||0)>state.gold;proceed.textContent=method.cost?SOSText("politics_covert_raids.showPoliticalOperationPreparation.009",method.cost):SOSText("politics_covert_raids.showPoliticalOperationPreparation.008")}};
 document.querySelectorAll('[data-prepparty]').forEach(b=>b.onclick=()=>{if(b.disabled)return;partyMode=b.dataset.prepparty;document.querySelectorAll('[data-prepparty]').forEach(x=>{x.classList.toggle('selected',x.dataset.prepparty===partyMode);x.setAttribute('aria-pressed',x.dataset.prepparty===partyMode?'true':'false')});syncCompanionPrepNotice()});
 syncCompanionPrepNotice();syncWitnessPrepChoice();
 document.querySelectorAll('[data-witnessmethod]').forEach(b=>b.onclick=()=>{witnessMethod=b.dataset.witnessmethod;syncWitnessPrepChoice()});$('#politicalPrepProceed').onclick=()=>{const method=politicalWitnessMethod(witnessMethod);if((method.cost||0)>state.gold)return;callback({leaveCompanions:partyMode==='leave',witnessMethod,witnessCost:method.cost||0,npcId})};$('#politicalPrepBack').onclick=()=>npcId?showPoliticalLeaderRaidTargets(locId,sponsor,target):showCovertPoliticalActions(locId,sponsor,target)
}
function politicalBeneficiaryLabel(sponsor){return sponsor&&OPEN_WORLD_FACTIONS[sponsor]?majorFaction(sponsor).short:SOSText("politics_covert_raids.politicalBeneficiaryLabel.001")}
function politicalCovertCrimeDescription(id,target,npc=null){const who=npc?SOSText("politics_covert_raids.politicalCovertCrimeDescription.001",npc.name):SOSText("politics_covert_raids.politicalCovertCrimeDescription.002",majorFaction(target).short);return id==='garbage'?SOSText("politics_covert_raids.politicalCovertCrimeDescription.003",who):id==='notices'?SOSText("politics_covert_raids.politicalCovertCrimeDescription.004",majorFaction(target).short):id==='redirect'?SOSText("politics_covert_raids.politicalCovertCrimeDescription.005",majorFaction(target).short):id==='records'?SOSText("politics_covert_raids.politicalCovertCrimeDescription.006",majorFaction(target).short):id==='stockpile'?SOSText("politics_covert_raids.politicalCovertCrimeDescription.007",majorFaction(target).short):id==='forged_letters'?`forged political correspondence intended to implicate ${majorFaction(target).short}`:id==='event_sabotage'?`sabotage of a ${majorFaction(target).short} public political event`:id==='falseflag_market'?`false-flag attack on the ${worldLocation(state.world.location).name} Market District while displaying ${majorFaction(target).short} colors`:SOSText("politics_covert_raids.politicalCovertCrimeDescription.008",who)}
function applyCovertNpcExposure(locId,target,npc,severity,desc){
 const affected=politicalCovertTargetPeople(locId,target);for(const row of affected.slice(0,4)){const rel=row.r,loss=row.n.id===npc?.id?Math.max(2,severity):severity>=4?2:1;rel.opinion=clamp((rel.opinion||0)-loss,-10,10);npcMemoryAdd(row.n.id,SOSText("politics_covert_raids.applyCovertNpcExposure.001",desc), -1);if(row.n.id===npc?.id)rel.familiarity=clamp((rel.familiarity||0)+1,0,10)}
}
function companionPoliticalOperationReaction(id,severity,violent=false,prep={}){
 if(politicalCompanionsLeftBehind(prep))return [];
 const notes=[];for(const m of SOSServices.companions.activeRoad()){const cls=m.className||allyDef(m.id)?.className||'';let d=0;if(violent&&[SOSText("politics_covert_raids.companionPoliticalOperationReaction.002"),SOSText("politics_covert_raids.companionPoliticalOperationReaction.003")].includes(cls))d=-2;else if(violent&&cls===SOSText("politics_covert_raids.companionPoliticalOperationReaction.004"))d=-1;else if(!violent&&cls===SOSText("politics_covert_raids.companionPoliticalOperationReaction.005"))d=1;else if(severity>=4&&cls===SOSText("politics_covert_raids.companionPoliticalOperationReaction.006"))d=-1;if(d){SOSServices.companions.adjustTrust(m.id,d);notes.push(SOSText("politics_covert_raids.companionPoliticalOperationReaction.007",m.name,d>0?'approves of':'objects to',d>0?'+':'',d))}}if(notes.length)SOSServices.companions.noteSharedEvent('politics',SOSText("politics_covert_raids.companionPoliticalOperationReaction.008",violent?'violent':'covert',POLITICAL_COVERT_ACTIONS[id]?.title||'political raid'));return notes
}
function executePoliticalFalseFlagMarketAttack(locId,sponsor,target,prep={}){
 const a=POLITICAL_COVERT_ACTIONS.falseflag_market,before=politicalOutcomeSnapshot(locId,[target,sponsor]),cost=a.cost+(prep.witnessCost||0),odds=politicalPreparedOdds(locId,target,'falseflag_market',prep),covert=politicalCovertState(locId);
 if(state.gold<cost)return actionResult('Not Enough Gold',`The false-flag preparation and witness plan require ${cost} gold.`,'bad',()=>showCovertPoliticalActions(locId,sponsor,target));state.gold-=cost;
 const operationalRoll=rnd(1,100),success=operationalRoll<=odds.success,exposureRoll=rnd(1,100),exposed=exposureRoll<=odds.exposure,attributionChance=clamp(Math.round(58+(stat(state,'cha')-8)*1.8+(state.scouting||0)*2-localPoliticalProfile(locId,target).organization*.06),25,90),attributionRoll=success?rnd(1,100):null,attributed=success&&!exposed&&attributionRoll<=attributionChance,evidenceRoll=exposed?rnd(1,100):null,evidence=exposed&&evidenceRoll<=odds.evidence,tc=localPoliticalFactionState(locId,target),ss=settlementState(locId),notes=[];
 let narrative='';if(success){ss.prosperity=clamp((ss.prosperity||0)-2,0,100);ss.security=clamp((ss.security||0)-1,0,100);if(attributed){tc.support=clamp((tc.support||0)-.7,-6,12);tc.merchant=clamp((tc.merchant||0)-1.2,-6,12);tc.legitimacy=clamp((tc.legitimacy||0)-.9,-6,12);politicalSettlement(locId).pressure[target]=Math.max(0,(politicalSettlement(locId).pressure[target]||0)-.45);if(sponsor&&OPEN_WORLD_FACTIONS[sponsor]){const sc=localPoliticalFactionState(locId,sponsor);sc.support=clamp((sc.support||0)+.25,-6,12)}narrative=`The Market District is hit and witnesses initially blame ${majorFaction(target).short} supporters.`}else narrative=exposed?'The Market District is hit, but the disguise collapses and the attempted frame becomes part of the investigation.':'The Market District is hit, but witnesses do not confidently accept the planted faction identity.'}else narrative='The attempted false-flag attack is disrupted before meaningful damage is done.';
 covert.operations++;covert.lastOperationDay=state.world.day;if(exposed){covert.suspicion=clamp(covert.suspicion+6,0,20);state.world.factionStanding[target]=(state.world.factionStanding[target]||0)-1;if(sponsor&&OPEN_WORLD_FACTIONS[sponsor])localPoliticalFactionState(locId,sponsor).legitimacy=clamp((localPoliticalFactionState(locId,sponsor).legitimacy||0)-1.25,-6,12);notes.push('The attempted false attribution is uncovered, sharply increasing political suspicion.');if(evidence){covert.evidence=clamp(covert.evidence+5,0,20);const protection=politicallyProtectedCrime('robbery',locId,target,sponsor,{witnessed:true,severity:5,desc:politicalCovertCrimeDescription('falseflag_market',target)});if(protection.note)notes.push(protection.note)}else recordPoliticalCaseFile(locId,{kind:'robbery',victimFaction:target,sponsor,severity:5,desc:politicalCovertCrimeDescription('falseflag_market',target),status:'suspected',identified:true,evidence:false})}else notes.push(attributed?`${majorFaction(target).short} takes the immediate political blame for the attack.`:'Nobody can reliably connect the operation to the Guardian, but the framing attempt does not fully stick.');
 notes.push(...politicalWitnessNotes(locId,target,sponsor,prep,exposed,evidence,5,a.title));notes.push(...companionPoliticalOperationReaction('falseflag_market',5,true,prep));covert.history.push({day:state.world.day,id:'falseflag_market',target,sponsor:sponsor||null,success,attributed,exposed,evidence,witnessMethod:prep.witnessMethod||'none',companionsLeftBehind:!!prep.leaveCompanions,text:narrative});covert.history=covert.history.slice(-40);recordLocalPoliticalAction(locId,sponsor||'Civic','covert_operation',`${a.title} targets the ${worldLocation(locId).name} Market District while displaying ${majorFaction(target).short} identity. ${success?'The attack lands.':'The attack fails.'}${attributed?' The target faction is blamed.':''}${exposed?' The Guardian is linked to the attempted frame.':''}`);const after=politicalOutcomeSnapshot(locId,[target,sponsor]);advanceWorldDays(1,`political operation in ${worldLocation(locId).name}`);save();showPoliticalOutcome(a.title,narrative,before,after,{tone:success?'good':'bad',success,exposed,evidence,target,checks:[{label:'Operation',kind:'success',chance:odds.success,roll:operationalRoll,triggered:success},{label:'Attribution',kind:'success',chance:attributionChance,roll:attributionRoll,triggered:attributed},{label:'Exposure',kind:'risk',chance:odds.exposure,roll:exposureRoll,triggered:exposed}],notes:[`Disguise/material acquisition and operation cost: ${cost} gold.`,...notes],back:()=>showCovertPoliticalActions(locId)})
}
function executePoliticalCovertOperation(locId,sponsor,target,id,npcId=null,prep={}){
 const a=POLITICAL_COVERT_ACTIONS[id];if(!a||!OPEN_WORLD_FACTIONS[target]||sponsor===target)return showCovertPoliticalActions(locId,sponsor,target);if(a.special==='falseflag_market')return executePoliticalFalseFlagMarketAttack(locId,sponsor,target,prep);const npc=npcId?settlementNpc(locId,npcId)||settlementNpc(npcHomeLocation(npcId),npcId):null,before=politicalOutcomeSnapshot(locId,[target,sponsor]),cost=a.cost+(prep.witnessCost||0),odds=politicalPreparedOdds(locId,target,id,prep),covert=politicalCovertState(locId);
 if(state.gold<cost)return actionResult(SOSText("politics_covert_raids.executePoliticalCovertOperation.001"),SOSText("politics_covert_raids.executePoliticalCovertOperation.002",a.title,cost),'bad',()=>showCovertPoliticalActions(locId,sponsor,target));state.gold-=cost;
 const successRoll=rnd(1,100),success=successRoll<=odds.success,exposureRoll=rnd(1,100),exposed=exposureRoll<=odds.exposure,evidenceRoll=exposed?rnd(1,100):null,evidence=exposed&&evidenceRoll<=odds.evidence,tc=localPoliticalFactionState(locId,target),notes=[];let tone=success?'good':'bad',narrative='';
 if(success){for(const k of ['support','organization','merchant','security','legitimacy'])if(a.effect[k])tc[k]=clamp((tc[k]||0)-a.effect[k],-6,12);politicalSettlement(locId).pressure[target]=Math.max(0,(politicalSettlement(locId).pressure[target]||0)-(a.effect.organization||0)*.25-(a.effect.support||0)*.15);if(sponsor&&OPEN_WORLD_FACTIONS[sponsor]){const sc=localPoliticalFactionState(locId,sponsor);for(const k of ['support','organization','merchant','security','legitimacy'])if(a.benefit[k])sc[k]=clamp((sc[k]||0)+a.benefit[k],-6,12);recordFactionPower(locId,sponsor,'politics',.5,SOSText("politics_covert_raids.executePoliticalCovertOperation.003",majorFaction(target).short),5)}narrative=SOSText("politics_covert_raids.executePoliticalCovertOperation.004",a.title,majorFaction(target).short,worldLocation(locId).name)}else{tc.organization=clamp((tc.organization||0)+.15,-6,12);narrative=SOSText("politics_covert_raids.executePoliticalCovertOperation.005",a.title,majorFaction(target).short);covert.suspicion=clamp(covert.suspicion+.5,0,20)}
 covert.operations++;covert.lastOperationDay=state.world.day;if(exposed){const sGain=Math.max(1,a.severity+(success?0:1));covert.suspicion=clamp(covert.suspicion+sGain,0,20);notes.push(SOSText("politics_covert_raids.executePoliticalCovertOperation.006",politicalSuspicionLabel(covert.suspicion)));state.world.factionStanding[target]=(state.world.factionStanding[target]||0)-Math.max(1,Math.floor(a.severity/2));applyCovertNpcExposure(locId,target,npc,a.severity,a.title);if(sponsor&&OPEN_WORLD_FACTIONS[sponsor]){const sc=localPoliticalFactionState(locId,sponsor);sc.legitimacy=clamp((sc.legitimacy||0)-a.severity*.12,-6,12);notes.push(SOSText("politics_covert_raids.executePoliticalCovertOperation.007",majorFaction(sponsor).short))}if(evidence){covert.evidence=clamp(covert.evidence+Math.max(1,a.severity),0,20);const protection=politicallyProtectedCrime(a.crime,locId,target,sponsor,{witnessed:true,severity:a.severity,desc:politicalCovertCrimeDescription(id,target,npc)}),crime=protection.row;notes.push(SOSText("politics_covert_raids.executePoliticalCovertOperation.008",jurisdictionRule(locId).authority,crime.fine));if(protection.note)notes.push(protection.note)}else{notes.push(SOSText("politics_covert_raids.executePoliticalCovertOperation.009"));if(a.severity>=3)recordPoliticalCaseFile(locId,{kind:a.crime,victimFaction:target,sponsor,severity:a.severity,desc:politicalCovertCrimeDescription(id,target,npc),status:'suspected',identified:true,evidence:false})}}else notes.push(SOSText("politics_covert_raids.executePoliticalCovertOperation.010"));
 notes.push(...politicalWitnessNotes(locId,target,sponsor,prep,exposed,evidence,a.severity,a.title));notes.push(...companionPoliticalOperationReaction(id,a.severity,false,prep));covert.history.push({day:state.world.day,id,target,sponsor:sponsor||null,npcId:npc?.id||null,success,exposed,evidence,witnessMethod:prep.witnessMethod||'none',companionsLeftBehind:!!prep.leaveCompanions,text:narrative});covert.history=covert.history.slice(-40);recordLocalPoliticalAction(locId,sponsor||SOSText("politics_covert_raids.executePoliticalCovertOperation.011"),'covert_operation',SOSText("politics_covert_raids.executePoliticalCovertOperation.012",a.title,majorFaction(target).short,success?'The operation succeeds.':'The operation fails.',exposed?' The Guardian is linked to it.':''));const after=politicalOutcomeSnapshot(locId,[target,sponsor]);advanceWorldDays(1,SOSText("politics_covert_raids.executePoliticalCovertOperation.013",worldLocation(locId).name));save();showPoliticalOutcome(a.title,narrative,before,after,{tone,success,exposed,evidence,target,checks:[{label:SOSText("politics_covert_raids.executePoliticalCovertOperation.019"),kind:'success',chance:odds.success,roll:successRoll,triggered:success},{label:SOSText("politics_covert_raids.executePoliticalCovertOperation.020"),kind:'risk',chance:odds.exposure,roll:exposureRoll,triggered:exposed}],notes:[SOSText("politics_covert_raids.executePoliticalCovertOperation.014",npc?`${npc.name} — ${npc.role}`:majorFaction(target).name),SOSText("politics_covert_raids.executePoliticalCovertOperation.015",politicalWitnessMethod(prep.witnessMethod||'none').name),SOSText("politics_covert_raids.executePoliticalCovertOperation.016",prep.leaveCompanions),SOSText("politics_covert_raids.executePoliticalCovertOperation.018",cost),...notes],back:()=>showCovertPoliticalActions(locId)})
}
function showPoliticalSupporterTargets(locId,sponsor,target){modalRouteEnter(SOSText("politics_covert_raids.showPoliticalSupporterTargets.001"),Array.from(arguments));
 const rows=politicalCovertTargetPeople(locId,target);overlay(SOSText("politics_covert_raids.showPoliticalSupporterTargets.002",esc(majorFaction(target).short),rows.map(({n,a,r})=>`<button class="political-person-row" data-covertnpc="${n.id}"><span><b>${esc(n.name)}</b><small>${esc(n.role)} • ${esc(npcPoliticalSupportLabel(a.support))} ${esc(majorFaction(target).short)}</small></span><small>${esc(npcAttitudeLabel(r))}</small></button>`).join('')||`<button id="covertGenericSite"><b>${esc(factionPostName(locId,target))}</b><br><small>No suitable named supporter site is known; target the faction's own local office instead.</small></button>`),true);
 document.querySelectorAll('[data-covertnpc]').forEach(b=>b.onclick=()=>showPoliticalOperationPreparation(locId,sponsor,target,'covert',prep=>executePoliticalCovertOperation(locId,sponsor,target,'supporter',b.dataset.covertnpc,prep),b.dataset.covertnpc));if($('#covertGenericSite'))$('#covertGenericSite').onclick=()=>showPoliticalOperationPreparation(locId,sponsor,target,'covert',prep=>executePoliticalCovertOperation(locId,sponsor,target,'supporter',null,prep));$('#covertSupporterBack').onclick=()=>SOSServices.navigation.back(()=>showCovertPoliticalActions(locId,sponsor,target))
}
function politicalLeaderCandidates(locId,target){return politicalCovertTargetPeople(locId,target).filter(x=>(x.a.support||0)>=3).slice(0,5)}
function showPoliticalLeaderRaidTargets(locId,sponsor,target){modalRouteEnter(SOSText("politics_covert_raids.showPoliticalLeaderRaidTargets.001"),Array.from(arguments));refreshPoliticalLeaderInjuries(locId);const rows=politicalLeaderCandidates(locId,target),injured=Object.entries(politicalCovertState(locId).injuredNpcs||{}).map(([id,inj])=>({id,inj,n:settlementNpc(locId,id)||settlementNpc(npcHomeLocation(id),id),a:npcFactionAlignment(id)})).filter(x=>x.n&&x.a?.faction===target);const injuredHTML=injured.map(x=>`<button class="political-person-row" disabled><span><b>${esc(x.n.name)}</b><small>${esc(x.n.role)} • Recovering from injuries</small></span><small>Expected recovery in ${Math.max(1,x.inj.untilDay-state.world.day)} day${Math.max(1,x.inj.untilDay-state.world.day)===1?'':'s'}</small></button>`).join('');overlay(SOSText("politics_covert_raids.showPoliticalLeaderRaidTargets.002",esc(majorFaction(target).short),rows.map(({n,a,r})=>`<button class="political-person-row" data-leadern="${n.id}"><span><b>${esc(n.name)}</b><small>${esc(n.role)} • ${esc(npcPoliticalSupportLabel(a.support))}</small></span><small>${esc(npcAttitudeLabel(r))}</small></button>`).join('')+injuredHTML||'<p class="muted">No named local political leader is currently prominent enough to target directly.</p>'),true);document.querySelectorAll('[data-leadern]').forEach(b=>b.onclick=()=>showPoliticalLeaderRaidOptions(locId,sponsor,target,b.dataset.leadern));$('#leaderTargetBack').onclick=()=>SOSServices.navigation.back(()=>showCovertPoliticalActions(locId,sponsor,target))}
function showPoliticalLeaderRaidOptions(locId,sponsor,target,npcId){modalRouteEnter(SOSText("politics_covert_raids.showPoliticalLeaderRaidOptions.001"),Array.from(arguments));
 const npc=settlementNpc(locId,npcId)||settlementNpc(npcHomeLocation(npcId),npcId),a=npcFactionAlignment(npcId),r=npcRelationshipState(npcId);if(!npc)return showPoliticalLeaderRaidTargets(locId,sponsor,target);
 overlay(SOSText("politics_covert_raids.showPoliticalLeaderRaidOptions.002",esc(npc.name),esc(npc.name),esc(npc.role),esc(npcPoliticalSupportLabel(a.support)),esc(majorFaction(target).short),esc(npcAttitudeLabel(r))),true);
 $('#leaderIntimidate').onclick=()=>showPoliticalOperationPreparation(locId,sponsor,target,'intimidate',prep=>executePoliticalLeaderIntimidation(locId,sponsor,target,npcId,prep),npcId);$('#leaderWound').onclick=()=>showPoliticalOperationPreparation(locId,sponsor,target,'raid',prep=>startPoliticalRaidCombat(locId,sponsor,target,npcId,'wound',prep),npcId);$('#leaderKill').onclick=()=>showPoliticalOperationPreparation(locId,sponsor,target,'raid',prep=>startPoliticalRaidCombat(locId,sponsor,target,npcId,'kill',prep),npcId);$('#leaderRaidBack').onclick=()=>SOSServices.navigation.back(()=>showPoliticalLeaderRaidTargets(locId,sponsor,target))
}
function executePoliticalLeaderIntimidation(locId,sponsor,target,npcId,prep={}){
 if((prep.witnessCost||0)>state.gold)return actionResult(SOSText("politics_covert_raids.executePoliticalCovertOperation.001"),SOSText("politics_covert_raids.executePoliticalCovertOperation.002",SOSText("politics_covert_raids.executePoliticalLeaderIntimidation.012"),prep.witnessCost||0),'bad',()=>showPoliticalLeaderRaidOptions(locId,sponsor,target,npcId));if(prep.witnessCost)state.gold-=prep.witnessCost;
 const npc=settlementNpc(locId,npcId)||settlementNpc(npcHomeLocation(npcId),npcId),a=npcFactionAlignment(npcId),r=npcRelationshipState(npcId),before=politicalOutcomeSnapshot(locId,[target,sponsor]),covert=politicalCovertState(locId),method=politicalWitnessMethod(prep.witnessMethod||'none'),chancePct=clamp(48+stat(state,'cha')*3+Math.floor(state.reputation/2)-(a.support||0)*6,20,90),successRoll=rnd(1,100),success=successRoll<=chancePct,exposureChance=clamp(68+method.exposure+(prep.leaveCompanions?-4:0),5,95),exposureRoll=rnd(1,100),exposed=exposureRoll<=exposureChance,notes=[];let narrative='',tone=success?'good':'bad';
 if(success){a.support=clamp((a.support||0)-2,-3,5);localPoliticalFactionState(locId,target).organization=clamp(localPoliticalFactionState(locId,target).organization-1,-6,12);narrative=SOSText("politics_covert_raids.executePoliticalLeaderIntimidation.001",npc.name)}else{localPoliticalFactionState(locId,target).support=clamp(localPoliticalFactionState(locId,target).support+.45,-6,12);narrative=SOSText("politics_covert_raids.executePoliticalLeaderIntimidation.002",npc.name)}
 r.opinion=clamp((r.opinion||0)-(success?3:4),-10,10);npcMemoryAdd(npcId,SOSText("politics_covert_raids.executePoliticalLeaderIntimidation.003"),-2);let evidence=false;
 if(exposed){covert.suspicion=clamp(covert.suspicion+4,0,20);state.world.factionStanding[target]=(state.world.factionStanding[target]||0)-2;notes.push(SOSText("politics_covert_raids.executePoliticalLeaderIntimidation.004",majorFaction(target).short));evidence=rnd(1,100)<=clamp(55+method.evidence,5,95);if(evidence){covert.evidence=clamp(covert.evidence+2,0,20);const protection=politicallyProtectedCrime('threat',locId,target,sponsor,{witnessed:true,severity:2,desc:SOSText("politics_covert_raids.executePoliticalLeaderIntimidation.005",npc.name)});if(protection.note)notes.push(protection.note);notes.push(SOSText("politics_covert_raids.executePoliticalLeaderIntimidation.006"))}else recordPoliticalCaseFile(locId,{kind:'threat',victimFaction:target,sponsor,severity:2,desc:SOSText("politics_covert_raids.executePoliticalLeaderIntimidation.005",npc.name),status:'suspected',identified:true,evidence:false})}else notes.push(SOSText("politics_covert_raids.executePoliticalLeaderIntimidation.007"));
 notes.push(...politicalWitnessNotes(locId,target,sponsor,prep,exposed,evidence,2,SOSText("politics_covert_raids.executePoliticalLeaderIntimidation.008",npc.name)));notes.push(...companionPoliticalOperationReaction('leader_intimidate',3,false,prep));covert.operations++;covert.lastOperationDay=state.world.day;covert.history.push({day:state.world.day,id:'leader_intimidate',target,sponsor:sponsor||null,npcId,success,exposed,witnessMethod:prep.witnessMethod||'none',companionsLeftBehind:!!prep.leaveCompanions,text:narrative});recordLocalPoliticalAction(locId,sponsor||SOSText("politics_covert_raids.executePoliticalLeaderIntimidation.009"),'political_intimidation',SOSText("politics_covert_raids.executePoliticalLeaderIntimidation.010",npc.name,majorFaction(target).short));const after=politicalOutcomeSnapshot(locId,[target,sponsor]);advanceWorldDays(1,SOSText("politics_covert_raids.executePoliticalLeaderIntimidation.011",worldLocation(locId).name));save();showPoliticalOutcome(SOSText("politics_covert_raids.executePoliticalLeaderIntimidation.012"),narrative,before,after,{tone,success,exposed,target,checks:[{label:SOSText("politics_covert_raids.executePoliticalCovertOperation.019"),kind:'success',chance:chancePct,roll:successRoll,triggered:success},{label:SOSText("politics_covert_raids.executePoliticalCovertOperation.020"),kind:'risk',chance:exposureChance,roll:exposureRoll,triggered:exposed}],notes:[SOSText("politics_covert_raids.executePoliticalLeaderIntimidation.013",npc.name,npcAttitudeLabel(r)),SOSText("politics_covert_raids.executePoliticalLeaderIntimidation.014",method.name),SOSText("politics_covert_raids.executePoliticalLeaderIntimidation.015",prep.leaveCompanions?'left behind':'present'),...notes],back:()=>showCovertPoliticalActions(locId)})
}
function politicalRaidPartyKind(target){return target===SOSText("politics_covert_raids.politicalRaidPartyKind.001")?'redstone':target===SOSText("politics_covert_raids.politicalRaidPartyKind.002")?'bluestone':target===SOSText("politics_covert_raids.politicalRaidPartyKind.003")?'coalition':'mercenary'}

function preparePoliticalSoloRaid(gr,prep){return SOSServices.combat.setParticipants(gr,SOSServices.companions.participantIds(prep))}
function politicalRaidExposure(op,base){const m=politicalWitnessMethod(op?.witnessMethod||'none');return clamp(base+m.exposure+(op?.companionsLeftBehind?-4:0),4,98)}
function politicalRaidEvidence(op,base){const m=politicalWitnessMethod(op?.witnessMethod||'none');return clamp(base+m.evidence,4,99)}
function startPoliticalRaidCombat(locId,sponsor,target,npcId,objective,prep={}){
 if((prep.witnessCost||0)>state.gold)return actionResult(SOSText("politics_covert_raids.executePoliticalCovertOperation.001"),SOSText("politics_covert_raids.executePoliticalCovertOperation.002",SOSText("politics_covert_raids.startPoliticalRaidCombat.005"),prep.witnessCost||0),'bad',()=>showCovertPoliticalActions(locId,sponsor,target));if(prep.witnessCost)state.gold-=prep.witnessCost;
 const npc=npcId?(settlementNpc(locId,npcId)||settlementNpc(npcHomeLocation(npcId),npcId)):null;if(objective!=='forces'&&!npc)return showPoliticalLeaderRaidTargets(locId,sponsor,target);const pseudo={id:`polraid_${uid()}`,kind:politicalRaidPartyKind(target),name:SOSText("politics_covert_raids.startPoliticalRaidCombat.001",majorFaction(target).short),faction:target,location:locId,destination:locId,combatLevel:clamp((state.level||1)+(objective==='kill'?1:0),1,(state.level||1)+2),guardianSolo:politicalCompanionsLeftBehind(prep)},gr=makeWorldCombatGroup(pseudo);delete gr.worldPartyId;gr.id=`political_${uid()}`;gr.name=objective==='forces'?SOSText("politics_covert_raids.startPoliticalRaidCombat.002",majorFaction(target).short):SOSText("politics_covert_raids.startPoliticalRaidCombat.003",npc.name);gr.status=SOSText("politics_covert_raids.startPoliticalRaidCombat.004");const raidIncident=createWorldIncident('political_violence',{location:locId,severity:objective==='kill'?5:4,actors:[{ref:'guardian:guardian',side:'attacker',role:'guardian'},...(politicalCompanionsLeftBehind(prep)?[]:(state.party?.active||[]).map(id=>({ref:`companion:${id}`,side:'attacker',role:'companion'}))),{ref:`faction:${target}`,side:'target',role:'faction'}],political:{sponsor:sponsor||null,target,covert:true},legal:{covert:true,witnessMethod:prep.witnessMethod||'none'},meta:{objective,npcId:npc?.id||null}});gr.incidentId=raidIncident.id;gr.politicalOperation={locId,sponsor:sponsor||null,target,npcId:npc?.id||null,objective,before:politicalOutcomeSnapshot(locId,[target,sponsor]),witnessMethod:prep.witnessMethod||'none',companionsLeftBehind:politicalCompanionsLeftBehind(prep),incidentId:raidIncident.id};gr.loot=Math.max(0,Math.round(gr.loot*.25));gr.tactical={terrain:encounterTerrain(locId),stance:SOSText("politics_covert_raids.startPoliticalRaidCombat.005"),acc:objective==='kill'?-1:1,enemyAcc:objective==='kill'?3:1,retreat:-.05};ensurePartyState();preparePoliticalSoloRaid(gr,prep);recordWorldHistory(objective==='forces'?SOSText("politics_covert_raids.startPoliticalRaidCombat.006",majorFaction(target).short,worldLocation(locId).name):SOSText("politics_covert_raids.startPoliticalRaidCombat.007",npc.name,majorFaction(target).short),'bad','politics');SOSServices.combat.launch(gr,{register:true,closeOverlay:true})
}
function resolvePoliticalRaidVictory(gr){
 const op=gr.politicalOperation,actor=politicalRaidActor(op),locId=op.locId,target=op.target,sponsor=op.sponsor,npc=op.npcId?(settlementNpc(locId,op.npcId)||settlementNpc(npcHomeLocation(op.npcId),op.npcId)):null,a=npc?npcFactionAlignment(op.npcId):null,r=npc?npcRelationshipState(op.npcId):null,covert=politicalCovertState(locId),tc=localPoliticalFactionState(locId,target),before=op.before,notes=[];const exposed=rnd(1,100)<=politicalRaidExposure(op,op.objective==='kill'?88:op.objective==='forces'?82:76),evidence=exposed&&rnd(1,100)<=politicalRaidEvidence(op,op.objective==='kill'?90:op.objective==='forces'?84:78);let narrative='',martyr=false;
 if(op.objective==='forces'){tc.organization=clamp(tc.organization-1.15,-6,12);tc.security=clamp(tc.security-1.45,-6,12);tc.support=clamp(tc.support-.2,-6,12);narrative=SOSText("politics_covert_raids.resolvePoliticalRaidVictory.001",actor,majorFaction(target).short)}
 else if(op.objective==='wound'){const originalSupport=a.support||3,inj=injurePoliticalLeader(locId,op.npcId,target,originalSupport);a.support=clamp(originalSupport-2,-3,5);a.reason=`Recovering from political-raid injuries until approximately Day ${inj.untilDay}.`;tc.organization=clamp(tc.organization-1.8,-6,12);tc.support=clamp(tc.support-.45,-6,12);narrative=`${npc.name} is badly wounded and withdraws from political activity. Recovery is expected in roughly ${inj.untilDay-state.world.day} days.`;r.opinion=-10;npcMemoryAdd(op.npcId,SOSText("politics_covert_raids.resolvePoliticalRaidVictory.003"),-3);notes.push(`${npc.name} is unavailable for direct political-leader operations until about Day ${inj.untilDay}.`)}
 else{martyr=chance(clamp(.35+(a.support||0)*.08,.35,.78));covert.deadNpcs[op.npcId]={day:state.world.day,target,cause:SOSText("politics_covert_raids.resolvePoliticalRaidVictory.004")};a.support=0;a.public=false;a.reason=SOSText("politics_covert_raids.resolvePoliticalRaidVictory.005",state.world.day);tc.organization=clamp(tc.organization-2.5,-6,12);tc.security=clamp(tc.security-.5,-6,12);tc.support=clamp(tc.support+(martyr?1.4:-.8),-6,12);narrative=martyr?SOSText("politics_covert_raids.resolvePoliticalRaidVictory.006",npc.name,majorFaction(target).short):SOSText("politics_covert_raids.resolvePoliticalRaidVictory.007",npc.name,majorFaction(target).short)}
 if(sponsor&&OPEN_WORLD_FACTIONS[sponsor]){const sc=localPoliticalFactionState(locId,sponsor);sc.organization=clamp(sc.organization+.4,-6,12);if(exposed)sc.legitimacy=clamp(sc.legitimacy-(op.objective==='kill'?1.2:op.objective==='forces'?.85:.7),-6,12)}covert.operations++;covert.lastOperationDay=state.world.day;if(exposed){covert.suspicion=clamp(covert.suspicion+(op.objective==='kill'?7:op.objective==='forces'?6:5),0,20);state.world.factionStanding[target]=(state.world.factionStanding[target]||0)-(op.objective==='kill'?5:op.objective==='forces'?4:3);applyCovertNpcExposure(locId,target,npc,op.objective==='kill'?6:op.objective==='forces'?5:4,gr.name);notes.push(SOSText("politics_covert_raids.resolvePoliticalRaidVictory.008",politicalSuspicionLabel(covert.suspicion)));if(evidence){covert.evidence=clamp(covert.evidence+(op.objective==='kill'?7:op.objective==='forces'?5:4),0,20);const kind=op.objective==='kill'?'murder':'assault',desc=npc?SOSText("politics_covert_raids.resolvePoliticalRaidVictory.009",npc.name):SOSText("politics_covert_raids.resolvePoliticalRaidVictory.010",majorFaction(target).short),protection=politicallyProtectedCrime(kind,locId,target,sponsor,{witnessed:true,severity:op.objective==='kill'?7:op.objective==='forces'?5:4,desc}),crime=protection.row;notes.push(SOSText("politics_covert_raids.resolvePoliticalRaidVictory.011",jurisdictionRule(locId).authority,crime.fine));if(protection.note)notes.push(protection.note)}else recordPoliticalCaseFile(locId,{kind:op.objective==='kill'?'murder':'assault',victimFaction:target,sponsor,severity:op.objective==='kill'?7:op.objective==='forces'?5:4,desc:npc?SOSText("politics_covert_raids.resolvePoliticalRaidVictory.009",npc.name):SOSText("politics_covert_raids.resolvePoliticalRaidVictory.010",majorFaction(target).short),status:'suspected',identified:true,evidence:false})}else notes.push(SOSText("politics_covert_raids.resolvePoliticalRaidVictory.012",actor));notes.push(...politicalWitnessNotes(locId,target,sponsor,op,exposed,evidence,op.objective==='kill'?7:5,gr.name));notes.push(...companionPoliticalOperationReaction('political_raid',op.objective==='kill'?7:op.objective==='forces'?6:5,true,op));covert.history.push({day:state.world.day,id:`leader_${op.objective}`,target,sponsor,npcId:op.npcId||null,success:true,exposed,evidence,text:narrative});recordLocalPoliticalAction(locId,sponsor||SOSText("politics_covert_raids.resolvePoliticalRaidVictory.013"),'political_raid',SOSText("politics_covert_raids.resolvePoliticalRaidVictory.014",gr.name,majorFaction(target).short,martyr?' The killing creates a martyr.':''));const after=politicalOutcomeSnapshot(locId,[target,sponsor]);return {title:op.objective==='kill'?'Political Leader Killed':op.objective==='forces'?'Rival Political Force Attacked':SOSText("politics_covert_raids.resolvePoliticalRaidVictory.015"),narrative,before,after,notes,target,locId,success:true,exposed,evidence}}
function resolvePoliticalRaidRetreat(gr){const op=gr.politicalOperation,actor=politicalRaidActor(op),locId=op.locId,target=op.target,sponsor=op.sponsor,npc=op.npcId?(settlementNpc(locId,op.npcId)||settlementNpc(npcHomeLocation(op.npcId),op.npcId)):null,covert=politicalCovertState(locId),tc=localPoliticalFactionState(locId,target),notes=[],exposed=rnd(1,100)<=politicalRaidExposure(op,62);tc.organization=clamp(tc.organization+.25,-6,12);covert.operations++;covert.lastOperationDay=state.world.day;if(exposed){covert.suspicion=clamp(covert.suspicion+3,0,20);state.world.factionStanding[target]=(state.world.factionStanding[target]||0)-2;applyCovertNpcExposure(locId,target,npc,3,gr.name);notes.push(SOSText("politics_covert_raids.resolvePoliticalRaidRetreat.001",majorFaction(target).short,actor.toLowerCase()));if(rnd(1,100)<=politicalRaidEvidence(op,45)){covert.evidence=clamp(covert.evidence+2,0,20);const protection=politicallyProtectedCrime('assault',locId,target,sponsor,{witnessed:true,severity:3,desc:npc?SOSText("politics_covert_raids.resolvePoliticalRaidRetreat.002",npc.name):SOSText("politics_covert_raids.resolvePoliticalRaidRetreat.003",majorFaction(target).short)});notes.push(SOSText("politics_covert_raids.resolvePoliticalRaidRetreat.004"));if(protection.note)notes.push(protection.note)}else recordPoliticalCaseFile(locId,{kind:'assault',victimFaction:target,sponsor,severity:3,desc:npc?SOSText("politics_covert_raids.resolvePoliticalRaidRetreat.002",npc.name):SOSText("politics_covert_raids.resolvePoliticalRaidRetreat.003",majorFaction(target).short),status:'suspected',identified:true,evidence:false})}else notes.push(SOSText("politics_covert_raids.resolvePoliticalRaidRetreat.005",actor));notes.push(...politicalWitnessNotes(locId,target,sponsor,op,exposed,false,3,gr.name));covert.history.push({day:state.world.day,id:'leader_raid_retreat',target,sponsor,npcId:op.npcId,success:false,exposed,text:SOSText("politics_covert_raids.resolvePoliticalRaidRetreat.006")});recordLocalPoliticalAction(locId,sponsor||SOSText("politics_covert_raids.resolvePoliticalRaidRetreat.007"),'political_raid_retreat',npc?SOSText("politics_covert_raids.resolvePoliticalRaidRetreat.008",npc.name):SOSText("politics_covert_raids.resolvePoliticalRaidRetreat.009",majorFaction(target).short));return {title:SOSText("politics_covert_raids.resolvePoliticalRaidRetreat.010"),narrative:npc?SOSText("politics_covert_raids.resolvePoliticalRaidRetreat.011",actor,npc.name,majorFaction(target).short):SOSText("politics_covert_raids.resolvePoliticalRaidRetreat.012",actor,majorFaction(target).short),before:op.before,after:politicalOutcomeSnapshot(locId,[target,sponsor]),notes,locId}}
function resolvePoliticalRaidDefeat(gr){const op=gr.politicalOperation,actor=politicalRaidActor(op),locId=op.locId,target=op.target,sponsor=op.sponsor,npc=op.npcId?(settlementNpc(locId,op.npcId)||settlementNpc(npcHomeLocation(op.npcId),op.npcId)):null,covert=politicalCovertState(locId),before=op.before,tc=localPoliticalFactionState(locId,target),notes=[];tc.support=clamp(tc.support+.8,-6,12);tc.organization=clamp(tc.organization+.55,-6,12);covert.suspicion=clamp(covert.suspicion+7,0,20);covert.evidence=clamp(covert.evidence+5,0,20);covert.operations++;state.world.factionStanding[target]=(state.world.factionStanding[target]||0)-4;applyCovertNpcExposure(locId,target,npc,5,gr.name);const protection=politicallyProtectedCrime('assault',locId,target,sponsor,{witnessed:true,severity:5,desc:npc?SOSText("politics_covert_raids.resolvePoliticalRaidDefeat.001",npc.name):SOSText("politics_covert_raids.resolvePoliticalRaidDefeat.002",majorFaction(target).short)});if(protection.note)notes.push(protection.note);notes.push(SOSText("politics_covert_raids.resolvePoliticalRaidDefeat.003",majorFaction(target).short));notes.push(...politicalWitnessNotes(locId,target,sponsor,op,true,true,5,gr.name));notes.push(...companionPoliticalOperationReaction('political_raid',6,true,op));covert.history.push({day:state.world.day,id:'leader_raid_failed',target,sponsor,npcId:op.npcId,success:false,exposed:true,evidence:true,text:SOSText("politics_covert_raids.resolvePoliticalRaidDefeat.004")});recordLocalPoliticalAction(locId,sponsor||SOSText("politics_covert_raids.resolvePoliticalRaidDefeat.005"),'political_raid_failure',SOSText("politics_covert_raids.resolvePoliticalRaidDefeat.006",gr.name,majorFaction(target).short));return {title:SOSText("politics_covert_raids.resolvePoliticalRaidDefeat.007"),narrative:npc?SOSText("politics_covert_raids.resolvePoliticalRaidDefeat.008",npc.name,actor.toLowerCase(),majorFaction(target).short):SOSText("politics_covert_raids.resolvePoliticalRaidDefeat.009",majorFaction(target).short,actor.toLowerCase()),before,after:politicalOutcomeSnapshot(locId,[target,sponsor]),notes,locId}}
function showCovertPoliticalActions(locId=state.world.location,sponsor=null,target=null){modalRouteEnter(SOSText("politics_covert_raids.showCovertPoliticalActions.001"),Array.from(arguments));
 const factions=localPoliticalFactions(locId),covert=politicalCovertState(locId);
 if(sponsor===null){overlay(SOSText("politics_covert_raids.showCovertPoliticalActions.002",esc(worldLocation(locId).name),esc(politicalSuspicionLabel(covert.suspicion)),esc(politicalEvidenceLabel(covert.evidence)),factions.filter(f=>(state.world.factionStanding[f]||0)>=0).map(f=>`<button data-covertsponsor="${f}">${esc(majorFaction(f).name)}</button>`).join('')),true);document.querySelectorAll('[data-covertsponsor]').forEach(b=>b.onclick=()=>showCovertPoliticalActions(locId,b.dataset.covertsponsor==='none'?'':b.dataset.covertsponsor,null));$('#covertBackPolitics').onclick=()=>SOSServices.navigation.back(()=>showSettlementPolitics(locId));return}
 if(target===null){const choices=factions.filter(f=>f!==sponsor);overlay(SOSText("politics_covert_raids.showCovertPoliticalActions.003",sponsor?`${majorFaction(sponsor).short} will benefit if the operation succeeds.`:'No faction is sponsoring the operation.',choices.map(f=>{const p=localPoliticalProfile(locId,f);return `<button class="political-action-faction" data-coverttarget="${f}"><span><b>${esc(majorFaction(f).name)}</b><small>${esc(politicalSupportLabel(p.publicSupport))} support • ${esc(politicalOrganizationLabel(p.organization))}</small></span><b>${p.overall}</b></button>`}).join('')),true);document.querySelectorAll('[data-coverttarget]').forEach(b=>b.onclick=()=>showCovertPoliticalActions(locId,sponsor,b.dataset.coverttarget));$('#covertTargetBack').onclick=()=>SOSServices.navigation.back(()=>showCovertPoliticalActions(locId,null,null));return}
 const targetPeople=politicalCovertTargetPeople(locId,target),targetLabel=politicalCovertTargetLabel(locId,target);overlay(SOSText("politics_covert_raids.showCovertPoliticalActions.004",esc(worldLocation(locId).name),esc(majorFaction(target).short),esc(politicalBeneficiaryLabel(sponsor)),esc(targetLabel),esc(politicalSuspicionLabel(covert.suspicion)),esc(politicalEvidenceLabel(covert.evidence)),sponsor&&settlementControl(locId)===sponsor?`${esc(politicalProtectionLabel(politicalProtectionScore(locId,sponsor)))} (${politicalProtectionScore(locId,sponsor)}/100) from ${esc(majorFaction(sponsor).short)}`:'No reliable ruling-faction cover',Object.entries(POLITICAL_COVERT_ACTIONS).map(([id,a])=>{const o=politicalCovertOdds(locId,target,id);return `<button data-covertop="${id}"><b>${esc(a.title)}</b><br><small>${esc(a.desc)} • ${a.cost}g • success ${o.success}% • exposure ${o.exposure}%</small></button>`}).join(''),targetPeople.some(x=>(x.a.support||0)>=3)?'':'disabled'),true);document.querySelectorAll('[data-covertop]').forEach(b=>b.onclick=()=>b.dataset.covertop==='supporter'?showPoliticalSupporterTargets(locId,sponsor,target):showPoliticalOperationPreparation(locId,sponsor,target,b.dataset.covertop==='falseflag_market'?'falseflag':'covert',prep=>executePoliticalCovertOperation(locId,sponsor,target,b.dataset.covertop,null,prep)));$('#politicalForceAttack').onclick=()=>showPoliticalOperationPreparation(locId,sponsor,target,'raid',prep=>startPoliticalRaidCombat(locId,sponsor,target,null,'forces',prep));$('#politicalLeaderRaid').onclick=()=>showPoliticalLeaderRaidTargets(locId,sponsor,target);$('#covertOpsBack').onclick=()=>SOSServices.navigation.back(()=>showCovertPoliticalActions(locId,sponsor,null))
}

function showPoliticalSituation(locId=state.world.location,focusFaction=null){modalRouteEnter(SOSText("politics_covert_raids.showPoliticalSituation.001"),Array.from(arguments));
 const loc=worldLocation(locId),s=politicalStatus(locId),ps=politicalSettlement(locId),rr=roadRights(locId),profiles=localPoliticalProfilesSorted(locId),history=localPoliticalHistory(locId,8),lead=profiles[0];
 if(focusFaction)profiles.sort((a,b)=>a.faction===focusFaction?-1:b.faction===focusFaction?1:b.overall-a.overall);
 overlay(SOSText("politics_covert_raids.showPoliticalSituation.002",esc(loc.name),esc(s.control),lead?`${esc(majorFaction(lead.faction).short)} (${lead.overall})`:'None',esc(ps.leader),esc(ps.style),ps.autonomy,esc(rr.controller),rr.openness,rr.toll?` • Toll ${rr.toll}g`:'',profiles.map(p=>politicalSituationFactionHTML(locId,p,focusFaction)).join(''),history.map(h=>`<div class="card compact"><b>Day ${h.day}</b> • ${h.faction==='Civic'?'Civic / no faction':esc(majorFaction(h.faction)?.short||h.faction)}<br>${esc(h.text)}</div>`).join('')||'<p class="muted">No recent Guardian-led local political activity.</p>',rr.openness>=8?'Roads remain broadly open to travelers and merchants.':rr.openness>=5?'Travel remains possible, with visible checks and controls.':'Travel is tightly controlled and outsiders should expect scrutiny.'),true);
 $('#politicalSituationBack').onclick=()=>townNavCurrent?.route===SOSText("politics_covert_raids.showPoliticalSituation.003")?townNavBackOrExit():showSettlementPolitics(locId)
}

function showLocalPoliticalActions(locId=state.world.location){modalRouteEnter(SOSText("politics_covert_raids.showLocalPoliticalActions.001"),Array.from(arguments));
 overlay(SOSText("politics_covert_raids.showLocalPoliticalActions.002",esc(worldLocation(locId).name),localPoliticalGlanceRowsHTML(locId,'activities')),true);
 document.querySelectorAll('[data-politicalfaction]').forEach(b=>b.onclick=()=>navigateTownMenu('factionCivic',{locId,faction:b.dataset.politicalfaction}));
 $('#nonpartisanPolitics').onclick=()=>navigateTownMenu('independentCivic',{locId});
 $('#politicalActionsBack').onclick=()=>townNavCurrent?.route===SOSText("politics_covert_raids.showLocalPoliticalActions.003")?townNavBackOrExit():showSettlementPolitics(locId)
}
