function factionSocialState(){ensureWorldState();if(!state.world.factionSocial||typeof state.world.factionSocial!=='object')state.world.factionSocial={npcAlignment:{},travelerInfluence:{},history:[],lastDay:state.world.day,lastPressureDay:{}};const F=state.world.factionSocial;if(!F.npcAlignment)F.npcAlignment={};if(!F.travelerInfluence)F.travelerInfluence={};if(!Array.isArray(F.history))F.history=[];if(!F.lastPressureDay||typeof F.lastPressureDay!=='object')F.lastPressureDay={};return F}
function inferNpcFaction(npc,locId){const role=String(npc?.role||'').toLowerCase(),control=settlementControl(locId);if(role.includes('coalition'))return SOSText("politics_faction_social.inferNpcFaction.001");if(role.includes('redstone'))return SOSText("politics_faction_social.inferNpcFaction.002");if(role.includes('bluestone'))return SOSText("politics_faction_social.inferNpcFaction.003");if(role.includes('guardian'))return SOSText("politics_faction_social.inferNpcFaction.004");if(role.includes('guard')||role.includes('watch')||role.includes('officer')||role.includes('sergeant')||role.includes('warden')||role.includes('quartermaster'))return control;if(role.includes('trader')||role.includes('factor')||role.includes('merchant')||role.includes('ferryman')||role.includes('farmer')||role.includes('miller')||role.includes('tavern')||role.includes('inn')||role.includes('roadhouse')||role.includes('cookhouse'))return SOSText("politics_faction_social.inferNpcFaction.005");return control===SOSText("politics_faction_social.inferNpcFaction.006")?'Shantium':control}
function npcPoliticalReason(npc,locId,faction){
 const role=String(npc?.role||'').toLowerCase(),loc=worldLocation(locId),ss=settlementState(locId),control=settlementControl(locId);
 if(faction===SOSText("politics_faction_social.npcPoliticalReason.001")&&(role.includes('merchant')||role.includes('trader')||role.includes('factor')||role.includes('tavern')||role.includes('inn')||role.includes('roadhouse')||role.includes('ferryman')))return SOSText("politics_faction_social.npcPoliticalReason.002");
 if([SOSText("politics_faction_social.npcPoliticalReason.003"),SOSText("politics_faction_social.npcPoliticalReason.004"),SOSText("politics_faction_social.npcPoliticalReason.005"),SOSText("politics_faction_social.npcPoliticalReason.006")].includes(faction)&&(role.includes('guard')||role.includes('watch')||role.includes('officer')||role.includes('warden')||role.includes('sergeant')||role.includes('quartermaster')))return SOSText("politics_faction_social.npcPoliticalReason.007",loc.name);
 if(role.includes('council')||role.includes('speaker')||role.includes('assembly')||role.includes('delegate'))return faction===control?'Believes the current governing arrangement is still the most workable local option.':SOSText("politics_faction_social.npcPoliticalReason.008");
 if(role.includes('healer')||role.includes('teacher')||role.includes('midwife'))return ss.prosperity<50?'Supports whichever local network seems most capable of keeping ordinary households supplied and stable.':SOSText("politics_faction_social.npcPoliticalReason.009");
 if(role.includes('farmer')||role.includes('miller')||role.includes('seed'))return SOSText("politics_faction_social.npcPoliticalReason.010");
 return faction===control?SOSText("politics_faction_social.npcPoliticalReason.011",loc.name):SOSText("politics_faction_social.npcPoliticalReason.012",majorFaction(faction).short)
}
function npcPoliticalSupportLabel(v){return v>=5?'Leading advocate':v>=4?'Organizer':v>=3?'Active supporter':v>=2?'Supporter':v>=1?'Sympathetic':v<=-3?'Strong opponent':v<=-1?'Opponent':SOSText("politics_faction_social.npcPoliticalSupportLabel.001")}
function npcFactionAlignment(npcId){const F=factionSocialState(),home=npcHomeLocation(npcId),npc=settlementNpc(home,npcId);if(!npc)return null;if(!F.npcAlignment[npcId]){const loc=currentNpcLocation(npcId,home),faction=inferNpcFaction(npc,loc),role=String(npc.role||'').toLowerCase(),support=(role.includes('officer')||role.includes('warden')||role.includes('council')||role.includes('speaker')||role.includes('liaison'))?3:2;F.npcAlignment[npcId]={npcId,faction,support,public:true,sinceDay:state.world.day,reason:npcPoliticalReason(npc,loc,faction),lastPoliticalApproachDay:-99}}const a=F.npcAlignment[npcId],loc=currentNpcLocation(npcId,home);if(!Number.isFinite(a.lastPoliticalApproachDay))a.lastPoliticalApproachDay=-99;if(!a.reason||/^Local ties in /i.test(a.reason))a.reason=npcPoliticalReason(npc,loc,a.faction);return a}
function setNpcFactionAlignment(npcId,faction,support=2,reason=SOSText("politics_faction_social.setNpcFactionAlignment.001")){const a=npcFactionAlignment(npcId);if(!a||!OPEN_WORLD_FACTIONS[faction])return null;a.faction=faction;a.support=clamp(support,-3,5);a.reason=reason;a.sinceDay=state.world.day;factionSocialState().history.push({day:state.world.day,type:'npc_alignment',npcId,faction,text:SOSText("politics_faction_social.setNpcFactionAlignment.002",settlementNpc(npcHomeLocation(npcId),npcId)?.name||npcId,a.support<0?'opposes':'supports',majorFaction(faction).short,reason)});return a}
function npcFactionWeightAt(locId,faction){let score=0,F=state.world?.factionSocial;if(!F?.npcAlignment)return 0;for(const [home,list] of Object.entries(SETTLEMENT_NPCS)){for(const npc of list){const base=state.world?.populationMovement?.npcResidences?.[npc.id]?.current||home,move=state.world?.npcMovements?.[npc.id],cur=move&&move.untilDay>=(state.world?.day||1)?move.location:base;if(cur!==locId)continue;const a=F.npcAlignment[npc.id];if(a?.faction===faction)score+=Math.max(-2,a.support||0)*.55}}return score}
function travelerFactionInfluenceAt(locId,faction){let score=0,F=state.world?.factionSocial,R=state.world?.travelerRegistry?.records||{};if(!F?.travelerInfluence)return 0;for(const r of Object.values(R)){if(r.settledAt!==locId)continue;const inf=F.travelerInfluence[r.id];if(inf?.faction===faction)score+=inf.strength||1}return score}
function syncTravelerFactionInfluence(){const F=factionSocialState();for(const r of travelerLedgerRecords()){if(F.travelerInfluence[r.id])continue;let faction=null;if(['coalition','redstone','bluestone','spawn'].includes(r.kind))faction=r.kind[0].toUpperCase()+r.kind.slice(1);else if(r.kind==='merchant'||r.kind==='refugees')faction=SOSText("politics_faction_social.syncTravelerFactionInfluence.001");else if(r.kind==='mercenary')faction=SOSText("politics_faction_social.syncTravelerFactionInfluence.002");if(faction&&OPEN_WORLD_FACTIONS[faction])F.travelerInfluence[r.id]={travelerId:r.id,faction,strength:Math.max(1,Math.min(3,Math.floor((travelerAttitudeScore(r)+4)/4))),sinceDay:state.world.day}}}
function factionSocialInfluenceSummary(locId){syncTravelerFactionInfluence();return Object.keys(OPEN_WORLD_FACTIONS).map(f=>({f,n:npcFactionWeightAt(locId,f),t:travelerFactionInfluenceAt(locId,f)})).filter(x=>Math.abs(x.n)+Math.abs(x.t)>.1).sort((a,b)=>(b.n+b.t)-(a.n+a.t))}
function companionFactionReaction(locId){const comps=activeRoadCompanions();if(!comps.length)return'';const locals=settlementNpcsPresent(locId).filter(n=>{const a=npcFactionAlignment(n.id);return a&&Math.abs(a.support)>=2}),bits=[];for(const m of comps){for(const n of locals){const op=companionNpcOpinionState()[`${m.id}:${n.id}`];if(!op||Math.abs(op.score)<2)continue;const a=npcFactionAlignment(n.id);bits.push(SOSText("politics_faction_social.companionFactionReaction.001",m.name,op.score>0?'is more willing to hear':'is wary of',majorFaction(a.faction).short,n.name));break}if(bits.length>=2)break}return bits.length?SOSText("politics_faction_social.companionFactionReaction.002",bits.map(esc).join('<br>')):''}
function factionPeopleHTML(locId){const people=settlementNpcsPresent(locId).map(n=>({n,a:npcFactionAlignment(n.id)})).filter(x=>x.a&&Math.abs(x.a.support)>=1).sort((a,b)=>Math.abs(b.a.support)-Math.abs(a.a.support)).slice(0,6),travelers=travelerLedgerRecords().filter(r=>r.settledAt===locId&&factionSocialState().travelerInfluence[r.id]).slice(0,4);if(!people.length&&!travelers.length)return SOSText("politics_faction_social.factionPeopleHTML.001");return `${people.map(({n,a})=>`<div class="card compact"><b>${esc(n.name)}</b> — ${esc(n.role)}<br><small>${esc(npcPoliticalSupportLabel(a.support))}: ${a.support<0?'opposes':'supports'} ${esc(majorFaction(a.faction).short)} • ${esc(a.reason)}</small></div>`).join('')}${travelers.map(r=>{const a=factionSocialState().travelerInfluence[r.id];return `<div class="card compact"><b>${esc(r.name)}</b> — recurring road contact<br><small>Carries ${esc(majorFaction(a.faction).short)} influence • strength ${a.strength}</small></div>`}).join('')}`}
function createPoliticalRelationshipContract(locId,faction,sourceNpc=null){let source=null;if(sourceNpc)source={kind:'npc',npc:sourceNpc,weight:8};else{const npc=settlementNpcsPresent(locId).find(n=>npcFactionAlignment(n.id)?.faction===faction);if(npc)source={kind:'npc',npc,weight:7}}if(!source)return null;const q=createRelationshipGeneratedContract(locId,source,true);if(!q)return null;q.politicalRelationship=true;q.faction=faction;q.name=`${majorFaction(faction).short}: ${q.name}`;q.desc=SOSText("politics_faction_social.createPoliticalRelationshipContract.001",q.desc,majorFaction(faction).short);q.reward+=15;return q}
function factionSocialDailyTick(){if(!isOpenWorld())return;const F=factionSocialState();syncTravelerFactionInfluence();const all=WORLD_LOCATIONS.filter(x=>state.world.settlements?.[x.id]),current=worldLocation(state.world.location),targets=[current,...all.filter(x=>x.id!==state.world.location).sort(()=>Math.random()-.5).slice(0,2)].filter(Boolean);for(const loc of targets){if(state.world.day-(F.lastPressureDay[loc.id]||0)>=4){const row=factionSocialInfluenceSummary(loc.id).find(x=>x.n+x.t>=2.5);if(row&&chance(.12)){addPoliticalPressure(loc.id,row.f,.5,SOSText("politics_faction_social.factionSocialDailyTick.001",loc.name));F.lastPressureDay[loc.id]=state.world.day}}if(chance(.025)){const npc=pick(settlementNpcsPresent(loc.id));if(npc){const a=npcFactionAlignment(npc.id),pres=state.world.factionPresence[loc.id]||{},best=Object.entries(pres).sort((a,b)=>b[1]-a[1])[0];if(best&&best[0]!==a.faction&&best[1]>=8)setNpcFactionAlignment(npc.id,best[0],1,SOSText("politics_faction_social.factionSocialDailyTick.002",majorFaction(best[0]).short))}}}F.lastDay=state.world.day;F.history=F.history.slice(-100)}
function showPoliticalEndorsementPeople(locId,faction){modalRouteEnter(SOSText("politics_faction_social.showPoliticalEndorsementPeople.001"),Array.from(arguments));
 const people=settlementNpcsPresent(locId).map(n=>({n,r:npcRelationshipState(n.id),a:npcFactionAlignment(n.id)})).sort((x,y)=>(y.r.familiarity||0)-(x.r.familiarity||0));
 overlay(SOSText("politics_faction_social.showPoliticalEndorsementPeople.002",esc(worldLocation(locId).name),esc(majorFaction(faction).short),people.map(({n,r,a})=>{const cooldown=state.world.day-(a.lastPoliticalApproachDay||-99)<4,ready=r.familiarity>=3&&!cooldown;return `<button class="political-person-row" data-politicsperson="${n.id}" ${ready?'':'disabled'}><span><b>${esc(n.name)}</b><small>${esc(n.role)} • ${esc(npcFamiliarityTier(r.familiarity))} • ${esc(npcPoliticalSupportLabel(a.support))} ${esc(majorFaction(a.faction).short)}</small></span><small>${cooldown?'Discussed politics recently':r.familiarity<3?'Become acquainted first':'Ask for public support'}</small></button>`}).join('')||'<p class="muted">No named residents are available here.</p>'),true);
 document.querySelectorAll('[data-politicsperson]').forEach(b=>b.onclick=()=>attemptNpcPoliticalEndorsement(locId,b.dataset.politicsperson,faction));$('#endorsementPeopleBack').onclick=()=>showFactionCivicActions(locId,faction)
}
function attemptNpcPoliticalEndorsement(locId,npcId,faction){
 const npc=settlementNpc(locId,npcId)||settlementNpc(npcHomeLocation(npcId),npcId),r=npcRelationshipState(npcId),a=npcFactionAlignment(npcId);if(!npc||!a)return showPoliticalEndorsementPeople(locId,faction);const before=politicalOutcomeSnapshot(locId,[faction,a.faction]),beforeOpinion=r.opinion||0;
 if(state.world.day-(a.lastPoliticalApproachDay||-99)<4)return actionResult(SOSText("politics_faction_social.attemptNpcPoliticalEndorsement.001"),SOSText("politics_faction_social.attemptNpcPoliticalEndorsement.002",npc.name),'info',()=>showPoliticalEndorsementPeople(locId,faction));
 const standing=state.world.factionStanding[faction]||0,oldFaction=a.faction,oldSupport=a.support||0,conflict=oldFaction!==faction?Math.max(0,oldSupport)*2:0,relationPenalty=oldFaction!==faction&&factionRelation(oldFaction,faction)<=-2?2:0,difficulty=14+conflict+relationPenalty;
 const roll=rnd(1,20)+stat(state,'cha')+Math.floor(localReputation(locId)/2)+Math.floor((r.familiarity||0)/2)+Math.floor((r.opinion||0)/2)+Math.floor(standing/3);a.lastPoliticalApproachDay=state.world.day;
 let text='',tone='info';
 if(oldFaction===faction&&oldSupport>=3){text=SOSText("politics_faction_social.attemptNpcPoliticalEndorsement.003",npc.name,majorFaction(faction).short);a.support=clamp(oldSupport+1,-3,5);applyLocalPoliticalEffects(locId,faction,{support:.75,organization:.5,power:1.5,pressure:.25},SOSText("politics_faction_social.attemptNpcPoliticalEndorsement.004",npc.name),'personnel');tone='good'}
 else if(roll>=difficulty){const strength=roll>=difficulty+6?3:2;setNpcFactionAlignment(npcId,faction,strength,SOSText("politics_faction_social.attemptNpcPoliticalEndorsement.005",npc.name,majorFaction(faction).short));adjustPoliticalCapital(locId,faction,1.5,SOSText("politics_faction_social.attemptNpcPoliticalEndorsement.006",npc.name));applyLocalPoliticalEffects(locId,faction,{support:1.25,legitimacy:.5,power:2,pressure:.4,rival:.4},SOSText("politics_faction_social.attemptNpcPoliticalEndorsement.007",npc.name,majorFaction(faction).short),'personnel');text=SOSText("politics_faction_social.attemptNpcPoliticalEndorsement.008",npc.name,majorFaction(faction).short,npc.name);tone='good';r.opinion=clamp((r.opinion||0)+1,-8,8)}
 else {text=SOSText("politics_faction_social.attemptNpcPoliticalEndorsement.009",npc.name,majorFaction(faction).short,oldFaction!==faction&&oldSupport>=3?`Their existing commitment to ${majorFaction(oldFaction).short} is too strong to set aside after one conversation.`:'They are not willing to attach their name to the faction publicly.');if(oldFaction!==faction&&oldSupport>=3)r.opinion=clamp((r.opinion||0)-1,-8,8)}
 npcMemoryAdd(npcId,SOSText("politics_faction_social.attemptNpcPoliticalEndorsement.010",npc.name,majorFaction(faction).short),tone==='good'?1:0);recordLocalPoliticalAction(locId,faction,'endorsement',text);const after=politicalOutcomeSnapshot(locId,[faction,a.faction]),notes=[];if((r.opinion||0)!==beforeOpinion)notes.push(SOSText("politics_faction_social.attemptNpcPoliticalEndorsement.011",npc.name,r.opinion>beforeOpinion?'improved':'worsened',beforeOpinion,r.opinion));advanceWorldDays(1,SOSText("politics_faction_social.attemptNpcPoliticalEndorsement.012",npc.name));save();showPoliticalOutcome(SOSText("politics_faction_social.attemptNpcPoliticalEndorsement.013"),text,before,after,{tone,notes,back:()=>showLocalPoliticalActions(locId)})
}
function showNpcPoliticalConversation(locId,npcId){modalRouteEnter(SOSText("politics_faction_social.showNpcPoliticalConversation.001"),Array.from(arguments));
 const npc=settlementNpc(locId,npcId)||settlementNpc(npcHomeLocation(npcId),npcId),a=npcFactionAlignment(npcId),r=npcRelationshipState(npcId);if(!npc||!a)return showSettlementNPCConversation(locId,npcId);
 const factions=localPoliticalFactions(locId);
 overlay(SOSText("politics_faction_social.showNpcPoliticalConversation.002",esc(npc.name),esc(npcPoliticalSupportLabel(a.support)),a.support<0?'opposes':'supports',esc(majorFaction(a.faction).short),esc(a.reason),esc(npc.name),esc(npcAttitudeLabel(r).toLowerCase()),r.familiarity>=3?`<div class="notice compact"><b>Ask for an endorsement:</b></div>${factions.map(f=>`<button data-npcendorsefaction="${f}">${esc(majorFaction(f).short)}</button>`).join('')}`:'<button disabled>Become Acquainted Before Asking for an Endorsement</button>'),true);
 $('#npcPoliticsWhy').onclick=()=>actionResult(SOSText("politics_faction_social.showNpcPoliticalConversation.003",npc.name),a.reason,'info',()=>showNpcPoliticalConversation(locId,npcId));document.querySelectorAll('[data-npcendorsefaction]').forEach(b=>b.onclick=()=>attemptNpcPoliticalEndorsement(locId,npcId,b.dataset.npcendorsefaction));$('#npcPoliticsBack').onclick=()=>showSettlementNPCConversation(locId,npcId)
}
function showLocalPoliticalPeople(locId=state.world.location,back=null){modalRouteEnter(SOSText("politics_faction_social.showLocalPoliticalPeople.001"),Array.from(arguments));
 const people=settlementNpcsPresent(locId).map(n=>({n,a:npcFactionAlignment(n.id),r:npcRelationshipState(n.id)})).sort((x,y)=>Math.abs(y.a.support)-Math.abs(x.a.support)||(y.r.familiarity||0)-(x.r.familiarity||0));
 overlay(SOSText("politics_faction_social.showLocalPoliticalPeople.002",esc(worldLocation(locId).name),people.map(({n,a,r})=>`<button class="political-person-row" data-localpoliticalnpc="${n.id}"><span><b>${esc(n.name)}</b><small>${esc(n.role)} • ${esc(npcPoliticalSupportLabel(a.support))}: ${a.support<0?'opposes':'supports'} ${esc(majorFaction(a.faction).short)}</small></span><small>${esc(npcFamiliarityTier(r.familiarity))}</small></button>`).join('')||'<p class="muted">No named residents are available here.</p>',companionFactionReaction(locId)),true);
 document.querySelectorAll('[data-localpoliticalnpc]').forEach(b=>b.onclick=()=>showNpcPoliticalConversation(locId,b.dataset.localpoliticalnpc));$('#localPoliticalPeopleBack').onclick=back||(()=>showSettlementPolitics(locId))
}
function showFactionSocialNetwork(locId=state.world.location,parent='overview'){modalRouteEnter(SOSText("politics_faction_social.showFactionSocialNetwork.001"),Array.from(arguments));
 const rows=factionSocialInfluenceSummary(locId),F=factionSocialState(),fromPolitics=townNavCurrent?.route===SOSText("politics_faction_social.showFactionSocialNetwork.002")&&townNavStack?.[townNavStack.length-1]?.route==='politics';
 overlay(SOSText("politics_faction_social.showFactionSocialNetwork.003",esc(worldLocation(locId).name),rows.length?`<div class="card">${rows.map(x=>`<div class="stat-row"><span>${esc(majorFaction(x.f).short)}</span><b>People ${x.n.toFixed(1)} • Travelers ${x.t.toFixed(1)}</b></div>`).join('')}</div>`:'',factionPeopleHTML(locId),companionFactionReaction(locId),F.history.slice(-12).reverse().map(x=>`<div class="card compact"><b>Day ${x.day}</b><br>${esc(x.text)}</div>`).join('')||'<p class="muted">No recent changes.</p>',fromPolitics?'Back to Local Politics':'Back to Factions'),true);
 $('#localPoliticalVoices').onclick=()=>showLocalPoliticalPeople(locId,()=>showFactionSocialNetwork(locId,parent));
 $('#factionSocialBack').onclick=()=>parent===SOSText("politics_faction_social.showFactionSocialNetwork.004")&&townNavCurrent?townNavBackOrExit():fromPolitics?showSettlementPolitics(locId):showFactionOverview()
}
function factionPresenceAt(locId){
 ensureFactionPresence();const base={...(state.world.factionPresence[locId]||{})};
 for(const p of state.world.parties||[]){if(p.location!==locId&&p.destination!==locId)continue;if(OPEN_WORLD_FACTIONS[p.faction])base[p.faction]=(base[p.faction]||0)+(p.kind==='merchant'||p.kind==='refugees'?1:2)}
 if(!WORLD_STATE_ENSURING&&state.world.factionSocial){for(const f of Object.keys(OPEN_WORLD_FACTIONS)){const social=npcFactionWeightAt(locId,f)+travelerFactionInfluenceAt(locId,f);if(Math.abs(social)>=1)base[f]=Math.max(0,(base[f]||0)+Math.round(social*.45))}}
 return base
}
function factionPresenceTier(v){return v>=10?'Dominant':v>=7?'Strong':v>=4?'Established':v>=2?'Visible':v>=1?'Small':SOSText("politics_faction_social.factionPresenceTier.001")}
function factionPostName(locId,faction){return FACTION_POST_NAMES[locId]?.[faction]||SOSText("politics_faction_social.factionPostName.001",majorFaction(faction).short)}
function factionRepresentativesAt(locId){
 const p=factionPresenceAt(locId);
 return Object.entries(p).filter(([f,v])=>OPEN_WORLD_FACTIONS[f]&&v>=1).sort((a,b)=>b[1]-a[1])
}
function factionPresenceSummary(locId){
 const reps=factionRepresentativesAt(locId);return reps.length?reps.map(([f,v])=>`${majorFaction(f).short}: ${factionPresenceTier(v)}`).join(' • '):SOSText("politics_faction_social.factionPresenceSummary.001")
}
function factionAttitudeText(faction){
 const v=state.world.factionStanding[faction]||0;
 if(v<=-8)return SOSText("politics_faction_social.factionAttitudeText.001");if(v<=-3)return SOSText("politics_faction_social.factionAttitudeText.002");if(v<3)return SOSText("politics_faction_social.factionAttitudeText.003");if(v<8)return SOSText("politics_faction_social.factionAttitudeText.004");return SOSText("politics_faction_social.factionAttitudeText.005")
}
function factionLocalEffect(locId,faction){
 const ss=settlementState(locId),v=factionPresenceAt(locId)[faction]||0;
 if(faction===SOSText("politics_faction_social.factionLocalEffect.001"))return SOSText("politics_faction_social.factionLocalEffect.002",v>=7?' are highly visible here.':'.');
 if(faction===SOSText("politics_faction_social.factionLocalEffect.003"))return locationRegion(locId)==='redstone'?SOSText("politics_faction_social.factionLocalEffect.004",v>=7?' visibly shape daily life here.':'.'):SOSText("politics_faction_social.factionLocalEffect.005",v>=7?' shape daily movement through the settlement.':'.');
 if(faction===SOSText("politics_faction_social.factionLocalEffect.006"))return SOSText("politics_faction_social.factionLocalEffect.007",v>=7?' retain most practical authority here.':'.');
 if(faction===SOSText("politics_faction_social.factionLocalEffect.008"))return SOSText("politics_faction_social.factionLocalEffect.009");
 if(faction===SOSText("politics_faction_social.factionLocalEffect.010"))return SOSText("politics_faction_social.factionLocalEffect.011");
 if(faction===SOSText("politics_faction_social.factionLocalEffect.012"))return locationRegion(locId)==='bluestone'?SOSText("politics_faction_social.factionLocalEffect.013"):SOSText("politics_faction_social.factionLocalEffect.014");
 if(faction===SOSText("politics_faction_social.factionLocalEffect.015"))return SOSText("politics_faction_social.factionLocalEffect.016");
 return SOSText("politics_faction_social.factionLocalEffect.017",ss.security,ss.prosperity)
}
function factionPostAvailable(locId,faction){return (factionPresenceAt(locId)[faction]||0)>=1}
function showFactionPost(locId,faction){modalRouteEnter(SOSText("politics_faction_social.showFactionPost.001"),Array.from(arguments));
 if(!factionPostAvailable(locId,faction))return showSettlementFactions(locId);
 const def=majorFaction(faction),standing=state.world.factionStanding[faction]||0,pres=factionPresenceAt(locId)[faction]||0,control=settlementControl(locId);
 const hostile=standing<=-8,priv=factionPrivileges(faction),relations=Object.keys(OPEN_WORLD_FACTIONS).filter(f=>f!==faction).map(f=>[f,factionRelation(faction,f)]).filter(x=>Math.abs(x[1])>=2).sort((a,b)=>Math.abs(b[1])-Math.abs(a[1]));
 overlay(SOSText("politics_faction_social.showFactionPost.002",esc(factionPostName(locId,faction)),esc(def.name),esc(factionPresenceTier(pres)),esc(factionAttitudeText(faction)),esc(def.desc),esc(currentFactionPriority(faction).label),esc(def.agenda),esc(factionLocalEffect(locId,faction)),esc(control),standing>=0?'+':'',standing,priv.length?`<h3>Standing Effects</h3><ul>${priv.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:'',relations.length?`<h3>Regional Relations</h3><p class="compact">${relations.map(([f,v])=>`${esc(majorFaction(f).short)}: <b>${esc(factionRelationLabel(v))}</b>`).join(' • ')}</p>`:'',hostile?'disabled':'',hostile?'disabled':'',hostile?'disabled':'',hostile?'disabled':'',hostile?'disabled':'',faction==='Redstone'&&standing<0?'<button id="fpParley">Request Formal Parley</button>':''));
 if($('#fpTalk'))$('#fpTalk').onclick=()=>factionRepresentativeTalk(locId,faction);
 if($('#fpWork'))$('#fpWork').onclick=()=>factionRepresentativeWork(locId,faction);
 if($('#fpCampaign'))$('#fpCampaign').onclick=()=>navigateTownMenu(SOSText("politics_faction_social.showFactionPost.003"),{locId,faction});
 if($('#fpPolitical'))$('#fpPolitical').onclick=()=>navigateTownMenu(SOSText("politics_faction_social.showFactionPost.004"),{locId,faction});
 if($('#fpSupport'))$('#fpSupport').onclick=()=>supportLocalFaction(locId,faction);
 if($('#fpParley'))$('#fpParley').onclick=()=>factionParley(locId,faction);
 wireClose()
}
function factionRepresentativeTalk(locId,faction){
 const def=majorFaction(faction),standing=state.world.factionStanding[faction]||0,pres=factionPresenceAt(locId)[faction]||0;
 const localPower=politicalPowerSummary(locId,faction),priority=currentFactionPriority(faction);const relation=standing>=8?'They speak openly and treat the Guardian as a proven ally.':standing>=3?'The conversation is cooperative, though not everything is shared.':standing<=-3?'The exchange is guarded and brief.':SOSText("politics_faction_social.factionRepresentativeTalk.001");
 actionResult(def.name,SOSText("politics_faction_social.factionRepresentativeTalk.002",relation,def.agenda,factionPresenceTier(pres).toLowerCase(),worldLocation(locId).name),'info',()=>showFactionPost(locId,faction))
}
function factionRepresentativeWork(locId,faction){
 const available=availableFactionQuestlinesHere().filter(q=>q.faction===faction);
 if(available.length)return showFactionQuestlines();
 const active=Object.values(FACTION_QUESTLINES).filter(d=>d.faction===faction&&factionQuestState(d.id).active);
 if(active.length)return actionResult(SOSText("politics_faction_social.factionRepresentativeWork.001"),SOSText("politics_faction_social.factionRepresentativeWork.002",majorFaction(faction).name),'info',()=>showFactionPost(locId,faction));
 const standing=state.world.factionStanding[faction]||0;
 if(standing<0)return actionResult(SOSText("politics_faction_social.factionRepresentativeWork.003"),SOSText("politics_faction_social.factionRepresentativeWork.004"),'info',()=>showFactionPost(locId,faction));
 const board=(state.world.quests||[]).filter(q=>['active','ready'].includes(q.status)&&q.origin===locId&&q.faction===faction);
 if(board.length)return showContractsJournal();
 const existing=(state.world.contracts[locId]||[]).find(q=>q.status==='offered'&&q.regional&&q.faction===faction);if(existing)return showContractBoard(locId);
 const commissioned=generateFactionRegionalContract(locId,faction);
 if(commissioned){save();return actionResult(SOSText("politics_faction_social.factionRepresentativeWork.005"),SOSText("politics_faction_social.factionRepresentativeWork.006",majorFaction(faction).name,worldLocation(locId).name,commissioned.name,commissioned.desc),'good',()=>showContractBoard(locId))}
 const need=politicalCampaignNeed(locId,faction),rival=need.rival;if(rival&&(localPoliticalProfile(locId,rival).overall>=localPoliticalProfile(locId,faction).overall-5))return actionResult(SOSText("politics_faction_social.factionRepresentativeWork.007"),SOSText("politics_faction_social.factionRepresentativeWork.008",majorFaction(faction).short,need.label.toLowerCase()),'info',()=>showPoliticalCampaignDesk(locId,faction));
 actionResult(SOSText("politics_faction_social.factionRepresentativeWork.009"),SOSText("politics_faction_social.factionRepresentativeWork.010",majorFaction(faction).short),'info',()=>showFactionPost(locId,faction))
}
function supportLocalFaction(locId,faction){
 const before=politicalOutcomeSnapshot(locId,[faction,localPoliticalRival(locId,faction)]),cost=18+Math.max(0,Math.round((factionPresenceAt(locId)[faction]||1)*2));
 if(state.gold<cost)return actionResult(SOSText("politics_faction_social.supportLocalFaction.001"),SOSText("politics_faction_social.supportLocalFaction.002",cost),'info',()=>showFactionPost(locId,faction));
 pay(state,cost);const p=state.world.factionPresence[locId];p[faction]=Math.min(12,(p[faction]||0)+1);state.world.factionStanding[faction]=(state.world.factionStanding[faction]||0)+1;recordFactionPower(locId,faction,'guardian',2,SOSText("politics_faction_social.supportLocalFaction.003"),8);addPoliticalPressure(locId,faction,1,SOSText("politics_faction_social.supportLocalFaction.004"));
 const ss=settlementState(locId);if([SOSText("politics_faction_social.supportLocalFaction.005"),SOSText("politics_faction_social.supportLocalFaction.006"),SOSText("politics_faction_social.supportLocalFaction.007")].includes(faction))ss.security=Math.min(100,ss.security+1);if([SOSText("politics_faction_social.supportLocalFaction.008"),SOSText("politics_faction_social.supportLocalFaction.009")].includes(faction))ss.prosperity=Math.min(100,ss.prosperity+1);
 changeLocalReputation(locId,1,SOSText("politics_faction_social.supportLocalFaction.010",majorFaction(faction).short));recordWorldHistory(SOSText("politics_faction_social.supportLocalFaction.011",state.name,majorFaction(faction).name,worldLocation(locId).name),'info','faction');const after=politicalOutcomeSnapshot(locId,[faction,localPoliticalRival(locId,faction)]);save();
 showPoliticalOutcome(SOSText("politics_faction_social.supportLocalFaction.012"),SOSText("politics_faction_social.supportLocalFaction.013",majorFaction(faction).name,worldLocation(locId).name),before,after,{tone:'good',notes:[SOSText("politics_faction_social.supportLocalFaction.014",cost)],back:()=>showFactionPost(locId,faction)})
}
function factionParley(locId,faction){
 const before=politicalOutcomeSnapshot(locId,[faction]),roll=rnd(1,12)+stat(state,'cha')+Math.floor(localReputation(locId)/3);
 if(roll>=10){state.world.factionStanding[faction]=(state.world.factionStanding[faction]||0)+2;recordWorldHistory(SOSText("politics_faction_social.factionParley.001",majorFaction(faction).name,worldLocation(locId).name),'good','faction');const after=politicalOutcomeSnapshot(locId,[faction]);save();return showPoliticalOutcome(SOSText("politics_faction_social.factionParley.002"),SOSText("politics_faction_social.factionParley.003"),before,after,{tone:'good',back:()=>showFactionPost(locId,faction)})}
 state.world.factionStanding[faction]=(state.world.factionStanding[faction]||0)-1;const after=politicalOutcomeSnapshot(locId,[faction]);save();showPoliticalOutcome(SOSText("politics_faction_social.factionParley.004"),SOSText("politics_faction_social.factionParley.005"),before,after,{tone:'bad',back:()=>showFactionPost(locId,faction)})
}
function showSettlementFactions(locId=state.world.location){modalRouteEnter(SOSText("politics_faction_social.showSettlementFactions.001"),Array.from(arguments));
 const loc=worldLocation(locId),reps=factionRepresentativesAt(locId),control=settlementControl(locId),incident=activeFactionIncident(locId);
 overlay(SOSText("politics_faction_social.showSettlementFactions.002",esc(loc.name),regionalSettlementPoliticsHTML(locId),locationRegion(locId)==='redstone'?redstonePolicyNoticeHTML(locId):'',incident?`<div class="warning notice"><b>${esc(incident.title)}</b><br>${esc(incident.text)}<br><button id="factionIncident">Get Involved</button></div>`:'',esc(control),esc(factionPresenceSummary(locId)),reps.map(([f,v])=>`<button class="relationship-pair faction-presence-row" data-factionpost="${f}"><span><b>${esc(factionPostName(locId,f))}</b><small>${esc(majorFaction(f).name)} • ${esc(factionLocalEffect(locId,f))}</small></span><b>${esc(factionPresenceTier(v))}</b></button>`).join('')||'<p class="muted">No organized faction representatives are currently present.</p>'),true);
 document.querySelectorAll('[data-factionpost]').forEach(b=>b.onclick=()=>navigateTownMenu(SOSText("politics_faction_social.showSettlementFactions.003"),{locId,faction:b.dataset.factionpost}));
 if($('#factionIncident'))$('#factionIncident').onclick=()=>showFactionIncident(locId);
 wireClose()
}

const BLUESTONE_LOCAL_POLITICS={
 zion:{issue:SOSText("politics_faction_social.showSettlementFactions.004"),central:SOSText("politics_faction_social.showSettlementFactions.005"),local:SOSText("politics_faction_social.showSettlementFactions.006"),independent:SOSText("politics_faction_social.showSettlementFactions.007"),bluestone:SOSText("politics_faction_social.showSettlementFactions.008")},
 lowcreek:{issue:SOSText("politics_faction_social.showSettlementFactions.009"),central:SOSText("politics_faction_social.showSettlementFactions.010"),local:SOSText("politics_faction_social.showSettlementFactions.011"),independent:SOSText("politics_faction_social.showSettlementFactions.012"),bluestone:SOSText("politics_faction_social.showSettlementFactions.013")},
 ebonheart:{issue:SOSText("politics_faction_social.showSettlementFactions.014"),central:SOSText("politics_faction_social.showSettlementFactions.015"),local:SOSText("politics_faction_social.showSettlementFactions.016"),independent:SOSText("politics_faction_social.showSettlementFactions.017"),bluestone:SOSText("politics_faction_social.showSettlementFactions.018")},
 norwegian:{issue:SOSText("politics_faction_social.showSettlementFactions.019"),central:SOSText("politics_faction_social.showSettlementFactions.020"),local:SOSText("politics_faction_social.showSettlementFactions.021"),independent:SOSText("politics_faction_social.showSettlementFactions.022"),bluestone:SOSText("politics_faction_social.showSettlementFactions.023")},
 winterstone:{issue:SOSText("politics_faction_social.showSettlementFactions.024"),central:SOSText("politics_faction_social.showSettlementFactions.025"),local:SOSText("politics_faction_social.showSettlementFactions.026"),independent:SOSText("politics_faction_social.showSettlementFactions.027"),bluestone:SOSText("politics_faction_social.showSettlementFactions.028")},
 skybreak:{issue:SOSText("politics_faction_social.showSettlementFactions.029"),central:SOSText("politics_faction_social.showSettlementFactions.030"),local:SOSText("politics_faction_social.showSettlementFactions.031"),independent:SOSText("politics_faction_social.showSettlementFactions.032"),bluestone:SOSText("politics_faction_social.showSettlementFactions.033")}
};
function bluestonePoliticsHTML(id){const p=BLUESTONE_LOCAL_POLITICS[id];if(!p)return'';return SOSText("politics_faction_social.bluestonePoliticsHTML.001",esc(p.issue),esc(p.bluestone),esc(p.central),esc(p.independent),esc(p.local))}


const REDSTONE_LOCAL_POLITICS={
 sengia:{issue:SOSText("politics_faction_social.bluestonePoliticsHTML.002"),central:SOSText("politics_faction_social.bluestonePoliticsHTML.003"),local:SOSText("politics_faction_social.bluestonePoliticsHTML.004"),redstone:SOSText("politics_faction_social.bluestonePoliticsHTML.005"),localName:SOSText("politics_faction_social.bluestonePoliticsHTML.006")},
 lockwood:{issue:SOSText("politics_faction_social.bluestonePoliticsHTML.007"),central:SOSText("politics_faction_social.bluestonePoliticsHTML.008"),local:SOSText("politics_faction_social.bluestonePoliticsHTML.009"),redstone:SOSText("politics_faction_social.bluestonePoliticsHTML.010"),localName:SOSText("politics_faction_social.bluestonePoliticsHTML.011")},
 grayhaven:{issue:SOSText("politics_faction_social.bluestonePoliticsHTML.012"),central:SOSText("politics_faction_social.bluestonePoliticsHTML.013"),local:SOSText("politics_faction_social.bluestonePoliticsHTML.014"),redstone:SOSText("politics_faction_social.bluestonePoliticsHTML.015"),localName:SOSText("politics_faction_social.bluestonePoliticsHTML.016")},
 briarlake:{issue:SOSText("politics_faction_social.bluestonePoliticsHTML.017"),central:SOSText("politics_faction_social.bluestonePoliticsHTML.018"),local:SOSText("politics_faction_social.bluestonePoliticsHTML.019"),redstone:SOSText("politics_faction_social.bluestonePoliticsHTML.020"),localName:SOSText("politics_faction_social.bluestonePoliticsHTML.021")},
 glenbrook:{issue:SOSText("politics_faction_social.bluestonePoliticsHTML.022"),central:SOSText("politics_faction_social.bluestonePoliticsHTML.023"),local:SOSText("politics_faction_social.bluestonePoliticsHTML.024"),redstone:SOSText("politics_faction_social.bluestonePoliticsHTML.025"),localName:SOSText("politics_faction_social.bluestonePoliticsHTML.026")},
 tyrdon:{issue:SOSText("politics_faction_social.bluestonePoliticsHTML.027"),central:SOSText("politics_faction_social.bluestonePoliticsHTML.028"),local:SOSText("politics_faction_social.bluestonePoliticsHTML.029"),redstone:SOSText("politics_faction_social.bluestonePoliticsHTML.030"),localName:SOSText("politics_faction_social.bluestonePoliticsHTML.031")},
 pyreglade:{issue:SOSText("politics_faction_social.bluestonePoliticsHTML.032"),central:SOSText("politics_faction_social.bluestonePoliticsHTML.033"),local:SOSText("politics_faction_social.bluestonePoliticsHTML.034"),redstone:SOSText("politics_faction_social.bluestonePoliticsHTML.035"),localName:SOSText("politics_faction_social.bluestonePoliticsHTML.036")}
};
function redstonePoliticsHTML(id){const p=REDSTONE_LOCAL_POLITICS[id];if(!p)return'';return `<div class="redstone-politics"><h3>${esc(p.issue)}</h3><div class="politics-side"><b>${esc(p.redstone)}</b><p>${esc(p.central)}</p></div><div class="politics-side"><b>${esc(p.localName)}</b><p>${esc(p.local)}</p></div></div>`}
function regionalSettlementPoliticsHTML(id){return bluestonePoliticsHTML(id)||redstonePoliticsHTML(id)}
function showFactionOverview(){modalRouteEnter(SOSText("politics_faction_social.showFactionOverview.001"),Array.from(arguments));
 ensureFactionPresence();const region=currentWorldRegion(),factions=Object.keys(OPEN_WORLD_FACTIONS);
 overlay(SOSText("politics_faction_social.showFactionOverview.002",esc(regionDef(region).name),factions.map(f=>{const def=majorFaction(f),standing=state.world.factionStanding[f]||0,places=WORLD_LOCATIONS.filter(l=>locationRegion(l)===region&&state.world.settlements?.[l.id]&&(factionPresenceAt(l.id)[f]||0)>0).sort((a,b)=>(factionPresenceAt(b.id)[f]||0)-(factionPresenceAt(a.id)[f]||0));return `<div class="card"><b>${esc(def.name)}</b> — ${esc(factionTier(standing))} ${standing>=0?'+':''}${standing}<p>${esc(def.desc)}</p><small>${places.length?`Presence: ${places.slice(0,4).map(l=>`${esc(l.name)} (${esc(factionPresenceTier(factionPresenceAt(l.id)[f]))})`).join(' • ')}`:'No known organized presence in the current region.'}</small></div>`}).join(''),Object.keys(state.world.factionDiplomacy).map(k=>{const [a,b]=k.split('|'),v=state.world.factionDiplomacy[k];return `<div><span>${esc(majorFaction(a).short)} ↔ ${esc(majorFaction(b).short)}</span><b>${esc(factionRelationLabel(v))}</b></div>`}).join(''),factionSecurityResponseState().history.slice(-8).reverse().map(x=>`<div class="card compact"><b>Day ${x.day} • ${esc(x.faction)}</b><br>${esc(x.text)}</div>`).join('')||'<p class="muted">No faction security response recorded yet.</p>'),true);$('#regionalPolitics').onclick=showRegionalPolitics;if($('#factionPeopleNetwork'))$('#factionPeopleNetwork').onclick=()=>showFactionSocialNetwork(state.world.location,'overview');wireClose()
}
function simulateFactionPresence(){
 if(!isOpenWorld())return;ensureFactionPresence();
 for(const loc of WORLD_LOCATIONS.filter(x=>state.world.settlements?.[x.id])){
  const p=state.world.factionPresence[loc.id],ss=settlementState(loc.id);
  for(const f of Object.keys(p))if(p[f]>0&&chance(.12))p[f]=Math.max(0,p[f]-1);
  for(const party of state.world.parties||[]){
   if((party.location===loc.id||party.destination===loc.id)&&OPEN_WORLD_FACTIONS[party.faction]&&chance(.28))p[party.faction]=Math.min(12,(p[party.faction]||0)+1)
  }
  const [dom,val]=Object.entries(p).sort((a,b)=>b[1]-a[1])[0]||[SOSText("politics_faction_social.simulateFactionPresence.001"),0];
  if(val>=8&&dom!==settlementControl(loc.id))addPoliticalPressure(loc.id,dom,val>=10?1:.5,SOSText("politics_faction_social.simulateFactionPresence.002"));
 }
 state.world.factionActivityDay=state.world.day
}
function settlementInfluence(id){ensureWorldState();return factionPresenceAt(id)}
function dominantInfluence(id){
 const inf=settlementInfluence(id);
 return Object.entries(inf).sort((a,b)=>b[1]-a[1])[0];
}
function updateSettlementControl(){for(const loc of WORLD_LOCATIONS.filter(x=>state.world.settlements?.[x.id]))evaluatePoliticalShift(loc.id)}

function settlementControl(id){const ss=settlementState(id);return ss.control||worldLocation(id).faction||SOSText("politics_faction_social.settlementControl.001")}
function defaultFactionStanding(){return {Shantium:5,Independent:0,Coalition:0,Redstone:-2,Bluestone:0,Spawn:0,Raiders:-8,Outlaws:-8,Mercenaries:0}}
