import {get,put} from './db.js';
export function mondayOf(date=new Date()){const d=new Date(date);const day=(d.getDay()+6)%7;d.setHours(12,0,0,0);d.setDate(d.getDate()-day);return d;}
export function isoDate(d){return d.toISOString().slice(0,10);}
export function weekId(date=new Date()){return `week-${isoDate(mondayOf(date))}`;}
export async function loadWeek(date=new Date()){const id=weekId(date);const p=await get('mealPlans',id);return p?{...p,entries:p.entries||[],exclusions:p.exclusions||[]}:{id,start:isoDate(mondayOf(date)),entries:[],exclusions:[]};}
export async function saveWeek(plan){plan.entries=plan.entries||[];plan.exclusions=plan.exclusions||[];return put('mealPlans',plan);}
export async function addMeal(date,dayIndex,mealType,recipeId,servings=1){const plan=await loadWeek(date);plan.exclusions=plan.exclusions.filter(x=>!(x.dayIndex===dayIndex&&x.mealType===mealType));plan.entries.push({id:`meal-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,dayIndex,mealType,recipeId,servings:Number(servings)||1});await saveWeek(plan);return plan;}
export async function removeMeal(date,entryId){const plan=await loadWeek(date);plan.entries=plan.entries.filter(e=>e.id!==entryId);await saveWeek(plan);return plan;}
export async function clearWeek(date,{clearExclusions=false}={}){const plan=await loadWeek(date);plan.entries=[];if(clearExclusions)plan.exclusions=[];plan.autoPlan=null;await saveWeek(plan);return plan;}
export async function moveMeal(date,entryId,dayIndex,mealType){const plan=await loadWeek(date);const e=plan.entries.find(x=>x.id===entryId);if(!e)return plan;plan.exclusions=plan.exclusions.filter(x=>!(x.dayIndex===dayIndex&&x.mealType===mealType));e.dayIndex=Number(dayIndex);e.mealType=mealType;await saveWeek(plan);return plan;}
export async function setMealExclusion(date,dayIndex,mealType,note='Meal planning not needed'){const plan=await loadWeek(date);plan.entries=plan.entries.filter(e=>!(e.dayIndex===dayIndex&&e.mealType===mealType));const current=plan.exclusions.find(x=>x.dayIndex===dayIndex&&x.mealType===mealType);if(current)current.note=note||'Meal planning not needed';else plan.exclusions.push({id:`skip-${dayIndex}-${mealType}`,dayIndex,mealType,note:note||'Meal planning not needed'});await saveWeek(plan);return plan;}
export async function clearMealExclusion(date,dayIndex,mealType){const plan=await loadWeek(date);plan.exclusions=plan.exclusions.filter(x=>!(x.dayIndex===dayIndex&&x.mealType===mealType));await saveWeek(plan);return plan;}

const WEIGHTS={breakfast:.25,lunch:.30,dinner:.35,snack:.10,dessert:.10};
function recipeText(r){return [r.title,r.description,...(r.tags||[]),...(r.derivedTags||[]),...(r.mealPrepNotes||[]),...(r.storageNotes||[]),...(r.reheatingNotes||[]),...(r.tips||[]),...(r.instructions||[])].join(' ').toLowerCase();}
function minuteEstimate(recipe){const text=recipeText(recipe);let max=0;for(const m of text.matchAll(/(\d{1,3})(?:\s*[-–]\s*(\d{1,3}))?\s*(?:minutes?|mins?)\b/g)){max=Math.max(max,Number(m[2]||m[1]));}return max||null;}
function compactLunchScore(recipe){const t=recipeText(recipe);let s=0;if(/sandwich|wrap|pita|burrito|quesadilla|salad|bowl|jar|lunch box|lunchbox|pack|portable|make-ahead|meal prep|meal-prep/.test(t))s+=1.2;if(/soup|chili/.test(t))s+=.25;if(/casserole|platter|feast|skillet|pizza|nachos|dippers|toppers/.test(t))s-=.75;if((recipe.ingredients||[]).length>12)s-=.25;if((recipe.equipment||[]).length>2)s-=.15;return s;}
function easeScore(recipe){const t=recipeText(recipe);let s=0;const mins=minuteEstimate(recipe);if(mins!=null){if(mins<=20)s+=1.4;else if(mins<=30)s+=.9;else if(mins<=45)s+=.15;else s-=1.1;}if(/quick|easy|stupid easy|15 minute|20 minute|one pan|one-pan|no cook|microwave|toaster oven/.test(t))s+=1;if(/slow cooker|crockpot/.test(t))s+=.2;if(/roast|bake|casserole/.test(t)&&mins&&mins>40)s-=.5;const steps=(recipe.instructions||[]).length;if(steps<=4)s+=.35;else if(steps>=8)s-=.45;if((recipe.ingredients||[]).length<=9)s+=.25;else if((recipe.ingredients||[]).length>=15)s-=.35;return s;}
function weekendOpportunityScore(recipe){const mins=minuteEstimate(recipe),steps=(recipe.instructions||[]).length,ings=(recipe.ingredients||[]).length;let s=0;if(mins&&mins>=35)s+=.55;if(steps>=6)s+=.35;if(ings>=12)s+=.2;return s;}
function contextAdjustment(recipe,dayIndex,mealType,prefs={}){const weekday=dayIndex<5;let adj=0;if(weekday&&mealType==='lunch'&&prefs.packableWeekdayLunches!==false)adj-=compactLunchScore(recipe)*.65;if(weekday&&mealType==='dinner'&&prefs.quickWeekdayDinners!==false)adj-=easeScore(recipe)*.7;if(!weekday&&prefs.weekendFlexibility!==false)adj-=weekendOpportunityScore(recipe)*.25;return adj;}
function bestServings(recipe,targetCalories,targetProtein,peopleCount){const min=Math.max(1,peopleCount||1);if(recipe.caloriesPerServing==null)return min;const c=Math.max(1,Number(recipe.caloriesPerServing));const max=Math.max(min,min*2);let best=min,bestScore=Infinity;for(let s=min;s<=max;s++){let score=Math.abs(c*s-targetCalories)/Math.max(targetCalories,1);if(recipe.proteinPerServing!=null&&targetProtein>0)score+=.35*Math.abs(recipe.proteinPerServing*s-targetProtein)/targetProtein;const perPerson=s/Math.max(peopleCount,1);if(perPerson>1.75)score+=(perPerson-1.75)*.12;if(score<bestScore){bestScore=score;best=s;}}return best;}
function scoreCandidate(recipe,servings,targetCalories,targetProtein,usedCount,sameDay,dayIndex,mealType,prefs){let score=0;if(recipe.caloriesPerServing!=null)score+=Math.abs(recipe.caloriesPerServing*servings-targetCalories)/Math.max(targetCalories,1);else score+=1.8;if(recipe.proteinPerServing!=null&&targetProtein>0)score+=.35*Math.abs(recipe.proteinPerServing*servings-targetProtein)/targetProtein;else score+=.2;score+=(usedCount||0)*.22;if(sameDay)score+=1.5;if(recipe.needsReview)score+=.35;score+=contextAdjustment(recipe,dayIndex,mealType,prefs);return score;}
export function householdTargets(profile={}){const people=(profile.people||[]).filter(Boolean);return {peopleCount:Math.max(1,people.length),calories:people.reduce((s,p)=>s+(Number(p.targetCalories)||0),0),protein:people.reduce((s,p)=>s+(Number(p.targetProtein)||0),0)};}
export function servingAudit(recipe,servings,targetCalories,targetProtein,peopleCount){const c=recipe?.caloriesPerServing!=null?recipe.caloriesPerServing*servings:null,p=recipe?.proteinPerServing!=null?recipe.proteinPerServing*servings:null;return {servings,perPerson:servings/Math.max(1,peopleCount),calories:c,protein:p,calorieDelta:c==null?null:c-targetCalories,proteinDelta:p==null?null:p-targetProtein};}
export async function autoPlanWeek(date,recipeList,profile={},favoriteRecipeIds=[],options={}){const plan=await loadWeek(date);const selected=options.mealTypes?.length?options.mealTypes:['breakfast','lunch','dinner','snack'];const replace=options.replace===true;const prefs={packableWeekdayLunches:options.packableWeekdayLunches!==false,quickWeekdayDinners:options.quickWeekdayDinners!==false,weekendFlexibility:options.weekendFlexibility!==false};const targets=householdTargets(profile);const weight=m=>(WEIGHTS[m]||0);const excluded=(d,m)=>plan.exclusions.some(x=>x.dayIndex===d&&x.mealType===m);
if(replace)plan.entries=plan.entries.filter(e=>!selected.includes(e.mealType)||excluded(e.dayIndex,e.mealType));
const slotHas=(d,m)=>plan.entries.some(e=>e.dayIndex===d&&e.mealType===m);
const used=new Map();for(const e of plan.entries)used.set(e.recipeId,(used.get(e.recipeId)||0)+1);
const add=(d,m,r)=>{const tc=targets.calories*weight(m),tp=targets.protein*weight(m),serv=bestServings(r,tc,tp,targets.peopleCount);plan.entries.push({id:`meal-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,dayIndex:d,mealType:m,recipeId:r.id,servings:serv,autoGenerated:true});used.set(r.id,(used.get(r.id)||0)+1);};
for(const id of favoriteRecipeIds||[]){const r=recipeList.find(x=>x.id===id);if(!r||r.bad||r.servingsUnknown||r.caloriesPerServing==null)continue;const meals=(r.mealTypes||[]).filter(m=>selected.includes(m));let bestSlot=null;for(const m of meals){for(let d=0;d<7;d++){if(excluded(d,m)||slotHas(d,m))continue;const tc=targets.calories*weight(m),tp=targets.protein*weight(m),serv=bestServings(r,tc,tp,targets.peopleCount),sc=scoreCandidate(r,serv,tc,tp,used.get(r.id)||0,false,d,m,prefs);if(!bestSlot||sc<bestSlot.score)bestSlot={d,m,score:sc};}}if(bestSlot)add(bestSlot.d,bestSlot.m,r);}
for(let d=0;d<7;d++)for(const m of selected){if(excluded(d,m)||slotHas(d,m))continue;const candidates=recipeList.filter(r=>!r.bad&&!r.servingsUnknown&&r.caloriesPerServing!=null&&(r.mealTypes||[]).includes(m));if(!candidates.length)continue;const tc=targets.calories*weight(m),tp=targets.protein*weight(m);let best=null;for(const r of candidates){const serv=bestServings(r,tc,tp,targets.peopleCount);const sameDay=plan.entries.some(e=>e.dayIndex===d&&e.recipeId===r.id);const sc=scoreCandidate(r,serv,tc,tp,used.get(r.id)||0,sameDay,d,m,prefs);if(!best||sc<best.score)best={r,score:sc};}if(best)add(d,m,best.r);}
plan.autoPlan={generatedAt:new Date().toISOString(),profileSnapshot:profile,targets,mealTypes:selected,favorites:favoriteRecipeIds||[],preferences:prefs};await saveWeek(plan);return plan;}
